/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AnswerValidationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class AnswerValidationDto {
  @JsonProperty("answerType")
  private String answerType = null;

  @JsonProperty("required")
  private Boolean required = false;

  @JsonProperty("otherAvailable")
  private Boolean otherAvailable = false;

  @JsonProperty("atLeast")
  private Integer atLeast = null;

  @JsonProperty("atMost")
  private Integer atMost = null;

  @JsonProperty("maximumLength")
  private Integer maximumLength = null;

  @JsonProperty("minimumLength")
  private Integer minimumLength = null;

  @JsonProperty("maximumValue")
  private Double maximumValue = null;

  @JsonProperty("minimumValue")
  private Double minimumValue = null;

  @JsonProperty("earlierThanDate")
  private String earlierThanDate = null;

  @JsonProperty("laterThanDate")
  private String laterThanDate = null;

  @JsonProperty("dateFormat")
  private String dateFormat = null;

  public AnswerValidationDto answerType(String answerType) {
    this.answerType = answerType;
    return this;
  }

   /**
   * Get answerType
   * @return answerType
  **/
  public String getAnswerType() {
    return answerType;
  }

  public void setAnswerType(String answerType) {
    this.answerType = answerType;
  }

  public AnswerValidationDto required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public AnswerValidationDto otherAvailable(Boolean otherAvailable) {
    this.otherAvailable = otherAvailable;
    return this;
  }

   /**
   * Get otherAvailable
   * @return otherAvailable
  **/
  public Boolean isOtherAvailable() {
    return otherAvailable;
  }

  public void setOtherAvailable(Boolean otherAvailable) {
    this.otherAvailable = otherAvailable;
  }

  public AnswerValidationDto atLeast(Integer atLeast) {
    this.atLeast = atLeast;
    return this;
  }

   /**
   * Get atLeast
   * @return atLeast
  **/
  public Integer getAtLeast() {
    return atLeast;
  }

  public void setAtLeast(Integer atLeast) {
    this.atLeast = atLeast;
  }

  public AnswerValidationDto atMost(Integer atMost) {
    this.atMost = atMost;
    return this;
  }

   /**
   * Get atMost
   * @return atMost
  **/
  public Integer getAtMost() {
    return atMost;
  }

  public void setAtMost(Integer atMost) {
    this.atMost = atMost;
  }

  public AnswerValidationDto maximumLength(Integer maximumLength) {
    this.maximumLength = maximumLength;
    return this;
  }

   /**
   * Get maximumLength
   * @return maximumLength
  **/
  public Integer getMaximumLength() {
    return maximumLength;
  }

  public void setMaximumLength(Integer maximumLength) {
    this.maximumLength = maximumLength;
  }

  public AnswerValidationDto minimumLength(Integer minimumLength) {
    this.minimumLength = minimumLength;
    return this;
  }

   /**
   * Get minimumLength
   * @return minimumLength
  **/
  public Integer getMinimumLength() {
    return minimumLength;
  }

  public void setMinimumLength(Integer minimumLength) {
    this.minimumLength = minimumLength;
  }

  public AnswerValidationDto maximumValue(Double maximumValue) {
    this.maximumValue = maximumValue;
    return this;
  }

   /**
   * Get maximumValue
   * @return maximumValue
  **/
  public Double getMaximumValue() {
    return maximumValue;
  }

  public void setMaximumValue(Double maximumValue) {
    this.maximumValue = maximumValue;
  }

  public AnswerValidationDto minimumValue(Double minimumValue) {
    this.minimumValue = minimumValue;
    return this;
  }

   /**
   * Get minimumValue
   * @return minimumValue
  **/
  public Double getMinimumValue() {
    return minimumValue;
  }

  public void setMinimumValue(Double minimumValue) {
    this.minimumValue = minimumValue;
  }

  public AnswerValidationDto earlierThanDate(String earlierThanDate) {
    this.earlierThanDate = earlierThanDate;
    return this;
  }

   /**
   * Get earlierThanDate
   * @return earlierThanDate
  **/
  public String getEarlierThanDate() {
    return earlierThanDate;
  }

  public void setEarlierThanDate(String earlierThanDate) {
    this.earlierThanDate = earlierThanDate;
  }

  public AnswerValidationDto laterThanDate(String laterThanDate) {
    this.laterThanDate = laterThanDate;
    return this;
  }

   /**
   * Get laterThanDate
   * @return laterThanDate
  **/
  public String getLaterThanDate() {
    return laterThanDate;
  }

  public void setLaterThanDate(String laterThanDate) {
    this.laterThanDate = laterThanDate;
  }

  public AnswerValidationDto dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerValidationDto answerValidationDto = (AnswerValidationDto) o;
    return Objects.equals(this.answerType, answerValidationDto.answerType) &&
        Objects.equals(this.required, answerValidationDto.required) &&
        Objects.equals(this.otherAvailable, answerValidationDto.otherAvailable) &&
        Objects.equals(this.atLeast, answerValidationDto.atLeast) &&
        Objects.equals(this.atMost, answerValidationDto.atMost) &&
        Objects.equals(this.maximumLength, answerValidationDto.maximumLength) &&
        Objects.equals(this.minimumLength, answerValidationDto.minimumLength) &&
        Objects.equals(this.maximumValue, answerValidationDto.maximumValue) &&
        Objects.equals(this.minimumValue, answerValidationDto.minimumValue) &&
        Objects.equals(this.earlierThanDate, answerValidationDto.earlierThanDate) &&
        Objects.equals(this.laterThanDate, answerValidationDto.laterThanDate) &&
        Objects.equals(this.dateFormat, answerValidationDto.dateFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answerType, required, otherAvailable, atLeast, atMost, maximumLength, minimumLength, maximumValue, minimumValue, earlierThanDate, laterThanDate, dateFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerValidationDto {\n");
    
    sb.append("    answerType: ").append(toIndentedString(answerType)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    otherAvailable: ").append(toIndentedString(otherAvailable)).append("\n");
    sb.append("    atLeast: ").append(toIndentedString(atLeast)).append("\n");
    sb.append("    atMost: ").append(toIndentedString(atMost)).append("\n");
    sb.append("    maximumLength: ").append(toIndentedString(maximumLength)).append("\n");
    sb.append("    minimumLength: ").append(toIndentedString(minimumLength)).append("\n");
    sb.append("    maximumValue: ").append(toIndentedString(maximumValue)).append("\n");
    sb.append("    minimumValue: ").append(toIndentedString(minimumValue)).append("\n");
    sb.append("    earlierThanDate: ").append(toIndentedString(earlierThanDate)).append("\n");
    sb.append("    laterThanDate: ").append(toIndentedString(laterThanDate)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
