/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ApplicationStatusDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class ApplicationStatusDto {
  @JsonProperty("applicationId")
  private Long applicationId = null;

  @JsonProperty("targetStatus")
  private String targetStatus = null;

  @JsonProperty("reasonOfChange")
  private String reasonOfChange = null;

  @JsonProperty("reasonOfCompletion")
  private String reasonOfCompletion = null;

  @JsonProperty("memo")
  private String memo = null;

  @JsonProperty("sendCancellationToCandidate")
  private Boolean sendCancellationToCandidate = false;

  @JsonProperty("offerAccepted")
  private Boolean offerAccepted = false;

  public ApplicationStatusDto applicationId(Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Long applicationId) {
    this.applicationId = applicationId;
  }

  public ApplicationStatusDto targetStatus(String targetStatus) {
    this.targetStatus = targetStatus;
    return this;
  }

   /**
   * Get targetStatus
   * @return targetStatus
  **/
  public String getTargetStatus() {
    return targetStatus;
  }

  public void setTargetStatus(String targetStatus) {
    this.targetStatus = targetStatus;
  }

  public ApplicationStatusDto reasonOfChange(String reasonOfChange) {
    this.reasonOfChange = reasonOfChange;
    return this;
  }

   /**
   * Get reasonOfChange
   * @return reasonOfChange
  **/
  public String getReasonOfChange() {
    return reasonOfChange;
  }

  public void setReasonOfChange(String reasonOfChange) {
    this.reasonOfChange = reasonOfChange;
  }

  public ApplicationStatusDto reasonOfCompletion(String reasonOfCompletion) {
    this.reasonOfCompletion = reasonOfCompletion;
    return this;
  }

   /**
   * Get reasonOfCompletion
   * @return reasonOfCompletion
  **/
  public String getReasonOfCompletion() {
    return reasonOfCompletion;
  }

  public void setReasonOfCompletion(String reasonOfCompletion) {
    this.reasonOfCompletion = reasonOfCompletion;
  }

  public ApplicationStatusDto memo(String memo) {
    this.memo = memo;
    return this;
  }

   /**
   * Get memo
   * @return memo
  **/
  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }

  public ApplicationStatusDto sendCancellationToCandidate(Boolean sendCancellationToCandidate) {
    this.sendCancellationToCandidate = sendCancellationToCandidate;
    return this;
  }

   /**
   * Get sendCancellationToCandidate
   * @return sendCancellationToCandidate
  **/
  public Boolean isSendCancellationToCandidate() {
    return sendCancellationToCandidate;
  }

  public void setSendCancellationToCandidate(Boolean sendCancellationToCandidate) {
    this.sendCancellationToCandidate = sendCancellationToCandidate;
  }

  public ApplicationStatusDto offerAccepted(Boolean offerAccepted) {
    this.offerAccepted = offerAccepted;
    return this;
  }

   /**
   * Get offerAccepted
   * @return offerAccepted
  **/
  public Boolean isOfferAccepted() {
    return offerAccepted;
  }

  public void setOfferAccepted(Boolean offerAccepted) {
    this.offerAccepted = offerAccepted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApplicationStatusDto applicationStatusDto = (ApplicationStatusDto) o;
    return Objects.equals(this.applicationId, applicationStatusDto.applicationId) &&
        Objects.equals(this.targetStatus, applicationStatusDto.targetStatus) &&
        Objects.equals(this.reasonOfChange, applicationStatusDto.reasonOfChange) &&
        Objects.equals(this.reasonOfCompletion, applicationStatusDto.reasonOfCompletion) &&
        Objects.equals(this.memo, applicationStatusDto.memo) &&
        Objects.equals(this.sendCancellationToCandidate, applicationStatusDto.sendCancellationToCandidate) &&
        Objects.equals(this.offerAccepted, applicationStatusDto.offerAccepted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationId, targetStatus, reasonOfChange, reasonOfCompletion, memo, sendCancellationToCandidate, offerAccepted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApplicationStatusDto {\n");
    
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    targetStatus: ").append(toIndentedString(targetStatus)).append("\n");
    sb.append("    reasonOfChange: ").append(toIndentedString(reasonOfChange)).append("\n");
    sb.append("    reasonOfCompletion: ").append(toIndentedString(reasonOfCompletion)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("    sendCancellationToCandidate: ").append(toIndentedString(sendCancellationToCandidate)).append("\n");
    sb.append("    offerAccepted: ").append(toIndentedString(offerAccepted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
