/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.AssessmentTestDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.AssessmentTestGroupDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ExternalSystemDto;

import java.util.ArrayList;
import java.util.List;
/**
 * AssessmentTestGroupDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class AssessmentTestGroupDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("externalSystem")
  private ExternalSystemDto externalSystem = null;

  @JsonProperty("father")
  private AssessmentTestGroupDto father = null;

  @JsonProperty("assessmentTests")
  private List<AssessmentTestDto> assessmentTests = null;

  public AssessmentTestGroupDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AssessmentTestGroupDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AssessmentTestGroupDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AssessmentTestGroupDto externalSystem(ExternalSystemDto externalSystem) {
    this.externalSystem = externalSystem;
    return this;
  }

   /**
   * Get externalSystem
   * @return externalSystem
  **/
  public ExternalSystemDto getExternalSystem() {
    return externalSystem;
  }

  public void setExternalSystem(ExternalSystemDto externalSystem) {
    this.externalSystem = externalSystem;
  }

  public AssessmentTestGroupDto father(AssessmentTestGroupDto father) {
    this.father = father;
    return this;
  }

   /**
   * Get father
   * @return father
  **/
  public AssessmentTestGroupDto getFather() {
    return father;
  }

  public void setFather(AssessmentTestGroupDto father) {
    this.father = father;
  }

  public AssessmentTestGroupDto assessmentTests(List<AssessmentTestDto> assessmentTests) {
    this.assessmentTests = assessmentTests;
    return this;
  }

  public AssessmentTestGroupDto addAssessmentTestsItem(AssessmentTestDto assessmentTestsItem) {
    if (this.assessmentTests == null) {
      this.assessmentTests = new ArrayList<>();
    }
    this.assessmentTests.add(assessmentTestsItem);
    return this;
  }

   /**
   * Get assessmentTests
   * @return assessmentTests
  **/
  public List<AssessmentTestDto> getAssessmentTests() {
    return assessmentTests;
  }

  public void setAssessmentTests(List<AssessmentTestDto> assessmentTests) {
    this.assessmentTests = assessmentTests;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssessmentTestGroupDto assessmentTestGroupDto = (AssessmentTestGroupDto) o;
    return Objects.equals(this.id, assessmentTestGroupDto.id) &&
        Objects.equals(this.name, assessmentTestGroupDto.name) &&
        Objects.equals(this.description, assessmentTestGroupDto.description) &&
        Objects.equals(this.externalSystem, assessmentTestGroupDto.externalSystem) &&
        Objects.equals(this.father, assessmentTestGroupDto.father) &&
        Objects.equals(this.assessmentTests, assessmentTestGroupDto.assessmentTests);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, externalSystem, father, assessmentTests);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssessmentTestGroupDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    externalSystem: ").append(toIndentedString(externalSystem)).append("\n");
    sb.append("    father: ").append(toIndentedString(father)).append("\n");
    sb.append("    assessmentTests: ").append(toIndentedString(assessmentTests)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
