/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * AssignedOptionDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class AssignedOptionDto {
  @JsonProperty("assignedOptionId")
  private Long assignedOptionId = null;

  @JsonProperty("dependingQuestionIds")
  private List<Long> dependingQuestionIds = null;

  @JsonProperty("optionId")
  private Long optionId = null;

  @JsonProperty("order")
  private Long order = null;

  @JsonProperty("optionScore")
  private Long optionScore = null;

  @JsonProperty("hasScore")
  private Boolean hasScore = false;

  @JsonProperty("isDefault")
  private Boolean isDefault = false;

  @JsonProperty("unlocalValue")
  private String unlocalValue = null;

  @JsonProperty("localizedLabel")
  private String localizedLabel = null;

  public AssignedOptionDto assignedOptionId(Long assignedOptionId) {
    this.assignedOptionId = assignedOptionId;
    return this;
  }

   /**
   * Get assignedOptionId
   * @return assignedOptionId
  **/
  public Long getAssignedOptionId() {
    return assignedOptionId;
  }

  public void setAssignedOptionId(Long assignedOptionId) {
    this.assignedOptionId = assignedOptionId;
  }

  public AssignedOptionDto dependingQuestionIds(List<Long> dependingQuestionIds) {
    this.dependingQuestionIds = dependingQuestionIds;
    return this;
  }

  public AssignedOptionDto addDependingQuestionIdsItem(Long dependingQuestionIdsItem) {
    if (this.dependingQuestionIds == null) {
      this.dependingQuestionIds = new ArrayList<>();
    }
    this.dependingQuestionIds.add(dependingQuestionIdsItem);
    return this;
  }

   /**
   * Get dependingQuestionIds
   * @return dependingQuestionIds
  **/
  public List<Long> getDependingQuestionIds() {
    return dependingQuestionIds;
  }

  public void setDependingQuestionIds(List<Long> dependingQuestionIds) {
    this.dependingQuestionIds = dependingQuestionIds;
  }

  public AssignedOptionDto optionId(Long optionId) {
    this.optionId = optionId;
    return this;
  }

   /**
   * Get optionId
   * @return optionId
  **/
  public Long getOptionId() {
    return optionId;
  }

  public void setOptionId(Long optionId) {
    this.optionId = optionId;
  }

  public AssignedOptionDto order(Long order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  public Long getOrder() {
    return order;
  }

  public void setOrder(Long order) {
    this.order = order;
  }

  public AssignedOptionDto optionScore(Long optionScore) {
    this.optionScore = optionScore;
    return this;
  }

   /**
   * Get optionScore
   * @return optionScore
  **/
  public Long getOptionScore() {
    return optionScore;
  }

  public void setOptionScore(Long optionScore) {
    this.optionScore = optionScore;
  }

  public AssignedOptionDto hasScore(Boolean hasScore) {
    this.hasScore = hasScore;
    return this;
  }

   /**
   * Get hasScore
   * @return hasScore
  **/
  public Boolean isHasScore() {
    return hasScore;
  }

  public void setHasScore(Boolean hasScore) {
    this.hasScore = hasScore;
  }

  public AssignedOptionDto isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  public Boolean isIsDefault() {
    return isDefault;
  }

  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public AssignedOptionDto unlocalValue(String unlocalValue) {
    this.unlocalValue = unlocalValue;
    return this;
  }

   /**
   * Get unlocalValue
   * @return unlocalValue
  **/
  public String getUnlocalValue() {
    return unlocalValue;
  }

  public void setUnlocalValue(String unlocalValue) {
    this.unlocalValue = unlocalValue;
  }

  public AssignedOptionDto localizedLabel(String localizedLabel) {
    this.localizedLabel = localizedLabel;
    return this;
  }

   /**
   * Get localizedLabel
   * @return localizedLabel
  **/
  public String getLocalizedLabel() {
    return localizedLabel;
  }

  public void setLocalizedLabel(String localizedLabel) {
    this.localizedLabel = localizedLabel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssignedOptionDto assignedOptionDto = (AssignedOptionDto) o;
    return Objects.equals(this.assignedOptionId, assignedOptionDto.assignedOptionId) &&
        Objects.equals(this.dependingQuestionIds, assignedOptionDto.dependingQuestionIds) &&
        Objects.equals(this.optionId, assignedOptionDto.optionId) &&
        Objects.equals(this.order, assignedOptionDto.order) &&
        Objects.equals(this.optionScore, assignedOptionDto.optionScore) &&
        Objects.equals(this.hasScore, assignedOptionDto.hasScore) &&
        Objects.equals(this.isDefault, assignedOptionDto.isDefault) &&
        Objects.equals(this.unlocalValue, assignedOptionDto.unlocalValue) &&
        Objects.equals(this.localizedLabel, assignedOptionDto.localizedLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assignedOptionId, dependingQuestionIds, optionId, order, optionScore, hasScore, isDefault, unlocalValue, localizedLabel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssignedOptionDto {\n");
    
    sb.append("    assignedOptionId: ").append(toIndentedString(assignedOptionId)).append("\n");
    sb.append("    dependingQuestionIds: ").append(toIndentedString(dependingQuestionIds)).append("\n");
    sb.append("    optionId: ").append(toIndentedString(optionId)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    optionScore: ").append(toIndentedString(optionScore)).append("\n");
    sb.append("    hasScore: ").append(toIndentedString(hasScore)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    unlocalValue: ").append(toIndentedString(unlocalValue)).append("\n");
    sb.append("    localizedLabel: ").append(toIndentedString(localizedLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
