/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicApprovalProcessDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicFreeFormFieldDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicLovDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ContractorDetailsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.IdDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.MidPeriodConfigBasicDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.PermanentDetailsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TimesheetConfigBasicDto;

import java.util.ArrayList;
import java.util.List;
/**
 * BasicContractDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class BasicContractDto {
  @JsonProperty("approved")
  private Boolean approved = false;

  @JsonProperty("accepted")
  private Boolean accepted = false;

  @JsonProperty("acceptApproved")
  private Boolean acceptApproved = false;

  @JsonProperty("administrativeComments")
  private String administrativeComments = null;

  @JsonProperty("plannedStartDate")
  private Long plannedStartDate = null;

  @JsonProperty("plannedEndDate")
  private Long plannedEndDate = null;

  @JsonProperty("scheduleType")
  private String scheduleType = null;

  @JsonProperty("workAmount")
  private Float workAmount = null;

  @JsonProperty("workPeriod")
  private String workPeriod = null;

  @JsonProperty("workUnit")
  private String workUnit = null;

  @JsonProperty("bonusCondition")
  private String bonusCondition = null;

  @JsonProperty("contractType")
  private String contractType = null;

  @JsonProperty("length")
  private Float length = null;

  @JsonProperty("lengthUnit")
  private String lengthUnit = null;

  @JsonProperty("permanentDetails")
  private PermanentDetailsDto permanentDetails = null;

  @JsonProperty("contractorDetails")
  private ContractorDetailsDto contractorDetails = null;

  @JsonProperty("allowConcurrentContracts")
  private Boolean allowConcurrentContracts = false;

  @JsonProperty("allowHeadCountSkip")
  private Boolean allowHeadCountSkip = false;

  @JsonProperty("application")
  private IdDto application = null;

  @JsonProperty("lovs")
  private List<BasicLovDto> lovs = null;

  @JsonProperty("freeFormFields")
  private List<BasicFreeFormFieldDto> freeFormFields = null;

  @JsonProperty("approvalProcess")
  private BasicApprovalProcessDto approvalProcess = null;

  @JsonProperty("timesheetConfig")
  private TimesheetConfigBasicDto timesheetConfig = null;

  @JsonProperty("midPeriodsConfigs")
  private List<MidPeriodConfigBasicDto> midPeriodsConfigs = null;

  public BasicContractDto approved(Boolean approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  public Boolean isApproved() {
    return approved;
  }

  public void setApproved(Boolean approved) {
    this.approved = approved;
  }

  public BasicContractDto accepted(Boolean accepted) {
    this.accepted = accepted;
    return this;
  }

   /**
   * Get accepted
   * @return accepted
  **/
  public Boolean isAccepted() {
    return accepted;
  }

  public void setAccepted(Boolean accepted) {
    this.accepted = accepted;
  }

  public BasicContractDto acceptApproved(Boolean acceptApproved) {
    this.acceptApproved = acceptApproved;
    return this;
  }

   /**
   * Get acceptApproved
   * @return acceptApproved
  **/
  public Boolean isAcceptApproved() {
    return acceptApproved;
  }

  public void setAcceptApproved(Boolean acceptApproved) {
    this.acceptApproved = acceptApproved;
  }

  public BasicContractDto administrativeComments(String administrativeComments) {
    this.administrativeComments = administrativeComments;
    return this;
  }

   /**
   * Get administrativeComments
   * @return administrativeComments
  **/
  public String getAdministrativeComments() {
    return administrativeComments;
  }

  public void setAdministrativeComments(String administrativeComments) {
    this.administrativeComments = administrativeComments;
  }

  public BasicContractDto plannedStartDate(Long plannedStartDate) {
    this.plannedStartDate = plannedStartDate;
    return this;
  }

   /**
   * Get plannedStartDate
   * @return plannedStartDate
  **/
  public Long getPlannedStartDate() {
    return plannedStartDate;
  }

  public void setPlannedStartDate(Long plannedStartDate) {
    this.plannedStartDate = plannedStartDate;
  }

  public BasicContractDto plannedEndDate(Long plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
    return this;
  }

   /**
   * Get plannedEndDate
   * @return plannedEndDate
  **/
  public Long getPlannedEndDate() {
    return plannedEndDate;
  }

  public void setPlannedEndDate(Long plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
  }

  public BasicContractDto scheduleType(String scheduleType) {
    this.scheduleType = scheduleType;
    return this;
  }

   /**
   * Get scheduleType
   * @return scheduleType
  **/
  public String getScheduleType() {
    return scheduleType;
  }

  public void setScheduleType(String scheduleType) {
    this.scheduleType = scheduleType;
  }

  public BasicContractDto workAmount(Float workAmount) {
    this.workAmount = workAmount;
    return this;
  }

   /**
   * Get workAmount
   * @return workAmount
  **/
  public Float getWorkAmount() {
    return workAmount;
  }

  public void setWorkAmount(Float workAmount) {
    this.workAmount = workAmount;
  }

  public BasicContractDto workPeriod(String workPeriod) {
    this.workPeriod = workPeriod;
    return this;
  }

   /**
   * Get workPeriod
   * @return workPeriod
  **/
  public String getWorkPeriod() {
    return workPeriod;
  }

  public void setWorkPeriod(String workPeriod) {
    this.workPeriod = workPeriod;
  }

  public BasicContractDto workUnit(String workUnit) {
    this.workUnit = workUnit;
    return this;
  }

   /**
   * Get workUnit
   * @return workUnit
  **/
  public String getWorkUnit() {
    return workUnit;
  }

  public void setWorkUnit(String workUnit) {
    this.workUnit = workUnit;
  }

  public BasicContractDto bonusCondition(String bonusCondition) {
    this.bonusCondition = bonusCondition;
    return this;
  }

   /**
   * Get bonusCondition
   * @return bonusCondition
  **/
  public String getBonusCondition() {
    return bonusCondition;
  }

  public void setBonusCondition(String bonusCondition) {
    this.bonusCondition = bonusCondition;
  }

  public BasicContractDto contractType(String contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  public String getContractType() {
    return contractType;
  }

  public void setContractType(String contractType) {
    this.contractType = contractType;
  }

  public BasicContractDto length(Float length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  public Float getLength() {
    return length;
  }

  public void setLength(Float length) {
    this.length = length;
  }

  public BasicContractDto lengthUnit(String lengthUnit) {
    this.lengthUnit = lengthUnit;
    return this;
  }

   /**
   * Get lengthUnit
   * @return lengthUnit
  **/
  public String getLengthUnit() {
    return lengthUnit;
  }

  public void setLengthUnit(String lengthUnit) {
    this.lengthUnit = lengthUnit;
  }

  public BasicContractDto permanentDetails(PermanentDetailsDto permanentDetails) {
    this.permanentDetails = permanentDetails;
    return this;
  }

   /**
   * Get permanentDetails
   * @return permanentDetails
  **/
  public PermanentDetailsDto getPermanentDetails() {
    return permanentDetails;
  }

  public void setPermanentDetails(PermanentDetailsDto permanentDetails) {
    this.permanentDetails = permanentDetails;
  }

  public BasicContractDto contractorDetails(ContractorDetailsDto contractorDetails) {
    this.contractorDetails = contractorDetails;
    return this;
  }

   /**
   * Get contractorDetails
   * @return contractorDetails
  **/
  public ContractorDetailsDto getContractorDetails() {
    return contractorDetails;
  }

  public void setContractorDetails(ContractorDetailsDto contractorDetails) {
    this.contractorDetails = contractorDetails;
  }

  public BasicContractDto allowConcurrentContracts(Boolean allowConcurrentContracts) {
    this.allowConcurrentContracts = allowConcurrentContracts;
    return this;
  }

   /**
   * Get allowConcurrentContracts
   * @return allowConcurrentContracts
  **/
  public Boolean isAllowConcurrentContracts() {
    return allowConcurrentContracts;
  }

  public void setAllowConcurrentContracts(Boolean allowConcurrentContracts) {
    this.allowConcurrentContracts = allowConcurrentContracts;
  }

  public BasicContractDto allowHeadCountSkip(Boolean allowHeadCountSkip) {
    this.allowHeadCountSkip = allowHeadCountSkip;
    return this;
  }

   /**
   * Get allowHeadCountSkip
   * @return allowHeadCountSkip
  **/
  public Boolean isAllowHeadCountSkip() {
    return allowHeadCountSkip;
  }

  public void setAllowHeadCountSkip(Boolean allowHeadCountSkip) {
    this.allowHeadCountSkip = allowHeadCountSkip;
  }

  public BasicContractDto application(IdDto application) {
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  public IdDto getApplication() {
    return application;
  }

  public void setApplication(IdDto application) {
    this.application = application;
  }

  public BasicContractDto lovs(List<BasicLovDto> lovs) {
    this.lovs = lovs;
    return this;
  }

  public BasicContractDto addLovsItem(BasicLovDto lovsItem) {
    if (this.lovs == null) {
      this.lovs = new ArrayList<>();
    }
    this.lovs.add(lovsItem);
    return this;
  }

   /**
   * Get lovs
   * @return lovs
  **/
  public List<BasicLovDto> getLovs() {
    return lovs;
  }

  public void setLovs(List<BasicLovDto> lovs) {
    this.lovs = lovs;
  }

  public BasicContractDto freeFormFields(List<BasicFreeFormFieldDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
    return this;
  }

  public BasicContractDto addFreeFormFieldsItem(BasicFreeFormFieldDto freeFormFieldsItem) {
    if (this.freeFormFields == null) {
      this.freeFormFields = new ArrayList<>();
    }
    this.freeFormFields.add(freeFormFieldsItem);
    return this;
  }

   /**
   * Get freeFormFields
   * @return freeFormFields
  **/
  public List<BasicFreeFormFieldDto> getFreeFormFields() {
    return freeFormFields;
  }

  public void setFreeFormFields(List<BasicFreeFormFieldDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
  }

  public BasicContractDto approvalProcess(BasicApprovalProcessDto approvalProcess) {
    this.approvalProcess = approvalProcess;
    return this;
  }

   /**
   * Get approvalProcess
   * @return approvalProcess
  **/
  public BasicApprovalProcessDto getApprovalProcess() {
    return approvalProcess;
  }

  public void setApprovalProcess(BasicApprovalProcessDto approvalProcess) {
    this.approvalProcess = approvalProcess;
  }

  public BasicContractDto timesheetConfig(TimesheetConfigBasicDto timesheetConfig) {
    this.timesheetConfig = timesheetConfig;
    return this;
  }

   /**
   * Get timesheetConfig
   * @return timesheetConfig
  **/
  public TimesheetConfigBasicDto getTimesheetConfig() {
    return timesheetConfig;
  }

  public void setTimesheetConfig(TimesheetConfigBasicDto timesheetConfig) {
    this.timesheetConfig = timesheetConfig;
  }

  public BasicContractDto midPeriodsConfigs(List<MidPeriodConfigBasicDto> midPeriodsConfigs) {
    this.midPeriodsConfigs = midPeriodsConfigs;
    return this;
  }

  public BasicContractDto addMidPeriodsConfigsItem(MidPeriodConfigBasicDto midPeriodsConfigsItem) {
    if (this.midPeriodsConfigs == null) {
      this.midPeriodsConfigs = new ArrayList<>();
    }
    this.midPeriodsConfigs.add(midPeriodsConfigsItem);
    return this;
  }

   /**
   * Get midPeriodsConfigs
   * @return midPeriodsConfigs
  **/
  public List<MidPeriodConfigBasicDto> getMidPeriodsConfigs() {
    return midPeriodsConfigs;
  }

  public void setMidPeriodsConfigs(List<MidPeriodConfigBasicDto> midPeriodsConfigs) {
    this.midPeriodsConfigs = midPeriodsConfigs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicContractDto basicContractDto = (BasicContractDto) o;
    return Objects.equals(this.approved, basicContractDto.approved) &&
        Objects.equals(this.accepted, basicContractDto.accepted) &&
        Objects.equals(this.acceptApproved, basicContractDto.acceptApproved) &&
        Objects.equals(this.administrativeComments, basicContractDto.administrativeComments) &&
        Objects.equals(this.plannedStartDate, basicContractDto.plannedStartDate) &&
        Objects.equals(this.plannedEndDate, basicContractDto.plannedEndDate) &&
        Objects.equals(this.scheduleType, basicContractDto.scheduleType) &&
        Objects.equals(this.workAmount, basicContractDto.workAmount) &&
        Objects.equals(this.workPeriod, basicContractDto.workPeriod) &&
        Objects.equals(this.workUnit, basicContractDto.workUnit) &&
        Objects.equals(this.bonusCondition, basicContractDto.bonusCondition) &&
        Objects.equals(this.contractType, basicContractDto.contractType) &&
        Objects.equals(this.length, basicContractDto.length) &&
        Objects.equals(this.lengthUnit, basicContractDto.lengthUnit) &&
        Objects.equals(this.permanentDetails, basicContractDto.permanentDetails) &&
        Objects.equals(this.contractorDetails, basicContractDto.contractorDetails) &&
        Objects.equals(this.allowConcurrentContracts, basicContractDto.allowConcurrentContracts) &&
        Objects.equals(this.allowHeadCountSkip, basicContractDto.allowHeadCountSkip) &&
        Objects.equals(this.application, basicContractDto.application) &&
        Objects.equals(this.lovs, basicContractDto.lovs) &&
        Objects.equals(this.freeFormFields, basicContractDto.freeFormFields) &&
        Objects.equals(this.approvalProcess, basicContractDto.approvalProcess) &&
        Objects.equals(this.timesheetConfig, basicContractDto.timesheetConfig) &&
        Objects.equals(this.midPeriodsConfigs, basicContractDto.midPeriodsConfigs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approved, accepted, acceptApproved, administrativeComments, plannedStartDate, plannedEndDate, scheduleType, workAmount, workPeriod, workUnit, bonusCondition, contractType, length, lengthUnit, permanentDetails, contractorDetails, allowConcurrentContracts, allowHeadCountSkip, application, lovs, freeFormFields, approvalProcess, timesheetConfig, midPeriodsConfigs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicContractDto {\n");
    
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    accepted: ").append(toIndentedString(accepted)).append("\n");
    sb.append("    acceptApproved: ").append(toIndentedString(acceptApproved)).append("\n");
    sb.append("    administrativeComments: ").append(toIndentedString(administrativeComments)).append("\n");
    sb.append("    plannedStartDate: ").append(toIndentedString(plannedStartDate)).append("\n");
    sb.append("    plannedEndDate: ").append(toIndentedString(plannedEndDate)).append("\n");
    sb.append("    scheduleType: ").append(toIndentedString(scheduleType)).append("\n");
    sb.append("    workAmount: ").append(toIndentedString(workAmount)).append("\n");
    sb.append("    workPeriod: ").append(toIndentedString(workPeriod)).append("\n");
    sb.append("    workUnit: ").append(toIndentedString(workUnit)).append("\n");
    sb.append("    bonusCondition: ").append(toIndentedString(bonusCondition)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    lengthUnit: ").append(toIndentedString(lengthUnit)).append("\n");
    sb.append("    permanentDetails: ").append(toIndentedString(permanentDetails)).append("\n");
    sb.append("    contractorDetails: ").append(toIndentedString(contractorDetails)).append("\n");
    sb.append("    allowConcurrentContracts: ").append(toIndentedString(allowConcurrentContracts)).append("\n");
    sb.append("    allowHeadCountSkip: ").append(toIndentedString(allowHeadCountSkip)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    lovs: ").append(toIndentedString(lovs)).append("\n");
    sb.append("    freeFormFields: ").append(toIndentedString(freeFormFields)).append("\n");
    sb.append("    approvalProcess: ").append(toIndentedString(approvalProcess)).append("\n");
    sb.append("    timesheetConfig: ").append(toIndentedString(timesheetConfig)).append("\n");
    sb.append("    midPeriodsConfigs: ").append(toIndentedString(midPeriodsConfigs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
