/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TaskNotificationDto;

import java.util.ArrayList;
import java.util.List;
/**
 * BasicEventNotificationConfigurationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class BasicEventNotificationConfigurationDto {
  /**
   * Gets or Sets frequency
   */
  public enum FrequencyEnum {
    ONCE_A_DAY("ONCE_A_DAY"),
    EVERY_HOUR("EVERY_HOUR");

    private String value;

    FrequencyEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FrequencyEnum fromValue(String input) {
      for (FrequencyEnum b : FrequencyEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("frequency")
  private FrequencyEnum frequency = null;

  @JsonProperty("activated")
  private Boolean activated = false;

  @JsonProperty("alertCandidate")
  private Boolean alertCandidate = false;

  @JsonProperty("alertMessage")
  private Boolean alertMessage = false;

  @JsonProperty("alertNewTimesheets")
  private Boolean alertNewTimesheets = false;

  @JsonProperty("plainTextAlerts")
  private Boolean plainTextAlerts = false;

  @JsonProperty("taskNotificationActive")
  private Boolean taskNotificationActive = false;

  @JsonProperty("taskNotifications")
  private List<TaskNotificationDto> taskNotifications = new ArrayList<>();

  public BasicEventNotificationConfigurationDto frequency(FrequencyEnum frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  public FrequencyEnum getFrequency() {
    return frequency;
  }

  public void setFrequency(FrequencyEnum frequency) {
    this.frequency = frequency;
  }

  public BasicEventNotificationConfigurationDto activated(Boolean activated) {
    this.activated = activated;
    return this;
  }

   /**
   * Get activated
   * @return activated
  **/
  public Boolean isActivated() {
    return activated;
  }

  public void setActivated(Boolean activated) {
    this.activated = activated;
  }

  public BasicEventNotificationConfigurationDto alertCandidate(Boolean alertCandidate) {
    this.alertCandidate = alertCandidate;
    return this;
  }

   /**
   * Get alertCandidate
   * @return alertCandidate
  **/
  public Boolean isAlertCandidate() {
    return alertCandidate;
  }

  public void setAlertCandidate(Boolean alertCandidate) {
    this.alertCandidate = alertCandidate;
  }

  public BasicEventNotificationConfigurationDto alertMessage(Boolean alertMessage) {
    this.alertMessage = alertMessage;
    return this;
  }

   /**
   * Get alertMessage
   * @return alertMessage
  **/
  public Boolean isAlertMessage() {
    return alertMessage;
  }

  public void setAlertMessage(Boolean alertMessage) {
    this.alertMessage = alertMessage;
  }

  public BasicEventNotificationConfigurationDto alertNewTimesheets(Boolean alertNewTimesheets) {
    this.alertNewTimesheets = alertNewTimesheets;
    return this;
  }

   /**
   * Get alertNewTimesheets
   * @return alertNewTimesheets
  **/
  public Boolean isAlertNewTimesheets() {
    return alertNewTimesheets;
  }

  public void setAlertNewTimesheets(Boolean alertNewTimesheets) {
    this.alertNewTimesheets = alertNewTimesheets;
  }

  public BasicEventNotificationConfigurationDto plainTextAlerts(Boolean plainTextAlerts) {
    this.plainTextAlerts = plainTextAlerts;
    return this;
  }

   /**
   * Get plainTextAlerts
   * @return plainTextAlerts
  **/
  public Boolean isPlainTextAlerts() {
    return plainTextAlerts;
  }

  public void setPlainTextAlerts(Boolean plainTextAlerts) {
    this.plainTextAlerts = plainTextAlerts;
  }

  public BasicEventNotificationConfigurationDto taskNotificationActive(Boolean taskNotificationActive) {
    this.taskNotificationActive = taskNotificationActive;
    return this;
  }

   /**
   * Get taskNotificationActive
   * @return taskNotificationActive
  **/
  public Boolean isTaskNotificationActive() {
    return taskNotificationActive;
  }

  public void setTaskNotificationActive(Boolean taskNotificationActive) {
    this.taskNotificationActive = taskNotificationActive;
  }

  public BasicEventNotificationConfigurationDto taskNotifications(List<TaskNotificationDto> taskNotifications) {
    this.taskNotifications = taskNotifications;
    return this;
  }

  public BasicEventNotificationConfigurationDto addTaskNotificationsItem(TaskNotificationDto taskNotificationsItem) {
    this.taskNotifications.add(taskNotificationsItem);
    return this;
  }

   /**
   * Get taskNotifications
   * @return taskNotifications
  **/
  public List<TaskNotificationDto> getTaskNotifications() {
    return taskNotifications;
  }

  public void setTaskNotifications(List<TaskNotificationDto> taskNotifications) {
    this.taskNotifications = taskNotifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicEventNotificationConfigurationDto basicEventNotificationConfigurationDto = (BasicEventNotificationConfigurationDto) o;
    return Objects.equals(this.frequency, basicEventNotificationConfigurationDto.frequency) &&
        Objects.equals(this.activated, basicEventNotificationConfigurationDto.activated) &&
        Objects.equals(this.alertCandidate, basicEventNotificationConfigurationDto.alertCandidate) &&
        Objects.equals(this.alertMessage, basicEventNotificationConfigurationDto.alertMessage) &&
        Objects.equals(this.alertNewTimesheets, basicEventNotificationConfigurationDto.alertNewTimesheets) &&
        Objects.equals(this.plainTextAlerts, basicEventNotificationConfigurationDto.plainTextAlerts) &&
        Objects.equals(this.taskNotificationActive, basicEventNotificationConfigurationDto.taskNotificationActive) &&
        Objects.equals(this.taskNotifications, basicEventNotificationConfigurationDto.taskNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequency, activated, alertCandidate, alertMessage, alertNewTimesheets, plainTextAlerts, taskNotificationActive, taskNotifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicEventNotificationConfigurationDto {\n");
    
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    activated: ").append(toIndentedString(activated)).append("\n");
    sb.append("    alertCandidate: ").append(toIndentedString(alertCandidate)).append("\n");
    sb.append("    alertMessage: ").append(toIndentedString(alertMessage)).append("\n");
    sb.append("    alertNewTimesheets: ").append(toIndentedString(alertNewTimesheets)).append("\n");
    sb.append("    plainTextAlerts: ").append(toIndentedString(plainTextAlerts)).append("\n");
    sb.append("    taskNotificationActive: ").append(toIndentedString(taskNotificationActive)).append("\n");
    sb.append("    taskNotifications: ").append(toIndentedString(taskNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
