/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicApproverDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.CommunicationToApproverDto;

import java.util.ArrayList;
import java.util.List;
/**
 * BasicApprovalProcessDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class BasicApprovalProcessDto {
  @JsonProperty("dueDate")
  private Long dueDate = null;

  /**
   * Gets or Sets approvalMethod
   */
  public enum ApprovalMethodEnum {
    COLLABORATIVE("collaborative"),
    SEQUENTIAL("sequential"),
    MANUALLY("manually");

    private String value;

    ApprovalMethodEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ApprovalMethodEnum fromValue(String input) {
      for (ApprovalMethodEnum b : ApprovalMethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("approvalMethod")
  private ApprovalMethodEnum approvalMethod = null;

  @JsonProperty("minApprovers")
  private Integer minApprovers = null;

  @JsonProperty("approvers")
  private List<BasicApproverDto> approvers = null;

  @JsonProperty("communicationToApprover")
  private CommunicationToApproverDto communicationToApprover = null;

  @JsonProperty("useAlwaysRecommendation")
  private Boolean useAlwaysRecommendation = false;

  public BasicApprovalProcessDto dueDate(Long dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  public Long getDueDate() {
    return dueDate;
  }

  public void setDueDate(Long dueDate) {
    this.dueDate = dueDate;
  }

  public BasicApprovalProcessDto approvalMethod(ApprovalMethodEnum approvalMethod) {
    this.approvalMethod = approvalMethod;
    return this;
  }

   /**
   * Get approvalMethod
   * @return approvalMethod
  **/
  public ApprovalMethodEnum getApprovalMethod() {
    return approvalMethod;
  }

  public void setApprovalMethod(ApprovalMethodEnum approvalMethod) {
    this.approvalMethod = approvalMethod;
  }

  public BasicApprovalProcessDto minApprovers(Integer minApprovers) {
    this.minApprovers = minApprovers;
    return this;
  }

   /**
   * Get minApprovers
   * @return minApprovers
  **/
  public Integer getMinApprovers() {
    return minApprovers;
  }

  public void setMinApprovers(Integer minApprovers) {
    this.minApprovers = minApprovers;
  }

  public BasicApprovalProcessDto approvers(List<BasicApproverDto> approvers) {
    this.approvers = approvers;
    return this;
  }

  public BasicApprovalProcessDto addApproversItem(BasicApproverDto approversItem) {
    if (this.approvers == null) {
      this.approvers = new ArrayList<>();
    }
    this.approvers.add(approversItem);
    return this;
  }

   /**
   * Get approvers
   * @return approvers
  **/
  public List<BasicApproverDto> getApprovers() {
    return approvers;
  }

  public void setApprovers(List<BasicApproverDto> approvers) {
    this.approvers = approvers;
  }

  public BasicApprovalProcessDto communicationToApprover(CommunicationToApproverDto communicationToApprover) {
    this.communicationToApprover = communicationToApprover;
    return this;
  }

   /**
   * Get communicationToApprover
   * @return communicationToApprover
  **/
  public CommunicationToApproverDto getCommunicationToApprover() {
    return communicationToApprover;
  }

  public void setCommunicationToApprover(CommunicationToApproverDto communicationToApprover) {
    this.communicationToApprover = communicationToApprover;
  }

  public BasicApprovalProcessDto useAlwaysRecommendation(Boolean useAlwaysRecommendation) {
    this.useAlwaysRecommendation = useAlwaysRecommendation;
    return this;
  }

   /**
   * Get useAlwaysRecommendation
   * @return useAlwaysRecommendation
  **/
  public Boolean isUseAlwaysRecommendation() {
    return useAlwaysRecommendation;
  }

  public void setUseAlwaysRecommendation(Boolean useAlwaysRecommendation) {
    this.useAlwaysRecommendation = useAlwaysRecommendation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BasicApprovalProcessDto basicApprovalProcessDto = (BasicApprovalProcessDto) o;
    return Objects.equals(this.dueDate, basicApprovalProcessDto.dueDate) &&
        Objects.equals(this.approvalMethod, basicApprovalProcessDto.approvalMethod) &&
        Objects.equals(this.minApprovers, basicApprovalProcessDto.minApprovers) &&
        Objects.equals(this.approvers, basicApprovalProcessDto.approvers) &&
        Objects.equals(this.communicationToApprover, basicApprovalProcessDto.communicationToApprover) &&
        Objects.equals(this.useAlwaysRecommendation, basicApprovalProcessDto.useAlwaysRecommendation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dueDate, approvalMethod, minApprovers, approvers, communicationToApprover, useAlwaysRecommendation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BasicApprovalProcessDto {\n");
    
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    approvalMethod: ").append(toIndentedString(approvalMethod)).append("\n");
    sb.append("    minApprovers: ").append(toIndentedString(minApprovers)).append("\n");
    sb.append("    approvers: ").append(toIndentedString(approvers)).append("\n");
    sb.append("    communicationToApprover: ").append(toIndentedString(communicationToApprover)).append("\n");
    sb.append("    useAlwaysRecommendation: ").append(toIndentedString(useAlwaysRecommendation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
