/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ActionDto;

/**
 * CandidateGlobalActionsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CandidateGlobalActionsDto {
  @JsonProperty("create")
  private ActionDto create = null;

  @JsonProperty("markForArchiving")
  private ActionDto markForArchiving = null;

  @JsonProperty("unmarkFromArchiving")
  private ActionDto unmarkFromArchiving = null;

  @JsonProperty("fetchCandidateSummary")
  private ActionDto fetchCandidateSummary = null;

  public CandidateGlobalActionsDto create(ActionDto create) {
    this.create = create;
    return this;
  }

   /**
   * Get create
   * @return create
  **/
  public ActionDto getCreate() {
    return create;
  }

  public void setCreate(ActionDto create) {
    this.create = create;
  }

  public CandidateGlobalActionsDto markForArchiving(ActionDto markForArchiving) {
    this.markForArchiving = markForArchiving;
    return this;
  }

   /**
   * Get markForArchiving
   * @return markForArchiving
  **/
  public ActionDto getMarkForArchiving() {
    return markForArchiving;
  }

  public void setMarkForArchiving(ActionDto markForArchiving) {
    this.markForArchiving = markForArchiving;
  }

  public CandidateGlobalActionsDto unmarkFromArchiving(ActionDto unmarkFromArchiving) {
    this.unmarkFromArchiving = unmarkFromArchiving;
    return this;
  }

   /**
   * Get unmarkFromArchiving
   * @return unmarkFromArchiving
  **/
  public ActionDto getUnmarkFromArchiving() {
    return unmarkFromArchiving;
  }

  public void setUnmarkFromArchiving(ActionDto unmarkFromArchiving) {
    this.unmarkFromArchiving = unmarkFromArchiving;
  }

  public CandidateGlobalActionsDto fetchCandidateSummary(ActionDto fetchCandidateSummary) {
    this.fetchCandidateSummary = fetchCandidateSummary;
    return this;
  }

   /**
   * Get fetchCandidateSummary
   * @return fetchCandidateSummary
  **/
  public ActionDto getFetchCandidateSummary() {
    return fetchCandidateSummary;
  }

  public void setFetchCandidateSummary(ActionDto fetchCandidateSummary) {
    this.fetchCandidateSummary = fetchCandidateSummary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateGlobalActionsDto candidateGlobalActionsDto = (CandidateGlobalActionsDto) o;
    return Objects.equals(this.create, candidateGlobalActionsDto.create) &&
        Objects.equals(this.markForArchiving, candidateGlobalActionsDto.markForArchiving) &&
        Objects.equals(this.unmarkFromArchiving, candidateGlobalActionsDto.unmarkFromArchiving) &&
        Objects.equals(this.fetchCandidateSummary, candidateGlobalActionsDto.fetchCandidateSummary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(create, markForArchiving, unmarkFromArchiving, fetchCandidateSummary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateGlobalActionsDto {\n");
    
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    markForArchiving: ").append(toIndentedString(markForArchiving)).append("\n");
    sb.append("    unmarkFromArchiving: ").append(toIndentedString(unmarkFromArchiving)).append("\n");
    sb.append("    fetchCandidateSummary: ").append(toIndentedString(fetchCandidateSummary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
