/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.CandidatePoolActionsDto;

/**
 * CandidatePoolFullDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CandidatePoolFullDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("outOfMatching")
  private Boolean outOfMatching = false;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("creationDate")
  private Long creationDate = null;

  @JsonProperty("updateDate")
  private Long updateDate = null;

  @JsonProperty("defaultFolder")
  private Boolean defaultFolder = false;

  @JsonProperty("folderType")
  private String folderType = null;

  @JsonProperty("departmentId")
  private Long departmentId = null;

  @JsonProperty("creationUserId")
  private Long creationUserId = null;

  @JsonProperty("updateUserId")
  private Long updateUserId = null;

  @JsonProperty("actions")
  private CandidatePoolActionsDto actions = null;

  public CandidatePoolFullDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the Pool
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CandidatePoolFullDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CandidatePoolFullDto outOfMatching(Boolean outOfMatching) {
    this.outOfMatching = outOfMatching;
    return this;
  }

   /**
   * If set to Yes, then candidates assigned to such a pool will be excluded from Job Matching feature.
   * @return outOfMatching
  **/
  public Boolean isOutOfMatching() {
    return outOfMatching;
  }

  public void setOutOfMatching(Boolean outOfMatching) {
    this.outOfMatching = outOfMatching;
  }

  public CandidatePoolFullDto country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Name of the country which is assigned to the Pool
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CandidatePoolFullDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * unique ID of a Pool
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public CandidatePoolFullDto creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * date when the Pool was created
   * @return creationDate
  **/
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }

  public CandidatePoolFullDto updateDate(Long updateDate) {
    this.updateDate = updateDate;
    return this;
  }

   /**
   * date when the Pool has been updated
   * @return updateDate
  **/
  public Long getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Long updateDate) {
    this.updateDate = updateDate;
  }

  public CandidatePoolFullDto defaultFolder(Boolean defaultFolder) {
    this.defaultFolder = defaultFolder;
    return this;
  }

   /**
   * distinguishes between user&#x27;s private pool (value&#x3D;Yes) and Department Shared Pool (value&#x3D;No)
   * @return defaultFolder
  **/
  public Boolean isDefaultFolder() {
    return defaultFolder;
  }

  public void setDefaultFolder(Boolean defaultFolder) {
    this.defaultFolder = defaultFolder;
  }

  public CandidatePoolFullDto folderType(String folderType) {
    this.folderType = folderType;
    return this;
  }

   /**
   * Get folderType
   * @return folderType
  **/
  public String getFolderType() {
    return folderType;
  }

  public void setFolderType(String folderType) {
    this.folderType = folderType;
  }

  public CandidatePoolFullDto departmentId(Long departmentId) {
    this.departmentId = departmentId;
    return this;
  }

   /**
   * ID of the department to which the Pool is assigned
   * @return departmentId
  **/
  public Long getDepartmentId() {
    return departmentId;
  }

  public void setDepartmentId(Long departmentId) {
    this.departmentId = departmentId;
  }

  public CandidatePoolFullDto creationUserId(Long creationUserId) {
    this.creationUserId = creationUserId;
    return this;
  }

   /**
   * ID of the user who created the Pool
   * @return creationUserId
  **/
  public Long getCreationUserId() {
    return creationUserId;
  }

  public void setCreationUserId(Long creationUserId) {
    this.creationUserId = creationUserId;
  }

  public CandidatePoolFullDto updateUserId(Long updateUserId) {
    this.updateUserId = updateUserId;
    return this;
  }

   /**
   * ID of the most recent user who updated the Pool
   * @return updateUserId
  **/
  public Long getUpdateUserId() {
    return updateUserId;
  }

  public void setUpdateUserId(Long updateUserId) {
    this.updateUserId = updateUserId;
  }

  public CandidatePoolFullDto actions(CandidatePoolActionsDto actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  public CandidatePoolActionsDto getActions() {
    return actions;
  }

  public void setActions(CandidatePoolActionsDto actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidatePoolFullDto candidatePoolFullDto = (CandidatePoolFullDto) o;
    return Objects.equals(this.name, candidatePoolFullDto.name) &&
        Objects.equals(this.description, candidatePoolFullDto.description) &&
        Objects.equals(this.outOfMatching, candidatePoolFullDto.outOfMatching) &&
        Objects.equals(this.country, candidatePoolFullDto.country) &&
        Objects.equals(this.id, candidatePoolFullDto.id) &&
        Objects.equals(this.creationDate, candidatePoolFullDto.creationDate) &&
        Objects.equals(this.updateDate, candidatePoolFullDto.updateDate) &&
        Objects.equals(this.defaultFolder, candidatePoolFullDto.defaultFolder) &&
        Objects.equals(this.folderType, candidatePoolFullDto.folderType) &&
        Objects.equals(this.departmentId, candidatePoolFullDto.departmentId) &&
        Objects.equals(this.creationUserId, candidatePoolFullDto.creationUserId) &&
        Objects.equals(this.updateUserId, candidatePoolFullDto.updateUserId) &&
        Objects.equals(this.actions, candidatePoolFullDto.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, outOfMatching, country, id, creationDate, updateDate, defaultFolder, folderType, departmentId, creationUserId, updateUserId, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidatePoolFullDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    outOfMatching: ").append(toIndentedString(outOfMatching)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    defaultFolder: ").append(toIndentedString(defaultFolder)).append("\n");
    sb.append("    folderType: ").append(toIndentedString(folderType)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("    creationUserId: ").append(toIndentedString(creationUserId)).append("\n");
    sb.append("    updateUserId: ").append(toIndentedString(updateUserId)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
