/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CandidatePoolCreationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CandidatePoolCreationDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("outOfMatching")
  private Boolean outOfMatching = false;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("departmentId")
  private Long departmentId = null;

  public CandidatePoolCreationDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name of the Pool
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CandidatePoolCreationDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CandidatePoolCreationDto outOfMatching(Boolean outOfMatching) {
    this.outOfMatching = outOfMatching;
    return this;
  }

   /**
   * If set to Yes, then candidates assigned to such a pool will be excluded from Job Matching feature.
   * @return outOfMatching
  **/
  public Boolean isOutOfMatching() {
    return outOfMatching;
  }

  public void setOutOfMatching(Boolean outOfMatching) {
    this.outOfMatching = outOfMatching;
  }

  public CandidatePoolCreationDto country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Name of the country which is assigned to the Pool
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CandidatePoolCreationDto departmentId(Long departmentId) {
    this.departmentId = departmentId;
    return this;
  }

   /**
   * ID of the department to which the Pool is assigned
   * @return departmentId
  **/
  public Long getDepartmentId() {
    return departmentId;
  }

  public void setDepartmentId(Long departmentId) {
    this.departmentId = departmentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidatePoolCreationDto candidatePoolCreationDto = (CandidatePoolCreationDto) o;
    return Objects.equals(this.name, candidatePoolCreationDto.name) &&
        Objects.equals(this.description, candidatePoolCreationDto.description) &&
        Objects.equals(this.outOfMatching, candidatePoolCreationDto.outOfMatching) &&
        Objects.equals(this.country, candidatePoolCreationDto.country) &&
        Objects.equals(this.departmentId, candidatePoolCreationDto.departmentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, outOfMatching, country, departmentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidatePoolCreationDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    outOfMatching: ").append(toIndentedString(outOfMatching)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    departmentId: ").append(toIndentedString(departmentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
