/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CandidateDocumentDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CandidateDocumentDto {
  @JsonProperty("fileName")
  private String fileName = null;

  @JsonProperty("description")
  private String description = null;

  /**
   * Gets or Sets docType
   */
  public enum DocTypeEnum {
    RESUME("RESUME"),
    COVER_LETTER("COVER_LETTER"),
    MAIL("MAIL"),
    OFFER_LETTER("OFFER_LETTER"),
    OTHER("OTHER");

    private String value;

    DocTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DocTypeEnum fromValue(String input) {
      for (DocTypeEnum b : DocTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("docType")
  private DocTypeEnum docType = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("base64File")
  private String base64File = null;

  @JsonProperty("applicationId")
  private Long applicationId = null;

  public CandidateDocumentDto fileName(String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName
  **/
  public String getFileName() {
    return fileName;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public CandidateDocumentDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CandidateDocumentDto docType(DocTypeEnum docType) {
    this.docType = docType;
    return this;
  }

   /**
   * Get docType
   * @return docType
  **/
  public DocTypeEnum getDocType() {
    return docType;
  }

  public void setDocType(DocTypeEnum docType) {
    this.docType = docType;
  }

  public CandidateDocumentDto language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public CandidateDocumentDto base64File(String base64File) {
    this.base64File = base64File;
    return this;
  }

   /**
   * Get base64File
   * @return base64File
  **/
  public String getBase64File() {
    return base64File;
  }

  public void setBase64File(String base64File) {
    this.base64File = base64File;
  }

  public CandidateDocumentDto applicationId(Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Long applicationId) {
    this.applicationId = applicationId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CandidateDocumentDto candidateDocumentDto = (CandidateDocumentDto) o;
    return Objects.equals(this.fileName, candidateDocumentDto.fileName) &&
        Objects.equals(this.description, candidateDocumentDto.description) &&
        Objects.equals(this.docType, candidateDocumentDto.docType) &&
        Objects.equals(this.language, candidateDocumentDto.language) &&
        Objects.equals(this.base64File, candidateDocumentDto.base64File) &&
        Objects.equals(this.applicationId, candidateDocumentDto.applicationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileName, description, docType, language, base64File, applicationId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CandidateDocumentDto {\n");
    
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    docType: ").append(toIndentedString(docType)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    base64File: ").append(toIndentedString(base64File)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
