/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LovDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TimesheetApprovalStepDto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * CostCenterConfigDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CostCenterConfigDto {
  @JsonProperty("costCenter")
  private LovDto costCenter = null;

  @JsonProperty("steps")
  private List<TimesheetApprovalStepDto> steps = null;

  @JsonProperty("cost")
  private BigDecimal cost = null;

  public CostCenterConfigDto costCenter(LovDto costCenter) {
    this.costCenter = costCenter;
    return this;
  }

   /**
   * Get costCenter
   * @return costCenter
  **/
  public LovDto getCostCenter() {
    return costCenter;
  }

  public void setCostCenter(LovDto costCenter) {
    this.costCenter = costCenter;
  }

  public CostCenterConfigDto steps(List<TimesheetApprovalStepDto> steps) {
    this.steps = steps;
    return this;
  }

  public CostCenterConfigDto addStepsItem(TimesheetApprovalStepDto stepsItem) {
    if (this.steps == null) {
      this.steps = new ArrayList<>();
    }
    this.steps.add(stepsItem);
    return this;
  }

   /**
   * Get steps
   * @return steps
  **/
  public List<TimesheetApprovalStepDto> getSteps() {
    return steps;
  }

  public void setSteps(List<TimesheetApprovalStepDto> steps) {
    this.steps = steps;
  }

  public CostCenterConfigDto cost(BigDecimal cost) {
    this.cost = cost;
    return this;
  }

   /**
   * Get cost
   * @return cost
  **/
  public BigDecimal getCost() {
    return cost;
  }

  public void setCost(BigDecimal cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CostCenterConfigDto costCenterConfigDto = (CostCenterConfigDto) o;
    return Objects.equals(this.costCenter, costCenterConfigDto.costCenter) &&
        Objects.equals(this.steps, costCenterConfigDto.steps) &&
        Objects.equals(this.cost, costCenterConfigDto.cost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(costCenter, steps, cost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CostCenterConfigDto {\n");
    
    sb.append("    costCenter: ").append(toIndentedString(costCenter)).append("\n");
    sb.append("    steps: ").append(toIndentedString(steps)).append("\n");
    sb.append("    cost: ").append(toIndentedString(cost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
