/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.CostCenterConfigDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LovDto;

import java.util.ArrayList;
import java.util.List;
/**
 * CostCenterApprovalConfigDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class CostCenterApprovalConfigDto {
  @JsonProperty("costCenterType")
  private LovDto costCenterType = null;

  @JsonProperty("costCenterConfig")
  private List<CostCenterConfigDto> costCenterConfig = null;

  public CostCenterApprovalConfigDto costCenterType(LovDto costCenterType) {
    this.costCenterType = costCenterType;
    return this;
  }

   /**
   * Get costCenterType
   * @return costCenterType
  **/
  public LovDto getCostCenterType() {
    return costCenterType;
  }

  public void setCostCenterType(LovDto costCenterType) {
    this.costCenterType = costCenterType;
  }

  public CostCenterApprovalConfigDto costCenterConfig(List<CostCenterConfigDto> costCenterConfig) {
    this.costCenterConfig = costCenterConfig;
    return this;
  }

  public CostCenterApprovalConfigDto addCostCenterConfigItem(CostCenterConfigDto costCenterConfigItem) {
    if (this.costCenterConfig == null) {
      this.costCenterConfig = new ArrayList<>();
    }
    this.costCenterConfig.add(costCenterConfigItem);
    return this;
  }

   /**
   * Get costCenterConfig
   * @return costCenterConfig
  **/
  public List<CostCenterConfigDto> getCostCenterConfig() {
    return costCenterConfig;
  }

  public void setCostCenterConfig(List<CostCenterConfigDto> costCenterConfig) {
    this.costCenterConfig = costCenterConfig;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CostCenterApprovalConfigDto costCenterApprovalConfigDto = (CostCenterApprovalConfigDto) o;
    return Objects.equals(this.costCenterType, costCenterApprovalConfigDto.costCenterType) &&
        Objects.equals(this.costCenterConfig, costCenterApprovalConfigDto.costCenterConfig);
  }

  @Override
  public int hashCode() {
    return Objects.hash(costCenterType, costCenterConfig);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CostCenterApprovalConfigDto {\n");
    
    sb.append("    costCenterType: ").append(toIndentedString(costCenterType)).append("\n");
    sb.append("    costCenterConfig: ").append(toIndentedString(costCenterConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
