/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * DashboardAssignmentRequestDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class DashboardAssignmentRequestDto {
  @JsonProperty("genericDashboard")
  private Boolean genericDashboard = false;

  @JsonProperty("hiringManagerDashboard")
  private Boolean hiringManagerDashboard = false;

  @JsonProperty("recruiterDashboards")
  private Map<String, Boolean> recruiterDashboards = null;

  public DashboardAssignmentRequestDto genericDashboard(Boolean genericDashboard) {
    this.genericDashboard = genericDashboard;
    return this;
  }

   /**
   * Get genericDashboard
   * @return genericDashboard
  **/
  public Boolean isGenericDashboard() {
    return genericDashboard;
  }

  public void setGenericDashboard(Boolean genericDashboard) {
    this.genericDashboard = genericDashboard;
  }

  public DashboardAssignmentRequestDto hiringManagerDashboard(Boolean hiringManagerDashboard) {
    this.hiringManagerDashboard = hiringManagerDashboard;
    return this;
  }

   /**
   * Get hiringManagerDashboard
   * @return hiringManagerDashboard
  **/
  public Boolean isHiringManagerDashboard() {
    return hiringManagerDashboard;
  }

  public void setHiringManagerDashboard(Boolean hiringManagerDashboard) {
    this.hiringManagerDashboard = hiringManagerDashboard;
  }

  public DashboardAssignmentRequestDto recruiterDashboards(Map<String, Boolean> recruiterDashboards) {
    this.recruiterDashboards = recruiterDashboards;
    return this;
  }

  public DashboardAssignmentRequestDto putRecruiterDashboardsItem(String key, Boolean recruiterDashboardsItem) {
    if (this.recruiterDashboards == null) {
      this.recruiterDashboards = new HashMap<>();
    }
    this.recruiterDashboards.put(key, recruiterDashboardsItem);
    return this;
  }

   /**
   * Get recruiterDashboards
   * @return recruiterDashboards
  **/
  public Map<String, Boolean> getRecruiterDashboards() {
    return recruiterDashboards;
  }

  public void setRecruiterDashboards(Map<String, Boolean> recruiterDashboards) {
    this.recruiterDashboards = recruiterDashboards;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DashboardAssignmentRequestDto dashboardAssignmentRequestDto = (DashboardAssignmentRequestDto) o;
    return Objects.equals(this.genericDashboard, dashboardAssignmentRequestDto.genericDashboard) &&
        Objects.equals(this.hiringManagerDashboard, dashboardAssignmentRequestDto.hiringManagerDashboard) &&
        Objects.equals(this.recruiterDashboards, dashboardAssignmentRequestDto.recruiterDashboards);
  }

  @Override
  public int hashCode() {
    return Objects.hash(genericDashboard, hiringManagerDashboard, recruiterDashboards);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DashboardAssignmentRequestDto {\n");
    
    sb.append("    genericDashboard: ").append(toIndentedString(genericDashboard)).append("\n");
    sb.append("    hiringManagerDashboard: ").append(toIndentedString(hiringManagerDashboard)).append("\n");
    sb.append("    recruiterDashboards: ").append(toIndentedString(recruiterDashboards)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
