/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * DepartmentConfigDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class DepartmentConfigDto {
  @JsonProperty("interviewScheduleInJobContext")
  private Boolean interviewScheduleInJobContext = false;

  @JsonProperty("hideManageMyDataRemoveButton")
  private Boolean hideManageMyDataRemoveButton = false;

  @JsonProperty("contractServerMerge")
  private Boolean contractServerMerge = false;

  @JsonProperty("txtSystemNotification")
  private String txtSystemNotification = null;

  @JsonProperty("systemNotificationAuthorUsername")
  private String systemNotificationAuthorUsername = null;

  @JsonProperty("dataPrivacyDisplayOption")
  private String dataPrivacyDisplayOption = null;

  public DepartmentConfigDto interviewScheduleInJobContext(Boolean interviewScheduleInJobContext) {
    this.interviewScheduleInJobContext = interviewScheduleInJobContext;
    return this;
  }

   /**
   * Get interviewScheduleInJobContext
   * @return interviewScheduleInJobContext
  **/
  public Boolean isInterviewScheduleInJobContext() {
    return interviewScheduleInJobContext;
  }

  public void setInterviewScheduleInJobContext(Boolean interviewScheduleInJobContext) {
    this.interviewScheduleInJobContext = interviewScheduleInJobContext;
  }

  public DepartmentConfigDto hideManageMyDataRemoveButton(Boolean hideManageMyDataRemoveButton) {
    this.hideManageMyDataRemoveButton = hideManageMyDataRemoveButton;
    return this;
  }

   /**
   * Get hideManageMyDataRemoveButton
   * @return hideManageMyDataRemoveButton
  **/
  public Boolean isHideManageMyDataRemoveButton() {
    return hideManageMyDataRemoveButton;
  }

  public void setHideManageMyDataRemoveButton(Boolean hideManageMyDataRemoveButton) {
    this.hideManageMyDataRemoveButton = hideManageMyDataRemoveButton;
  }

  public DepartmentConfigDto contractServerMerge(Boolean contractServerMerge) {
    this.contractServerMerge = contractServerMerge;
    return this;
  }

   /**
   * Get contractServerMerge
   * @return contractServerMerge
  **/
  public Boolean isContractServerMerge() {
    return contractServerMerge;
  }

  public void setContractServerMerge(Boolean contractServerMerge) {
    this.contractServerMerge = contractServerMerge;
  }

  public DepartmentConfigDto txtSystemNotification(String txtSystemNotification) {
    this.txtSystemNotification = txtSystemNotification;
    return this;
  }

   /**
   * Get txtSystemNotification
   * @return txtSystemNotification
  **/
  public String getTxtSystemNotification() {
    return txtSystemNotification;
  }

  public void setTxtSystemNotification(String txtSystemNotification) {
    this.txtSystemNotification = txtSystemNotification;
  }

  public DepartmentConfigDto systemNotificationAuthorUsername(String systemNotificationAuthorUsername) {
    this.systemNotificationAuthorUsername = systemNotificationAuthorUsername;
    return this;
  }

   /**
   * Get systemNotificationAuthorUsername
   * @return systemNotificationAuthorUsername
  **/
  public String getSystemNotificationAuthorUsername() {
    return systemNotificationAuthorUsername;
  }

  public void setSystemNotificationAuthorUsername(String systemNotificationAuthorUsername) {
    this.systemNotificationAuthorUsername = systemNotificationAuthorUsername;
  }

  public DepartmentConfigDto dataPrivacyDisplayOption(String dataPrivacyDisplayOption) {
    this.dataPrivacyDisplayOption = dataPrivacyDisplayOption;
    return this;
  }

   /**
   * Get dataPrivacyDisplayOption
   * @return dataPrivacyDisplayOption
  **/
  public String getDataPrivacyDisplayOption() {
    return dataPrivacyDisplayOption;
  }

  public void setDataPrivacyDisplayOption(String dataPrivacyDisplayOption) {
    this.dataPrivacyDisplayOption = dataPrivacyDisplayOption;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentConfigDto departmentConfigDto = (DepartmentConfigDto) o;
    return Objects.equals(this.interviewScheduleInJobContext, departmentConfigDto.interviewScheduleInJobContext) &&
        Objects.equals(this.hideManageMyDataRemoveButton, departmentConfigDto.hideManageMyDataRemoveButton) &&
        Objects.equals(this.contractServerMerge, departmentConfigDto.contractServerMerge) &&
        Objects.equals(this.txtSystemNotification, departmentConfigDto.txtSystemNotification) &&
        Objects.equals(this.systemNotificationAuthorUsername, departmentConfigDto.systemNotificationAuthorUsername) &&
        Objects.equals(this.dataPrivacyDisplayOption, departmentConfigDto.dataPrivacyDisplayOption);
  }

  @Override
  public int hashCode() {
    return Objects.hash(interviewScheduleInJobContext, hideManageMyDataRemoveButton, contractServerMerge, txtSystemNotification, systemNotificationAuthorUsername, dataPrivacyDisplayOption);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentConfigDto {\n");
    
    sb.append("    interviewScheduleInJobContext: ").append(toIndentedString(interviewScheduleInJobContext)).append("\n");
    sb.append("    hideManageMyDataRemoveButton: ").append(toIndentedString(hideManageMyDataRemoveButton)).append("\n");
    sb.append("    contractServerMerge: ").append(toIndentedString(contractServerMerge)).append("\n");
    sb.append("    txtSystemNotification: ").append(toIndentedString(txtSystemNotification)).append("\n");
    sb.append("    systemNotificationAuthorUsername: ").append(toIndentedString(systemNotificationAuthorUsername)).append("\n");
    sb.append("    dataPrivacyDisplayOption: ").append(toIndentedString(dataPrivacyDisplayOption)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
