/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentActionsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentConfigDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ThemeDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TranslationsDto;

import java.util.ArrayList;
import java.util.List;
/**
 * DepartmentFullDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class DepartmentFullDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("code")
  private String code = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("documentSecurityRule")
  private Integer documentSecurityRule = null;

  @JsonProperty("dataPrivacyStatement")
  private String dataPrivacyStatement = null;

  @JsonProperty("dataPrivacyStatementForHires")
  private String dataPrivacyStatementForHires = null;

  @JsonProperty("invitationValidity")
  private Long invitationValidity = null;

  @JsonProperty("currencyCost")
  private String currencyCost = null;

  @JsonProperty("hideDateOfBirth")
  private Boolean hideDateOfBirth = false;

  @JsonProperty("searchByAgeEnabled")
  private Boolean searchByAgeEnabled = false;

  @JsonProperty("parentId")
  private Long parentId = null;

  @JsonProperty("translations")
  private TranslationsDto translations = null;

  @JsonProperty("keyNameId")
  private Long keyNameId = null;

  @JsonProperty("ofccpMaxCandidates")
  private Long ofccpMaxCandidates = null;

  @JsonProperty("enforceInviteToExpressInterest")
  private Boolean enforceInviteToExpressInterest = false;

  @JsonProperty("activateSearchRecording")
  private Boolean activateSearchRecording = false;

  @JsonProperty("ofccpLinkToJobShowJobs")
  private Boolean ofccpLinkToJobShowJobs = false;

  @JsonProperty("enforceSalaryRangeCheck")
  private Boolean enforceSalaryRangeCheck = false;

  @JsonProperty("mobileAccess")
  private Boolean mobileAccess = false;

  @JsonProperty("themes")
  private List<ThemeDto> themes = null;

  @JsonProperty("emailSignatureID")
  private Long emailSignatureID = null;

  @JsonProperty("letterSignatureID")
  private Long letterSignatureID = null;

  @JsonProperty("awdOwner")
  private String awdOwner = null;

  @JsonProperty("awdReminderID")
  private Long awdReminderID = null;

  @JsonProperty("awdReminderPeriod")
  private Long awdReminderPeriod = null;

  @JsonProperty("awdQualifyExpiresReminderID")
  private Long awdQualifyExpiresReminderID = null;

  @JsonProperty("calendarEventWsIntegrationURL")
  private String calendarEventWsIntegrationURL = null;

  @JsonProperty("useAccountCalendarEventWsIntegrationURL")
  private Boolean useAccountCalendarEventWsIntegrationURL = false;

  @JsonProperty("enforceSalaryRangeCheckApproval")
  private Boolean enforceSalaryRangeCheckApproval = false;

  @JsonProperty("ratingScaleId")
  private Long ratingScaleId = null;

  @JsonProperty("impJobDescAvailable")
  private Boolean impJobDescAvailable = false;

  @JsonProperty("encryptApplicants")
  private Boolean encryptApplicants = false;

  @JsonProperty("rejectionReasonRequired")
  private Boolean rejectionReasonRequired = false;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("location")
  private String location = null;

  @JsonProperty("mobileMDMAccess")
  private Boolean mobileMDMAccess = false;

  @JsonProperty("departmentConfig")
  private DepartmentConfigDto departmentConfig = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("level")
  private Integer level = null;

  @JsonProperty("active")
  private Boolean active = false;

  @JsonProperty("actions")
  private DepartmentActionsDto actions = null;

  public DepartmentFullDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DepartmentFullDto code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public DepartmentFullDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public DepartmentFullDto documentSecurityRule(Integer documentSecurityRule) {
    this.documentSecurityRule = documentSecurityRule;
    return this;
  }

   /**
   * Get documentSecurityRule
   * @return documentSecurityRule
  **/
  public Integer getDocumentSecurityRule() {
    return documentSecurityRule;
  }

  public void setDocumentSecurityRule(Integer documentSecurityRule) {
    this.documentSecurityRule = documentSecurityRule;
  }

  public DepartmentFullDto dataPrivacyStatement(String dataPrivacyStatement) {
    this.dataPrivacyStatement = dataPrivacyStatement;
    return this;
  }

   /**
   * Get dataPrivacyStatement
   * @return dataPrivacyStatement
  **/
  public String getDataPrivacyStatement() {
    return dataPrivacyStatement;
  }

  public void setDataPrivacyStatement(String dataPrivacyStatement) {
    this.dataPrivacyStatement = dataPrivacyStatement;
  }

  public DepartmentFullDto dataPrivacyStatementForHires(String dataPrivacyStatementForHires) {
    this.dataPrivacyStatementForHires = dataPrivacyStatementForHires;
    return this;
  }

   /**
   * Get dataPrivacyStatementForHires
   * @return dataPrivacyStatementForHires
  **/
  public String getDataPrivacyStatementForHires() {
    return dataPrivacyStatementForHires;
  }

  public void setDataPrivacyStatementForHires(String dataPrivacyStatementForHires) {
    this.dataPrivacyStatementForHires = dataPrivacyStatementForHires;
  }

  public DepartmentFullDto invitationValidity(Long invitationValidity) {
    this.invitationValidity = invitationValidity;
    return this;
  }

   /**
   * Get invitationValidity
   * @return invitationValidity
  **/
  public Long getInvitationValidity() {
    return invitationValidity;
  }

  public void setInvitationValidity(Long invitationValidity) {
    this.invitationValidity = invitationValidity;
  }

  public DepartmentFullDto currencyCost(String currencyCost) {
    this.currencyCost = currencyCost;
    return this;
  }

   /**
   * Get currencyCost
   * @return currencyCost
  **/
  public String getCurrencyCost() {
    return currencyCost;
  }

  public void setCurrencyCost(String currencyCost) {
    this.currencyCost = currencyCost;
  }

  public DepartmentFullDto hideDateOfBirth(Boolean hideDateOfBirth) {
    this.hideDateOfBirth = hideDateOfBirth;
    return this;
  }

   /**
   * Get hideDateOfBirth
   * @return hideDateOfBirth
  **/
  public Boolean isHideDateOfBirth() {
    return hideDateOfBirth;
  }

  public void setHideDateOfBirth(Boolean hideDateOfBirth) {
    this.hideDateOfBirth = hideDateOfBirth;
  }

  public DepartmentFullDto searchByAgeEnabled(Boolean searchByAgeEnabled) {
    this.searchByAgeEnabled = searchByAgeEnabled;
    return this;
  }

   /**
   * Get searchByAgeEnabled
   * @return searchByAgeEnabled
  **/
  public Boolean isSearchByAgeEnabled() {
    return searchByAgeEnabled;
  }

  public void setSearchByAgeEnabled(Boolean searchByAgeEnabled) {
    this.searchByAgeEnabled = searchByAgeEnabled;
  }

  public DepartmentFullDto parentId(Long parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  public Long getParentId() {
    return parentId;
  }

  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  public DepartmentFullDto translations(TranslationsDto translations) {
    this.translations = translations;
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  public TranslationsDto getTranslations() {
    return translations;
  }

  public void setTranslations(TranslationsDto translations) {
    this.translations = translations;
  }

  public DepartmentFullDto keyNameId(Long keyNameId) {
    this.keyNameId = keyNameId;
    return this;
  }

   /**
   * Get keyNameId
   * @return keyNameId
  **/
  public Long getKeyNameId() {
    return keyNameId;
  }

  public void setKeyNameId(Long keyNameId) {
    this.keyNameId = keyNameId;
  }

  public DepartmentFullDto ofccpMaxCandidates(Long ofccpMaxCandidates) {
    this.ofccpMaxCandidates = ofccpMaxCandidates;
    return this;
  }

   /**
   * Get ofccpMaxCandidates
   * @return ofccpMaxCandidates
  **/
  public Long getOfccpMaxCandidates() {
    return ofccpMaxCandidates;
  }

  public void setOfccpMaxCandidates(Long ofccpMaxCandidates) {
    this.ofccpMaxCandidates = ofccpMaxCandidates;
  }

  public DepartmentFullDto enforceInviteToExpressInterest(Boolean enforceInviteToExpressInterest) {
    this.enforceInviteToExpressInterest = enforceInviteToExpressInterest;
    return this;
  }

   /**
   * Get enforceInviteToExpressInterest
   * @return enforceInviteToExpressInterest
  **/
  public Boolean isEnforceInviteToExpressInterest() {
    return enforceInviteToExpressInterest;
  }

  public void setEnforceInviteToExpressInterest(Boolean enforceInviteToExpressInterest) {
    this.enforceInviteToExpressInterest = enforceInviteToExpressInterest;
  }

  public DepartmentFullDto activateSearchRecording(Boolean activateSearchRecording) {
    this.activateSearchRecording = activateSearchRecording;
    return this;
  }

   /**
   * Get activateSearchRecording
   * @return activateSearchRecording
  **/
  public Boolean isActivateSearchRecording() {
    return activateSearchRecording;
  }

  public void setActivateSearchRecording(Boolean activateSearchRecording) {
    this.activateSearchRecording = activateSearchRecording;
  }

  public DepartmentFullDto ofccpLinkToJobShowJobs(Boolean ofccpLinkToJobShowJobs) {
    this.ofccpLinkToJobShowJobs = ofccpLinkToJobShowJobs;
    return this;
  }

   /**
   * Get ofccpLinkToJobShowJobs
   * @return ofccpLinkToJobShowJobs
  **/
  public Boolean isOfccpLinkToJobShowJobs() {
    return ofccpLinkToJobShowJobs;
  }

  public void setOfccpLinkToJobShowJobs(Boolean ofccpLinkToJobShowJobs) {
    this.ofccpLinkToJobShowJobs = ofccpLinkToJobShowJobs;
  }

  public DepartmentFullDto enforceSalaryRangeCheck(Boolean enforceSalaryRangeCheck) {
    this.enforceSalaryRangeCheck = enforceSalaryRangeCheck;
    return this;
  }

   /**
   * Get enforceSalaryRangeCheck
   * @return enforceSalaryRangeCheck
  **/
  public Boolean isEnforceSalaryRangeCheck() {
    return enforceSalaryRangeCheck;
  }

  public void setEnforceSalaryRangeCheck(Boolean enforceSalaryRangeCheck) {
    this.enforceSalaryRangeCheck = enforceSalaryRangeCheck;
  }

  public DepartmentFullDto mobileAccess(Boolean mobileAccess) {
    this.mobileAccess = mobileAccess;
    return this;
  }

   /**
   * Get mobileAccess
   * @return mobileAccess
  **/
  public Boolean isMobileAccess() {
    return mobileAccess;
  }

  public void setMobileAccess(Boolean mobileAccess) {
    this.mobileAccess = mobileAccess;
  }

  public DepartmentFullDto themes(List<ThemeDto> themes) {
    this.themes = themes;
    return this;
  }

  public DepartmentFullDto addThemesItem(ThemeDto themesItem) {
    if (this.themes == null) {
      this.themes = new ArrayList<>();
    }
    this.themes.add(themesItem);
    return this;
  }

   /**
   * Get themes
   * @return themes
  **/
  public List<ThemeDto> getThemes() {
    return themes;
  }

  public void setThemes(List<ThemeDto> themes) {
    this.themes = themes;
  }

  public DepartmentFullDto emailSignatureID(Long emailSignatureID) {
    this.emailSignatureID = emailSignatureID;
    return this;
  }

   /**
   * Get emailSignatureID
   * @return emailSignatureID
  **/
  public Long getEmailSignatureID() {
    return emailSignatureID;
  }

  public void setEmailSignatureID(Long emailSignatureID) {
    this.emailSignatureID = emailSignatureID;
  }

  public DepartmentFullDto letterSignatureID(Long letterSignatureID) {
    this.letterSignatureID = letterSignatureID;
    return this;
  }

   /**
   * Get letterSignatureID
   * @return letterSignatureID
  **/
  public Long getLetterSignatureID() {
    return letterSignatureID;
  }

  public void setLetterSignatureID(Long letterSignatureID) {
    this.letterSignatureID = letterSignatureID;
  }

  public DepartmentFullDto awdOwner(String awdOwner) {
    this.awdOwner = awdOwner;
    return this;
  }

   /**
   * Get awdOwner
   * @return awdOwner
  **/
  public String getAwdOwner() {
    return awdOwner;
  }

  public void setAwdOwner(String awdOwner) {
    this.awdOwner = awdOwner;
  }

  public DepartmentFullDto awdReminderID(Long awdReminderID) {
    this.awdReminderID = awdReminderID;
    return this;
  }

   /**
   * Get awdReminderID
   * @return awdReminderID
  **/
  public Long getAwdReminderID() {
    return awdReminderID;
  }

  public void setAwdReminderID(Long awdReminderID) {
    this.awdReminderID = awdReminderID;
  }

  public DepartmentFullDto awdReminderPeriod(Long awdReminderPeriod) {
    this.awdReminderPeriod = awdReminderPeriod;
    return this;
  }

   /**
   * Get awdReminderPeriod
   * @return awdReminderPeriod
  **/
  public Long getAwdReminderPeriod() {
    return awdReminderPeriod;
  }

  public void setAwdReminderPeriod(Long awdReminderPeriod) {
    this.awdReminderPeriod = awdReminderPeriod;
  }

  public DepartmentFullDto awdQualifyExpiresReminderID(Long awdQualifyExpiresReminderID) {
    this.awdQualifyExpiresReminderID = awdQualifyExpiresReminderID;
    return this;
  }

   /**
   * Get awdQualifyExpiresReminderID
   * @return awdQualifyExpiresReminderID
  **/
  public Long getAwdQualifyExpiresReminderID() {
    return awdQualifyExpiresReminderID;
  }

  public void setAwdQualifyExpiresReminderID(Long awdQualifyExpiresReminderID) {
    this.awdQualifyExpiresReminderID = awdQualifyExpiresReminderID;
  }

  public DepartmentFullDto calendarEventWsIntegrationURL(String calendarEventWsIntegrationURL) {
    this.calendarEventWsIntegrationURL = calendarEventWsIntegrationURL;
    return this;
  }

   /**
   * Get calendarEventWsIntegrationURL
   * @return calendarEventWsIntegrationURL
  **/
  public String getCalendarEventWsIntegrationURL() {
    return calendarEventWsIntegrationURL;
  }

  public void setCalendarEventWsIntegrationURL(String calendarEventWsIntegrationURL) {
    this.calendarEventWsIntegrationURL = calendarEventWsIntegrationURL;
  }

  public DepartmentFullDto useAccountCalendarEventWsIntegrationURL(Boolean useAccountCalendarEventWsIntegrationURL) {
    this.useAccountCalendarEventWsIntegrationURL = useAccountCalendarEventWsIntegrationURL;
    return this;
  }

   /**
   * Get useAccountCalendarEventWsIntegrationURL
   * @return useAccountCalendarEventWsIntegrationURL
  **/
  public Boolean isUseAccountCalendarEventWsIntegrationURL() {
    return useAccountCalendarEventWsIntegrationURL;
  }

  public void setUseAccountCalendarEventWsIntegrationURL(Boolean useAccountCalendarEventWsIntegrationURL) {
    this.useAccountCalendarEventWsIntegrationURL = useAccountCalendarEventWsIntegrationURL;
  }

  public DepartmentFullDto enforceSalaryRangeCheckApproval(Boolean enforceSalaryRangeCheckApproval) {
    this.enforceSalaryRangeCheckApproval = enforceSalaryRangeCheckApproval;
    return this;
  }

   /**
   * Get enforceSalaryRangeCheckApproval
   * @return enforceSalaryRangeCheckApproval
  **/
  public Boolean isEnforceSalaryRangeCheckApproval() {
    return enforceSalaryRangeCheckApproval;
  }

  public void setEnforceSalaryRangeCheckApproval(Boolean enforceSalaryRangeCheckApproval) {
    this.enforceSalaryRangeCheckApproval = enforceSalaryRangeCheckApproval;
  }

  public DepartmentFullDto ratingScaleId(Long ratingScaleId) {
    this.ratingScaleId = ratingScaleId;
    return this;
  }

   /**
   * Get ratingScaleId
   * @return ratingScaleId
  **/
  public Long getRatingScaleId() {
    return ratingScaleId;
  }

  public void setRatingScaleId(Long ratingScaleId) {
    this.ratingScaleId = ratingScaleId;
  }

  public DepartmentFullDto impJobDescAvailable(Boolean impJobDescAvailable) {
    this.impJobDescAvailable = impJobDescAvailable;
    return this;
  }

   /**
   * Get impJobDescAvailable
   * @return impJobDescAvailable
  **/
  public Boolean isImpJobDescAvailable() {
    return impJobDescAvailable;
  }

  public void setImpJobDescAvailable(Boolean impJobDescAvailable) {
    this.impJobDescAvailable = impJobDescAvailable;
  }

  public DepartmentFullDto encryptApplicants(Boolean encryptApplicants) {
    this.encryptApplicants = encryptApplicants;
    return this;
  }

   /**
   * Get encryptApplicants
   * @return encryptApplicants
  **/
  public Boolean isEncryptApplicants() {
    return encryptApplicants;
  }

  public void setEncryptApplicants(Boolean encryptApplicants) {
    this.encryptApplicants = encryptApplicants;
  }

  public DepartmentFullDto rejectionReasonRequired(Boolean rejectionReasonRequired) {
    this.rejectionReasonRequired = rejectionReasonRequired;
    return this;
  }

   /**
   * Get rejectionReasonRequired
   * @return rejectionReasonRequired
  **/
  public Boolean isRejectionReasonRequired() {
    return rejectionReasonRequired;
  }

  public void setRejectionReasonRequired(Boolean rejectionReasonRequired) {
    this.rejectionReasonRequired = rejectionReasonRequired;
  }

  public DepartmentFullDto country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public DepartmentFullDto location(String location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public String getLocation() {
    return location;
  }

  public void setLocation(String location) {
    this.location = location;
  }

  public DepartmentFullDto mobileMDMAccess(Boolean mobileMDMAccess) {
    this.mobileMDMAccess = mobileMDMAccess;
    return this;
  }

   /**
   * Get mobileMDMAccess
   * @return mobileMDMAccess
  **/
  public Boolean isMobileMDMAccess() {
    return mobileMDMAccess;
  }

  public void setMobileMDMAccess(Boolean mobileMDMAccess) {
    this.mobileMDMAccess = mobileMDMAccess;
  }

  public DepartmentFullDto departmentConfig(DepartmentConfigDto departmentConfig) {
    this.departmentConfig = departmentConfig;
    return this;
  }

   /**
   * Get departmentConfig
   * @return departmentConfig
  **/
  public DepartmentConfigDto getDepartmentConfig() {
    return departmentConfig;
  }

  public void setDepartmentConfig(DepartmentConfigDto departmentConfig) {
    this.departmentConfig = departmentConfig;
  }

  public DepartmentFullDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public DepartmentFullDto level(Integer level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  public Integer getLevel() {
    return level;
  }

  public void setLevel(Integer level) {
    this.level = level;
  }

  public DepartmentFullDto active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public DepartmentFullDto actions(DepartmentActionsDto actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  public DepartmentActionsDto getActions() {
    return actions;
  }

  public void setActions(DepartmentActionsDto actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DepartmentFullDto departmentFullDto = (DepartmentFullDto) o;
    return Objects.equals(this.name, departmentFullDto.name) &&
        Objects.equals(this.code, departmentFullDto.code) &&
        Objects.equals(this.description, departmentFullDto.description) &&
        Objects.equals(this.documentSecurityRule, departmentFullDto.documentSecurityRule) &&
        Objects.equals(this.dataPrivacyStatement, departmentFullDto.dataPrivacyStatement) &&
        Objects.equals(this.dataPrivacyStatementForHires, departmentFullDto.dataPrivacyStatementForHires) &&
        Objects.equals(this.invitationValidity, departmentFullDto.invitationValidity) &&
        Objects.equals(this.currencyCost, departmentFullDto.currencyCost) &&
        Objects.equals(this.hideDateOfBirth, departmentFullDto.hideDateOfBirth) &&
        Objects.equals(this.searchByAgeEnabled, departmentFullDto.searchByAgeEnabled) &&
        Objects.equals(this.parentId, departmentFullDto.parentId) &&
        Objects.equals(this.translations, departmentFullDto.translations) &&
        Objects.equals(this.keyNameId, departmentFullDto.keyNameId) &&
        Objects.equals(this.ofccpMaxCandidates, departmentFullDto.ofccpMaxCandidates) &&
        Objects.equals(this.enforceInviteToExpressInterest, departmentFullDto.enforceInviteToExpressInterest) &&
        Objects.equals(this.activateSearchRecording, departmentFullDto.activateSearchRecording) &&
        Objects.equals(this.ofccpLinkToJobShowJobs, departmentFullDto.ofccpLinkToJobShowJobs) &&
        Objects.equals(this.enforceSalaryRangeCheck, departmentFullDto.enforceSalaryRangeCheck) &&
        Objects.equals(this.mobileAccess, departmentFullDto.mobileAccess) &&
        Objects.equals(this.themes, departmentFullDto.themes) &&
        Objects.equals(this.emailSignatureID, departmentFullDto.emailSignatureID) &&
        Objects.equals(this.letterSignatureID, departmentFullDto.letterSignatureID) &&
        Objects.equals(this.awdOwner, departmentFullDto.awdOwner) &&
        Objects.equals(this.awdReminderID, departmentFullDto.awdReminderID) &&
        Objects.equals(this.awdReminderPeriod, departmentFullDto.awdReminderPeriod) &&
        Objects.equals(this.awdQualifyExpiresReminderID, departmentFullDto.awdQualifyExpiresReminderID) &&
        Objects.equals(this.calendarEventWsIntegrationURL, departmentFullDto.calendarEventWsIntegrationURL) &&
        Objects.equals(this.useAccountCalendarEventWsIntegrationURL, departmentFullDto.useAccountCalendarEventWsIntegrationURL) &&
        Objects.equals(this.enforceSalaryRangeCheckApproval, departmentFullDto.enforceSalaryRangeCheckApproval) &&
        Objects.equals(this.ratingScaleId, departmentFullDto.ratingScaleId) &&
        Objects.equals(this.impJobDescAvailable, departmentFullDto.impJobDescAvailable) &&
        Objects.equals(this.encryptApplicants, departmentFullDto.encryptApplicants) &&
        Objects.equals(this.rejectionReasonRequired, departmentFullDto.rejectionReasonRequired) &&
        Objects.equals(this.country, departmentFullDto.country) &&
        Objects.equals(this.location, departmentFullDto.location) &&
        Objects.equals(this.mobileMDMAccess, departmentFullDto.mobileMDMAccess) &&
        Objects.equals(this.departmentConfig, departmentFullDto.departmentConfig) &&
        Objects.equals(this.id, departmentFullDto.id) &&
        Objects.equals(this.level, departmentFullDto.level) &&
        Objects.equals(this.active, departmentFullDto.active) &&
        Objects.equals(this.actions, departmentFullDto.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, code, description, documentSecurityRule, dataPrivacyStatement, dataPrivacyStatementForHires, invitationValidity, currencyCost, hideDateOfBirth, searchByAgeEnabled, parentId, translations, keyNameId, ofccpMaxCandidates, enforceInviteToExpressInterest, activateSearchRecording, ofccpLinkToJobShowJobs, enforceSalaryRangeCheck, mobileAccess, themes, emailSignatureID, letterSignatureID, awdOwner, awdReminderID, awdReminderPeriod, awdQualifyExpiresReminderID, calendarEventWsIntegrationURL, useAccountCalendarEventWsIntegrationURL, enforceSalaryRangeCheckApproval, ratingScaleId, impJobDescAvailable, encryptApplicants, rejectionReasonRequired, country, location, mobileMDMAccess, departmentConfig, id, level, active, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DepartmentFullDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentSecurityRule: ").append(toIndentedString(documentSecurityRule)).append("\n");
    sb.append("    dataPrivacyStatement: ").append(toIndentedString(dataPrivacyStatement)).append("\n");
    sb.append("    dataPrivacyStatementForHires: ").append(toIndentedString(dataPrivacyStatementForHires)).append("\n");
    sb.append("    invitationValidity: ").append(toIndentedString(invitationValidity)).append("\n");
    sb.append("    currencyCost: ").append(toIndentedString(currencyCost)).append("\n");
    sb.append("    hideDateOfBirth: ").append(toIndentedString(hideDateOfBirth)).append("\n");
    sb.append("    searchByAgeEnabled: ").append(toIndentedString(searchByAgeEnabled)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    keyNameId: ").append(toIndentedString(keyNameId)).append("\n");
    sb.append("    ofccpMaxCandidates: ").append(toIndentedString(ofccpMaxCandidates)).append("\n");
    sb.append("    enforceInviteToExpressInterest: ").append(toIndentedString(enforceInviteToExpressInterest)).append("\n");
    sb.append("    activateSearchRecording: ").append(toIndentedString(activateSearchRecording)).append("\n");
    sb.append("    ofccpLinkToJobShowJobs: ").append(toIndentedString(ofccpLinkToJobShowJobs)).append("\n");
    sb.append("    enforceSalaryRangeCheck: ").append(toIndentedString(enforceSalaryRangeCheck)).append("\n");
    sb.append("    mobileAccess: ").append(toIndentedString(mobileAccess)).append("\n");
    sb.append("    themes: ").append(toIndentedString(themes)).append("\n");
    sb.append("    emailSignatureID: ").append(toIndentedString(emailSignatureID)).append("\n");
    sb.append("    letterSignatureID: ").append(toIndentedString(letterSignatureID)).append("\n");
    sb.append("    awdOwner: ").append(toIndentedString(awdOwner)).append("\n");
    sb.append("    awdReminderID: ").append(toIndentedString(awdReminderID)).append("\n");
    sb.append("    awdReminderPeriod: ").append(toIndentedString(awdReminderPeriod)).append("\n");
    sb.append("    awdQualifyExpiresReminderID: ").append(toIndentedString(awdQualifyExpiresReminderID)).append("\n");
    sb.append("    calendarEventWsIntegrationURL: ").append(toIndentedString(calendarEventWsIntegrationURL)).append("\n");
    sb.append("    useAccountCalendarEventWsIntegrationURL: ").append(toIndentedString(useAccountCalendarEventWsIntegrationURL)).append("\n");
    sb.append("    enforceSalaryRangeCheckApproval: ").append(toIndentedString(enforceSalaryRangeCheckApproval)).append("\n");
    sb.append("    ratingScaleId: ").append(toIndentedString(ratingScaleId)).append("\n");
    sb.append("    impJobDescAvailable: ").append(toIndentedString(impJobDescAvailable)).append("\n");
    sb.append("    encryptApplicants: ").append(toIndentedString(encryptApplicants)).append("\n");
    sb.append("    rejectionReasonRequired: ").append(toIndentedString(rejectionReasonRequired)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    mobileMDMAccess: ").append(toIndentedString(mobileMDMAccess)).append("\n");
    sb.append("    departmentConfig: ").append(toIndentedString(departmentConfig)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
