/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicFreeFormFieldDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.BasicLovDto;

import java.util.ArrayList;
import java.util.List;
/**
 * EditUserDataDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class EditUserDataDto {
  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("lovs")
  private List<BasicLovDto> lovs = null;

  @JsonProperty("fffs")
  private List<BasicFreeFormFieldDto> fffs = null;

  public EditUserDataDto userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public EditUserDataDto lovs(List<BasicLovDto> lovs) {
    this.lovs = lovs;
    return this;
  }

  public EditUserDataDto addLovsItem(BasicLovDto lovsItem) {
    if (this.lovs == null) {
      this.lovs = new ArrayList<>();
    }
    this.lovs.add(lovsItem);
    return this;
  }

   /**
   * Get lovs
   * @return lovs
  **/
  public List<BasicLovDto> getLovs() {
    return lovs;
  }

  public void setLovs(List<BasicLovDto> lovs) {
    this.lovs = lovs;
  }

  public EditUserDataDto fffs(List<BasicFreeFormFieldDto> fffs) {
    this.fffs = fffs;
    return this;
  }

  public EditUserDataDto addFffsItem(BasicFreeFormFieldDto fffsItem) {
    if (this.fffs == null) {
      this.fffs = new ArrayList<>();
    }
    this.fffs.add(fffsItem);
    return this;
  }

   /**
   * Get fffs
   * @return fffs
  **/
  public List<BasicFreeFormFieldDto> getFffs() {
    return fffs;
  }

  public void setFffs(List<BasicFreeFormFieldDto> fffs) {
    this.fffs = fffs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EditUserDataDto editUserDataDto = (EditUserDataDto) o;
    return Objects.equals(this.userId, editUserDataDto.userId) &&
        Objects.equals(this.lovs, editUserDataDto.lovs) &&
        Objects.equals(this.fffs, editUserDataDto.fffs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, lovs, fffs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EditUserDataDto {\n");
    
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    lovs: ").append(toIndentedString(lovs)).append("\n");
    sb.append("    fffs: ").append(toIndentedString(fffs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
