/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TlkQueueDto;

/**
 * EventServiceConfKeyDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class EventServiceConfKeyDto {
  @JsonProperty("queue")
  private TlkQueueDto queue = null;

  /**
   * Gets or Sets eventType
   */
  public enum EventTypeEnum {
    CANDIDATE_CREATED_EVENT("CANDIDATE_CREATED_EVENT"),
    CANDIDATE_CHANGED_EVENT("CANDIDATE_CHANGED_EVENT"),
    CANDIDATE_DPS_ABOUT_TO_EXPIRE("CANDIDATE_DPS_ABOUT_TO_EXPIRE"),
    APPLICATION_CREATED_EVENT("APPLICATION_CREATED_EVENT"),
    APPLICATION_STATUS_CHANGED_EVENT("APPLICATION_STATUS_CHANGED_EVENT"),
    APPLICATION_STEP_DECISION_EVENT("APPLICATION_STEP_DECISION_EVENT"),
    JOB_APPROVED_EVENT("JOB_APPROVED_EVENT"),
    JOB_STATUS_CHANGED_EVENT("JOB_STATUS_CHANGED_EVENT"),
    JOB_CREATED_EVENT("JOB_CREATED_EVENT"),
    NEW_VERSION_OF_CONTRACT_OR_EXTENSION_CREATED_EVENT("NEW_VERSION_OF_CONTRACT_OR_EXTENSION_CREATED_EVENT"),
    VERSION_OF_CONTRACT_OR_EXTENSION_APPROVED("VERSION_OF_CONTRACT_OR_EXTENSION_APPROVED"),
    VERSION_OF_CONTRACT_OR_EXTENSION_ACCEPTED("VERSION_OF_CONTRACT_OR_EXTENSION_ACCEPTED"),
    TIMESHEET_APPROVED_EVENT("TIMESHEET_APPROVED_EVENT"),
    NEW_EXTERNAL_SYSTEM_REQUEST_CREATED("NEW_EXTERNAL_SYSTEM_REQUEST_CREATED"),
    UPDATE_EXTERNAL_SYSTEM_REQUEST("UPDATE_EXTERNAL_SYSTEM_REQUEST"),
    CANCEL_EXTERNAL_SYSTEM_REQUEST("CANCEL_EXTERNAL_SYSTEM_REQUEST"),
    NEW_EXTERNAL_SYSTEM_CREATED("NEW_EXTERNAL_SYSTEM_CREATED"),
    POSTING_CREATED("POSTING_CREATED"),
    CANDIDATE_ARCHIVED_OR_DELETED_EVENT("CANDIDATE_ARCHIVED_OR_DELETED_EVENT"),
    USER_CREATED_EVENT("USER_CREATED_EVENT"),
    USER_DATA_UPDATED_EVENT("USER_DATA_UPDATED_EVENT"),
    USER_REMOVED_EVENT("USER_REMOVED_EVENT");

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static EventTypeEnum fromValue(String input) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("eventType")
  private EventTypeEnum eventType = null;

  public EventServiceConfKeyDto queue(TlkQueueDto queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  public TlkQueueDto getQueue() {
    return queue;
  }

  public void setQueue(TlkQueueDto queue) {
    this.queue = queue;
  }

  public EventServiceConfKeyDto eventType(EventTypeEnum eventType) {
    this.eventType = eventType;
    return this;
  }

   /**
   * Get eventType
   * @return eventType
  **/
  public EventTypeEnum getEventType() {
    return eventType;
  }

  public void setEventType(EventTypeEnum eventType) {
    this.eventType = eventType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventServiceConfKeyDto eventServiceConfKeyDto = (EventServiceConfKeyDto) o;
    return Objects.equals(this.queue, eventServiceConfKeyDto.queue) &&
        Objects.equals(this.eventType, eventServiceConfKeyDto.eventType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queue, eventType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventServiceConfKeyDto {\n");
    
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
