/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.AssessmentTestGroupDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ExtSysStatusMappingDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ExternalSystemTypeDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.FormDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.JSONObject;

import java.util.ArrayList;
import java.util.List;
/**
 * ExternalSystemDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class ExternalSystemDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("global")
  private Boolean global = false;

  @JsonProperty("parameters")
  private String parameters = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("active")
  private Boolean active = false;

  @JsonProperty("clientId")
  private String clientId = null;

  @JsonProperty("password")
  private String password = null;

  @JsonProperty("redirectionUrl")
  private String redirectionUrl = null;

  @JsonProperty("defaultEndPoint")
  private String defaultEndPoint = null;

  @JsonProperty("type")
  private ExternalSystemTypeDto type = null;

  @JsonProperty("form")
  private FormDto form = null;

  @JsonProperty("immediateAssessment")
  private Boolean immediateAssessment = false;

  @JsonProperty("useTlkApi")
  private Boolean useTlkApi = false;

  @JsonProperty("redirectCandidate")
  private Boolean redirectCandidate = false;

  @JsonProperty("startDate")
  private Long startDate = null;

  @JsonProperty("endDate")
  private Long endDate = null;

  @JsonProperty("jsonParams")
  private JSONObject jsonParams = null;

  @JsonProperty("vendor_UserId")
  private Long vendorUserId = null;

  @JsonProperty("interfaceId")
  private Long interfaceId = null;

  @JsonProperty("statusMappings")
  private List<ExtSysStatusMappingDto> statusMappings = null;

  @JsonProperty("departments")
  private List<DepartmentDto> departments = null;

  @JsonProperty("assessmentTestGroups")
  private List<AssessmentTestGroupDto> assessmentTestGroups = null;

  @JsonProperty("updateDate")
  private Long updateDate = null;

  @JsonProperty("updateUserId")
  private Long updateUserId = null;

  public ExternalSystemDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ExternalSystemDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExternalSystemDto global(Boolean global) {
    this.global = global;
    return this;
  }

   /**
   * Get global
   * @return global
  **/
  public Boolean isGlobal() {
    return global;
  }

  public void setGlobal(Boolean global) {
    this.global = global;
  }

  public ExternalSystemDto parameters(String parameters) {
    this.parameters = parameters;
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  public String getParameters() {
    return parameters;
  }

  public void setParameters(String parameters) {
    this.parameters = parameters;
  }

  public ExternalSystemDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ExternalSystemDto active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public ExternalSystemDto clientId(String clientId) {
    this.clientId = clientId;
    return this;
  }

   /**
   * Get clientId
   * @return clientId
  **/
  public String getClientId() {
    return clientId;
  }

  public void setClientId(String clientId) {
    this.clientId = clientId;
  }

  public ExternalSystemDto password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public ExternalSystemDto redirectionUrl(String redirectionUrl) {
    this.redirectionUrl = redirectionUrl;
    return this;
  }

   /**
   * Get redirectionUrl
   * @return redirectionUrl
  **/
  public String getRedirectionUrl() {
    return redirectionUrl;
  }

  public void setRedirectionUrl(String redirectionUrl) {
    this.redirectionUrl = redirectionUrl;
  }

  public ExternalSystemDto defaultEndPoint(String defaultEndPoint) {
    this.defaultEndPoint = defaultEndPoint;
    return this;
  }

   /**
   * Get defaultEndPoint
   * @return defaultEndPoint
  **/
  public String getDefaultEndPoint() {
    return defaultEndPoint;
  }

  public void setDefaultEndPoint(String defaultEndPoint) {
    this.defaultEndPoint = defaultEndPoint;
  }

  public ExternalSystemDto type(ExternalSystemTypeDto type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public ExternalSystemTypeDto getType() {
    return type;
  }

  public void setType(ExternalSystemTypeDto type) {
    this.type = type;
  }

  public ExternalSystemDto form(FormDto form) {
    this.form = form;
    return this;
  }

   /**
   * Get form
   * @return form
  **/
  public FormDto getForm() {
    return form;
  }

  public void setForm(FormDto form) {
    this.form = form;
  }

  public ExternalSystemDto immediateAssessment(Boolean immediateAssessment) {
    this.immediateAssessment = immediateAssessment;
    return this;
  }

   /**
   * Get immediateAssessment
   * @return immediateAssessment
  **/
  public Boolean isImmediateAssessment() {
    return immediateAssessment;
  }

  public void setImmediateAssessment(Boolean immediateAssessment) {
    this.immediateAssessment = immediateAssessment;
  }

  public ExternalSystemDto useTlkApi(Boolean useTlkApi) {
    this.useTlkApi = useTlkApi;
    return this;
  }

   /**
   * Get useTlkApi
   * @return useTlkApi
  **/
  public Boolean isUseTlkApi() {
    return useTlkApi;
  }

  public void setUseTlkApi(Boolean useTlkApi) {
    this.useTlkApi = useTlkApi;
  }

  public ExternalSystemDto redirectCandidate(Boolean redirectCandidate) {
    this.redirectCandidate = redirectCandidate;
    return this;
  }

   /**
   * Get redirectCandidate
   * @return redirectCandidate
  **/
  public Boolean isRedirectCandidate() {
    return redirectCandidate;
  }

  public void setRedirectCandidate(Boolean redirectCandidate) {
    this.redirectCandidate = redirectCandidate;
  }

  public ExternalSystemDto startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public ExternalSystemDto endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public ExternalSystemDto jsonParams(JSONObject jsonParams) {
    this.jsonParams = jsonParams;
    return this;
  }

   /**
   * Get jsonParams
   * @return jsonParams
  **/
  public JSONObject getJsonParams() {
    return jsonParams;
  }

  public void setJsonParams(JSONObject jsonParams) {
    this.jsonParams = jsonParams;
  }

  public ExternalSystemDto vendorUserId(Long vendorUserId) {
    this.vendorUserId = vendorUserId;
    return this;
  }

   /**
   * Get vendorUserId
   * @return vendorUserId
  **/
  public Long getVendorUserId() {
    return vendorUserId;
  }

  public void setVendorUserId(Long vendorUserId) {
    this.vendorUserId = vendorUserId;
  }

  public ExternalSystemDto interfaceId(Long interfaceId) {
    this.interfaceId = interfaceId;
    return this;
  }

   /**
   * Get interfaceId
   * @return interfaceId
  **/
  public Long getInterfaceId() {
    return interfaceId;
  }

  public void setInterfaceId(Long interfaceId) {
    this.interfaceId = interfaceId;
  }

  public ExternalSystemDto statusMappings(List<ExtSysStatusMappingDto> statusMappings) {
    this.statusMappings = statusMappings;
    return this;
  }

  public ExternalSystemDto addStatusMappingsItem(ExtSysStatusMappingDto statusMappingsItem) {
    if (this.statusMappings == null) {
      this.statusMappings = new ArrayList<>();
    }
    this.statusMappings.add(statusMappingsItem);
    return this;
  }

   /**
   * Get statusMappings
   * @return statusMappings
  **/
  public List<ExtSysStatusMappingDto> getStatusMappings() {
    return statusMappings;
  }

  public void setStatusMappings(List<ExtSysStatusMappingDto> statusMappings) {
    this.statusMappings = statusMappings;
  }

  public ExternalSystemDto departments(List<DepartmentDto> departments) {
    this.departments = departments;
    return this;
  }

  public ExternalSystemDto addDepartmentsItem(DepartmentDto departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments
  **/
  public List<DepartmentDto> getDepartments() {
    return departments;
  }

  public void setDepartments(List<DepartmentDto> departments) {
    this.departments = departments;
  }

  public ExternalSystemDto assessmentTestGroups(List<AssessmentTestGroupDto> assessmentTestGroups) {
    this.assessmentTestGroups = assessmentTestGroups;
    return this;
  }

  public ExternalSystemDto addAssessmentTestGroupsItem(AssessmentTestGroupDto assessmentTestGroupsItem) {
    if (this.assessmentTestGroups == null) {
      this.assessmentTestGroups = new ArrayList<>();
    }
    this.assessmentTestGroups.add(assessmentTestGroupsItem);
    return this;
  }

   /**
   * Get assessmentTestGroups
   * @return assessmentTestGroups
  **/
  public List<AssessmentTestGroupDto> getAssessmentTestGroups() {
    return assessmentTestGroups;
  }

  public void setAssessmentTestGroups(List<AssessmentTestGroupDto> assessmentTestGroups) {
    this.assessmentTestGroups = assessmentTestGroups;
  }

  public ExternalSystemDto updateDate(Long updateDate) {
    this.updateDate = updateDate;
    return this;
  }

   /**
   * Get updateDate
   * @return updateDate
  **/
  public Long getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Long updateDate) {
    this.updateDate = updateDate;
  }

  public ExternalSystemDto updateUserId(Long updateUserId) {
    this.updateUserId = updateUserId;
    return this;
  }

   /**
   * Get updateUserId
   * @return updateUserId
  **/
  public Long getUpdateUserId() {
    return updateUserId;
  }

  public void setUpdateUserId(Long updateUserId) {
    this.updateUserId = updateUserId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalSystemDto externalSystemDto = (ExternalSystemDto) o;
    return Objects.equals(this.id, externalSystemDto.id) &&
        Objects.equals(this.name, externalSystemDto.name) &&
        Objects.equals(this.global, externalSystemDto.global) &&
        Objects.equals(this.parameters, externalSystemDto.parameters) &&
        Objects.equals(this.description, externalSystemDto.description) &&
        Objects.equals(this.active, externalSystemDto.active) &&
        Objects.equals(this.clientId, externalSystemDto.clientId) &&
        Objects.equals(this.password, externalSystemDto.password) &&
        Objects.equals(this.redirectionUrl, externalSystemDto.redirectionUrl) &&
        Objects.equals(this.defaultEndPoint, externalSystemDto.defaultEndPoint) &&
        Objects.equals(this.type, externalSystemDto.type) &&
        Objects.equals(this.form, externalSystemDto.form) &&
        Objects.equals(this.immediateAssessment, externalSystemDto.immediateAssessment) &&
        Objects.equals(this.useTlkApi, externalSystemDto.useTlkApi) &&
        Objects.equals(this.redirectCandidate, externalSystemDto.redirectCandidate) &&
        Objects.equals(this.startDate, externalSystemDto.startDate) &&
        Objects.equals(this.endDate, externalSystemDto.endDate) &&
        Objects.equals(this.jsonParams, externalSystemDto.jsonParams) &&
        Objects.equals(this.vendorUserId, externalSystemDto.vendorUserId) &&
        Objects.equals(this.interfaceId, externalSystemDto.interfaceId) &&
        Objects.equals(this.statusMappings, externalSystemDto.statusMappings) &&
        Objects.equals(this.departments, externalSystemDto.departments) &&
        Objects.equals(this.assessmentTestGroups, externalSystemDto.assessmentTestGroups) &&
        Objects.equals(this.updateDate, externalSystemDto.updateDate) &&
        Objects.equals(this.updateUserId, externalSystemDto.updateUserId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, global, parameters, description, active, clientId, password, redirectionUrl, defaultEndPoint, type, form, immediateAssessment, useTlkApi, redirectCandidate, startDate, endDate, jsonParams, vendorUserId, interfaceId, statusMappings, departments, assessmentTestGroups, updateDate, updateUserId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalSystemDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    global: ").append(toIndentedString(global)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    redirectionUrl: ").append(toIndentedString(redirectionUrl)).append("\n");
    sb.append("    defaultEndPoint: ").append(toIndentedString(defaultEndPoint)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    immediateAssessment: ").append(toIndentedString(immediateAssessment)).append("\n");
    sb.append("    useTlkApi: ").append(toIndentedString(useTlkApi)).append("\n");
    sb.append("    redirectCandidate: ").append(toIndentedString(redirectCandidate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    jsonParams: ").append(toIndentedString(jsonParams)).append("\n");
    sb.append("    vendorUserId: ").append(toIndentedString(vendorUserId)).append("\n");
    sb.append("    interfaceId: ").append(toIndentedString(interfaceId)).append("\n");
    sb.append("    statusMappings: ").append(toIndentedString(statusMappings)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("    assessmentTestGroups: ").append(toIndentedString(assessmentTestGroups)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    updateUserId: ").append(toIndentedString(updateUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
