/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TranslationsDto;

/**
 * FormulaDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class FormulaDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("translations")
  private TranslationsDto translations = null;

  /**
   * Gets or Sets rateType
   */
  public enum RateTypeEnum {
    CHARGERATE("ChargeRate"),
    SUPPLIERRATE("SupplierRate"),
    PAYRATE("PayRate"),
    CUSTOMRATE("CustomRate"),
    PAY2SUPPLIER("Pay2Supplier"),
    SUPPLIER2CHARGE("Supplier2Charge"),
    OVERALL("Overall");

    private String value;

    RateTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RateTypeEnum fromValue(String input) {
      for (RateTypeEnum b : RateTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("rateType")
  private RateTypeEnum rateType = null;

  /**
   * Gets or Sets unit
   */
  public enum UnitEnum {
    PERCENT("PERCENT"),
    CURRENCY("CURRENCY");

    private String value;

    UnitEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static UnitEnum fromValue(String input) {
      for (UnitEnum b : UnitEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("unit")
  private UnitEnum unit = null;

  @JsonProperty("input")
  private Boolean input = false;

  public FormulaDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FormulaDto translations(TranslationsDto translations) {
    this.translations = translations;
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  public TranslationsDto getTranslations() {
    return translations;
  }

  public void setTranslations(TranslationsDto translations) {
    this.translations = translations;
  }

  public FormulaDto rateType(RateTypeEnum rateType) {
    this.rateType = rateType;
    return this;
  }

   /**
   * Get rateType
   * @return rateType
  **/
  public RateTypeEnum getRateType() {
    return rateType;
  }

  public void setRateType(RateTypeEnum rateType) {
    this.rateType = rateType;
  }

  public FormulaDto unit(UnitEnum unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  public UnitEnum getUnit() {
    return unit;
  }

  public void setUnit(UnitEnum unit) {
    this.unit = unit;
  }

  public FormulaDto input(Boolean input) {
    this.input = input;
    return this;
  }

   /**
   * Get input
   * @return input
  **/
  public Boolean isInput() {
    return input;
  }

  public void setInput(Boolean input) {
    this.input = input;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FormulaDto formulaDto = (FormulaDto) o;
    return Objects.equals(this.name, formulaDto.name) &&
        Objects.equals(this.translations, formulaDto.translations) &&
        Objects.equals(this.rateType, formulaDto.rateType) &&
        Objects.equals(this.unit, formulaDto.unit) &&
        Objects.equals(this.input, formulaDto.input);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, translations, rateType, unit, input);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FormulaDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    rateType: ").append(toIndentedString(rateType)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
