/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ChildrenFreeFormFieldDto;

import java.util.ArrayList;
import java.util.List;
/**
 * FreeFormFieldTriggerDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class FreeFormFieldTriggerDto {
  @JsonProperty("lovId")
  private Long lovId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("translatedName")
  private String translatedName = null;

  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("children")
  private List<ChildrenFreeFormFieldDto> children = null;

  @JsonProperty("active")
  private Boolean active = false;

  @JsonProperty("required")
  private Boolean required = false;

  @JsonProperty("tsTrigger")
  private Boolean tsTrigger = false;

  public FreeFormFieldTriggerDto lovId(Long lovId) {
    this.lovId = lovId;
    return this;
  }

   /**
   * Get lovId
   * @return lovId
  **/
  public Long getLovId() {
    return lovId;
  }

  public void setLovId(Long lovId) {
    this.lovId = lovId;
  }

  public FreeFormFieldTriggerDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FreeFormFieldTriggerDto translatedName(String translatedName) {
    this.translatedName = translatedName;
    return this;
  }

   /**
   * Get translatedName
   * @return translatedName
  **/
  public String getTranslatedName() {
    return translatedName;
  }

  public void setTranslatedName(String translatedName) {
    this.translatedName = translatedName;
  }

  public FreeFormFieldTriggerDto order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public FreeFormFieldTriggerDto children(List<ChildrenFreeFormFieldDto> children) {
    this.children = children;
    return this;
  }

  public FreeFormFieldTriggerDto addChildrenItem(ChildrenFreeFormFieldDto childrenItem) {
    if (this.children == null) {
      this.children = new ArrayList<>();
    }
    this.children.add(childrenItem);
    return this;
  }

   /**
   * Get children
   * @return children
  **/
  public List<ChildrenFreeFormFieldDto> getChildren() {
    return children;
  }

  public void setChildren(List<ChildrenFreeFormFieldDto> children) {
    this.children = children;
  }

  public FreeFormFieldTriggerDto active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public FreeFormFieldTriggerDto required(Boolean required) {
    this.required = required;
    return this;
  }

   /**
   * Get required
   * @return required
  **/
  public Boolean isRequired() {
    return required;
  }

  public void setRequired(Boolean required) {
    this.required = required;
  }

  public FreeFormFieldTriggerDto tsTrigger(Boolean tsTrigger) {
    this.tsTrigger = tsTrigger;
    return this;
  }

   /**
   * Get tsTrigger
   * @return tsTrigger
  **/
  public Boolean isTsTrigger() {
    return tsTrigger;
  }

  public void setTsTrigger(Boolean tsTrigger) {
    this.tsTrigger = tsTrigger;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FreeFormFieldTriggerDto freeFormFieldTriggerDto = (FreeFormFieldTriggerDto) o;
    return Objects.equals(this.lovId, freeFormFieldTriggerDto.lovId) &&
        Objects.equals(this.name, freeFormFieldTriggerDto.name) &&
        Objects.equals(this.translatedName, freeFormFieldTriggerDto.translatedName) &&
        Objects.equals(this.order, freeFormFieldTriggerDto.order) &&
        Objects.equals(this.children, freeFormFieldTriggerDto.children) &&
        Objects.equals(this.active, freeFormFieldTriggerDto.active) &&
        Objects.equals(this.required, freeFormFieldTriggerDto.required) &&
        Objects.equals(this.tsTrigger, freeFormFieldTriggerDto.tsTrigger);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lovId, name, translatedName, order, children, active, required, tsTrigger);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FreeFormFieldTriggerDto {\n");
    
    sb.append("    lovId: ").append(toIndentedString(lovId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    translatedName: ").append(toIndentedString(translatedName)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    children: ").append(toIndentedString(children)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    required: ").append(toIndentedString(required)).append("\n");
    sb.append("    tsTrigger: ").append(toIndentedString(tsTrigger)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
