/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ApplicationDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ApprovalProcessFullDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ContractorDetailsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.FreeFormFieldDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LovDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.MidPeriodConfigDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.PermanentDetailsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TimesheetConfigDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserDto;

import java.util.ArrayList;
import java.util.List;
/**
 * FullContractDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class FullContractDto {
  @JsonProperty("approved")
  private Boolean approved = false;

  @JsonProperty("accepted")
  private Boolean accepted = false;

  @JsonProperty("acceptApproved")
  private Boolean acceptApproved = false;

  @JsonProperty("administrativeComments")
  private String administrativeComments = null;

  @JsonProperty("plannedStartDate")
  private Long plannedStartDate = null;

  @JsonProperty("plannedEndDate")
  private Long plannedEndDate = null;

  @JsonProperty("scheduleType")
  private String scheduleType = null;

  @JsonProperty("workAmount")
  private Float workAmount = null;

  @JsonProperty("workPeriod")
  private String workPeriod = null;

  @JsonProperty("workUnit")
  private String workUnit = null;

  @JsonProperty("bonusCondition")
  private String bonusCondition = null;

  @JsonProperty("contractType")
  private String contractType = null;

  @JsonProperty("length")
  private Float length = null;

  @JsonProperty("lengthUnit")
  private String lengthUnit = null;

  @JsonProperty("permanentDetails")
  private PermanentDetailsDto permanentDetails = null;

  @JsonProperty("contractorDetails")
  private ContractorDetailsDto contractorDetails = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("extension")
  private Integer extension = null;

  @JsonProperty("current")
  private Boolean current = false;

  @JsonProperty("revision")
  private Boolean revision = false;

  @JsonProperty("creation")
  private Long creation = null;

  @JsonProperty("update")
  private Long update = null;

  @JsonProperty("approval")
  private Long approval = null;

  @JsonProperty("contractStatus")
  private String contractStatus = null;

  @JsonProperty("negotiationStatus")
  private String negotiationStatus = null;

  @JsonProperty("creationUser")
  private UserDto creationUser = null;

  @JsonProperty("updateUser")
  private UserDto updateUser = null;

  @JsonProperty("lovs")
  private List<LovDto> lovs = null;

  @JsonProperty("freeFormFields")
  private List<FreeFormFieldDto> freeFormFields = null;

  @JsonProperty("application")
  private ApplicationDto application = null;

  @JsonProperty("timesheetConfig")
  private TimesheetConfigDto timesheetConfig = null;

  @JsonProperty("approvalProcess")
  private ApprovalProcessFullDto approvalProcess = null;

  @JsonProperty("midPeriodsConfigs")
  private List<MidPeriodConfigDto> midPeriodsConfigs = null;

  @JsonProperty("deleted")
  private Boolean deleted = false;

  public FullContractDto approved(Boolean approved) {
    this.approved = approved;
    return this;
  }

   /**
   * Get approved
   * @return approved
  **/
  public Boolean isApproved() {
    return approved;
  }

  public void setApproved(Boolean approved) {
    this.approved = approved;
  }

  public FullContractDto accepted(Boolean accepted) {
    this.accepted = accepted;
    return this;
  }

   /**
   * Get accepted
   * @return accepted
  **/
  public Boolean isAccepted() {
    return accepted;
  }

  public void setAccepted(Boolean accepted) {
    this.accepted = accepted;
  }

  public FullContractDto acceptApproved(Boolean acceptApproved) {
    this.acceptApproved = acceptApproved;
    return this;
  }

   /**
   * Get acceptApproved
   * @return acceptApproved
  **/
  public Boolean isAcceptApproved() {
    return acceptApproved;
  }

  public void setAcceptApproved(Boolean acceptApproved) {
    this.acceptApproved = acceptApproved;
  }

  public FullContractDto administrativeComments(String administrativeComments) {
    this.administrativeComments = administrativeComments;
    return this;
  }

   /**
   * Get administrativeComments
   * @return administrativeComments
  **/
  public String getAdministrativeComments() {
    return administrativeComments;
  }

  public void setAdministrativeComments(String administrativeComments) {
    this.administrativeComments = administrativeComments;
  }

  public FullContractDto plannedStartDate(Long plannedStartDate) {
    this.plannedStartDate = plannedStartDate;
    return this;
  }

   /**
   * Get plannedStartDate
   * @return plannedStartDate
  **/
  public Long getPlannedStartDate() {
    return plannedStartDate;
  }

  public void setPlannedStartDate(Long plannedStartDate) {
    this.plannedStartDate = plannedStartDate;
  }

  public FullContractDto plannedEndDate(Long plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
    return this;
  }

   /**
   * Get plannedEndDate
   * @return plannedEndDate
  **/
  public Long getPlannedEndDate() {
    return plannedEndDate;
  }

  public void setPlannedEndDate(Long plannedEndDate) {
    this.plannedEndDate = plannedEndDate;
  }

  public FullContractDto scheduleType(String scheduleType) {
    this.scheduleType = scheduleType;
    return this;
  }

   /**
   * Get scheduleType
   * @return scheduleType
  **/
  public String getScheduleType() {
    return scheduleType;
  }

  public void setScheduleType(String scheduleType) {
    this.scheduleType = scheduleType;
  }

  public FullContractDto workAmount(Float workAmount) {
    this.workAmount = workAmount;
    return this;
  }

   /**
   * Get workAmount
   * @return workAmount
  **/
  public Float getWorkAmount() {
    return workAmount;
  }

  public void setWorkAmount(Float workAmount) {
    this.workAmount = workAmount;
  }

  public FullContractDto workPeriod(String workPeriod) {
    this.workPeriod = workPeriod;
    return this;
  }

   /**
   * Get workPeriod
   * @return workPeriod
  **/
  public String getWorkPeriod() {
    return workPeriod;
  }

  public void setWorkPeriod(String workPeriod) {
    this.workPeriod = workPeriod;
  }

  public FullContractDto workUnit(String workUnit) {
    this.workUnit = workUnit;
    return this;
  }

   /**
   * Get workUnit
   * @return workUnit
  **/
  public String getWorkUnit() {
    return workUnit;
  }

  public void setWorkUnit(String workUnit) {
    this.workUnit = workUnit;
  }

  public FullContractDto bonusCondition(String bonusCondition) {
    this.bonusCondition = bonusCondition;
    return this;
  }

   /**
   * Get bonusCondition
   * @return bonusCondition
  **/
  public String getBonusCondition() {
    return bonusCondition;
  }

  public void setBonusCondition(String bonusCondition) {
    this.bonusCondition = bonusCondition;
  }

  public FullContractDto contractType(String contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  public String getContractType() {
    return contractType;
  }

  public void setContractType(String contractType) {
    this.contractType = contractType;
  }

  public FullContractDto length(Float length) {
    this.length = length;
    return this;
  }

   /**
   * Get length
   * @return length
  **/
  public Float getLength() {
    return length;
  }

  public void setLength(Float length) {
    this.length = length;
  }

  public FullContractDto lengthUnit(String lengthUnit) {
    this.lengthUnit = lengthUnit;
    return this;
  }

   /**
   * Get lengthUnit
   * @return lengthUnit
  **/
  public String getLengthUnit() {
    return lengthUnit;
  }

  public void setLengthUnit(String lengthUnit) {
    this.lengthUnit = lengthUnit;
  }

  public FullContractDto permanentDetails(PermanentDetailsDto permanentDetails) {
    this.permanentDetails = permanentDetails;
    return this;
  }

   /**
   * Get permanentDetails
   * @return permanentDetails
  **/
  public PermanentDetailsDto getPermanentDetails() {
    return permanentDetails;
  }

  public void setPermanentDetails(PermanentDetailsDto permanentDetails) {
    this.permanentDetails = permanentDetails;
  }

  public FullContractDto contractorDetails(ContractorDetailsDto contractorDetails) {
    this.contractorDetails = contractorDetails;
    return this;
  }

   /**
   * Get contractorDetails
   * @return contractorDetails
  **/
  public ContractorDetailsDto getContractorDetails() {
    return contractorDetails;
  }

  public void setContractorDetails(ContractorDetailsDto contractorDetails) {
    this.contractorDetails = contractorDetails;
  }

  public FullContractDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public FullContractDto version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public FullContractDto extension(Integer extension) {
    this.extension = extension;
    return this;
  }

   /**
   * Get extension
   * @return extension
  **/
  public Integer getExtension() {
    return extension;
  }

  public void setExtension(Integer extension) {
    this.extension = extension;
  }

  public FullContractDto current(Boolean current) {
    this.current = current;
    return this;
  }

   /**
   * Get current
   * @return current
  **/
  public Boolean isCurrent() {
    return current;
  }

  public void setCurrent(Boolean current) {
    this.current = current;
  }

  public FullContractDto revision(Boolean revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Get revision
   * @return revision
  **/
  public Boolean isRevision() {
    return revision;
  }

  public void setRevision(Boolean revision) {
    this.revision = revision;
  }

  public FullContractDto creation(Long creation) {
    this.creation = creation;
    return this;
  }

   /**
   * Get creation
   * @return creation
  **/
  public Long getCreation() {
    return creation;
  }

  public void setCreation(Long creation) {
    this.creation = creation;
  }

  public FullContractDto update(Long update) {
    this.update = update;
    return this;
  }

   /**
   * Get update
   * @return update
  **/
  public Long getUpdate() {
    return update;
  }

  public void setUpdate(Long update) {
    this.update = update;
  }

  public FullContractDto approval(Long approval) {
    this.approval = approval;
    return this;
  }

   /**
   * Get approval
   * @return approval
  **/
  public Long getApproval() {
    return approval;
  }

  public void setApproval(Long approval) {
    this.approval = approval;
  }

  public FullContractDto contractStatus(String contractStatus) {
    this.contractStatus = contractStatus;
    return this;
  }

   /**
   * Get contractStatus
   * @return contractStatus
  **/
  public String getContractStatus() {
    return contractStatus;
  }

  public void setContractStatus(String contractStatus) {
    this.contractStatus = contractStatus;
  }

  public FullContractDto negotiationStatus(String negotiationStatus) {
    this.negotiationStatus = negotiationStatus;
    return this;
  }

   /**
   * Get negotiationStatus
   * @return negotiationStatus
  **/
  public String getNegotiationStatus() {
    return negotiationStatus;
  }

  public void setNegotiationStatus(String negotiationStatus) {
    this.negotiationStatus = negotiationStatus;
  }

  public FullContractDto creationUser(UserDto creationUser) {
    this.creationUser = creationUser;
    return this;
  }

   /**
   * Get creationUser
   * @return creationUser
  **/
  public UserDto getCreationUser() {
    return creationUser;
  }

  public void setCreationUser(UserDto creationUser) {
    this.creationUser = creationUser;
  }

  public FullContractDto updateUser(UserDto updateUser) {
    this.updateUser = updateUser;
    return this;
  }

   /**
   * Get updateUser
   * @return updateUser
  **/
  public UserDto getUpdateUser() {
    return updateUser;
  }

  public void setUpdateUser(UserDto updateUser) {
    this.updateUser = updateUser;
  }

  public FullContractDto lovs(List<LovDto> lovs) {
    this.lovs = lovs;
    return this;
  }

  public FullContractDto addLovsItem(LovDto lovsItem) {
    if (this.lovs == null) {
      this.lovs = new ArrayList<>();
    }
    this.lovs.add(lovsItem);
    return this;
  }

   /**
   * Get lovs
   * @return lovs
  **/
  public List<LovDto> getLovs() {
    return lovs;
  }

  public void setLovs(List<LovDto> lovs) {
    this.lovs = lovs;
  }

  public FullContractDto freeFormFields(List<FreeFormFieldDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
    return this;
  }

  public FullContractDto addFreeFormFieldsItem(FreeFormFieldDto freeFormFieldsItem) {
    if (this.freeFormFields == null) {
      this.freeFormFields = new ArrayList<>();
    }
    this.freeFormFields.add(freeFormFieldsItem);
    return this;
  }

   /**
   * Get freeFormFields
   * @return freeFormFields
  **/
  public List<FreeFormFieldDto> getFreeFormFields() {
    return freeFormFields;
  }

  public void setFreeFormFields(List<FreeFormFieldDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
  }

  public FullContractDto application(ApplicationDto application) {
    this.application = application;
    return this;
  }

   /**
   * Get application
   * @return application
  **/
  public ApplicationDto getApplication() {
    return application;
  }

  public void setApplication(ApplicationDto application) {
    this.application = application;
  }

  public FullContractDto timesheetConfig(TimesheetConfigDto timesheetConfig) {
    this.timesheetConfig = timesheetConfig;
    return this;
  }

   /**
   * Get timesheetConfig
   * @return timesheetConfig
  **/
  public TimesheetConfigDto getTimesheetConfig() {
    return timesheetConfig;
  }

  public void setTimesheetConfig(TimesheetConfigDto timesheetConfig) {
    this.timesheetConfig = timesheetConfig;
  }

  public FullContractDto approvalProcess(ApprovalProcessFullDto approvalProcess) {
    this.approvalProcess = approvalProcess;
    return this;
  }

   /**
   * Get approvalProcess
   * @return approvalProcess
  **/
  public ApprovalProcessFullDto getApprovalProcess() {
    return approvalProcess;
  }

  public void setApprovalProcess(ApprovalProcessFullDto approvalProcess) {
    this.approvalProcess = approvalProcess;
  }

  public FullContractDto midPeriodsConfigs(List<MidPeriodConfigDto> midPeriodsConfigs) {
    this.midPeriodsConfigs = midPeriodsConfigs;
    return this;
  }

  public FullContractDto addMidPeriodsConfigsItem(MidPeriodConfigDto midPeriodsConfigsItem) {
    if (this.midPeriodsConfigs == null) {
      this.midPeriodsConfigs = new ArrayList<>();
    }
    this.midPeriodsConfigs.add(midPeriodsConfigsItem);
    return this;
  }

   /**
   * Get midPeriodsConfigs
   * @return midPeriodsConfigs
  **/
  public List<MidPeriodConfigDto> getMidPeriodsConfigs() {
    return midPeriodsConfigs;
  }

  public void setMidPeriodsConfigs(List<MidPeriodConfigDto> midPeriodsConfigs) {
    this.midPeriodsConfigs = midPeriodsConfigs;
  }

  public FullContractDto deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Get deleted
   * @return deleted
  **/
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FullContractDto fullContractDto = (FullContractDto) o;
    return Objects.equals(this.approved, fullContractDto.approved) &&
        Objects.equals(this.accepted, fullContractDto.accepted) &&
        Objects.equals(this.acceptApproved, fullContractDto.acceptApproved) &&
        Objects.equals(this.administrativeComments, fullContractDto.administrativeComments) &&
        Objects.equals(this.plannedStartDate, fullContractDto.plannedStartDate) &&
        Objects.equals(this.plannedEndDate, fullContractDto.plannedEndDate) &&
        Objects.equals(this.scheduleType, fullContractDto.scheduleType) &&
        Objects.equals(this.workAmount, fullContractDto.workAmount) &&
        Objects.equals(this.workPeriod, fullContractDto.workPeriod) &&
        Objects.equals(this.workUnit, fullContractDto.workUnit) &&
        Objects.equals(this.bonusCondition, fullContractDto.bonusCondition) &&
        Objects.equals(this.contractType, fullContractDto.contractType) &&
        Objects.equals(this.length, fullContractDto.length) &&
        Objects.equals(this.lengthUnit, fullContractDto.lengthUnit) &&
        Objects.equals(this.permanentDetails, fullContractDto.permanentDetails) &&
        Objects.equals(this.contractorDetails, fullContractDto.contractorDetails) &&
        Objects.equals(this.id, fullContractDto.id) &&
        Objects.equals(this.version, fullContractDto.version) &&
        Objects.equals(this.extension, fullContractDto.extension) &&
        Objects.equals(this.current, fullContractDto.current) &&
        Objects.equals(this.revision, fullContractDto.revision) &&
        Objects.equals(this.creation, fullContractDto.creation) &&
        Objects.equals(this.update, fullContractDto.update) &&
        Objects.equals(this.approval, fullContractDto.approval) &&
        Objects.equals(this.contractStatus, fullContractDto.contractStatus) &&
        Objects.equals(this.negotiationStatus, fullContractDto.negotiationStatus) &&
        Objects.equals(this.creationUser, fullContractDto.creationUser) &&
        Objects.equals(this.updateUser, fullContractDto.updateUser) &&
        Objects.equals(this.lovs, fullContractDto.lovs) &&
        Objects.equals(this.freeFormFields, fullContractDto.freeFormFields) &&
        Objects.equals(this.application, fullContractDto.application) &&
        Objects.equals(this.timesheetConfig, fullContractDto.timesheetConfig) &&
        Objects.equals(this.approvalProcess, fullContractDto.approvalProcess) &&
        Objects.equals(this.midPeriodsConfigs, fullContractDto.midPeriodsConfigs) &&
        Objects.equals(this.deleted, fullContractDto.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(approved, accepted, acceptApproved, administrativeComments, plannedStartDate, plannedEndDate, scheduleType, workAmount, workPeriod, workUnit, bonusCondition, contractType, length, lengthUnit, permanentDetails, contractorDetails, id, version, extension, current, revision, creation, update, approval, contractStatus, negotiationStatus, creationUser, updateUser, lovs, freeFormFields, application, timesheetConfig, approvalProcess, midPeriodsConfigs, deleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FullContractDto {\n");
    
    sb.append("    approved: ").append(toIndentedString(approved)).append("\n");
    sb.append("    accepted: ").append(toIndentedString(accepted)).append("\n");
    sb.append("    acceptApproved: ").append(toIndentedString(acceptApproved)).append("\n");
    sb.append("    administrativeComments: ").append(toIndentedString(administrativeComments)).append("\n");
    sb.append("    plannedStartDate: ").append(toIndentedString(plannedStartDate)).append("\n");
    sb.append("    plannedEndDate: ").append(toIndentedString(plannedEndDate)).append("\n");
    sb.append("    scheduleType: ").append(toIndentedString(scheduleType)).append("\n");
    sb.append("    workAmount: ").append(toIndentedString(workAmount)).append("\n");
    sb.append("    workPeriod: ").append(toIndentedString(workPeriod)).append("\n");
    sb.append("    workUnit: ").append(toIndentedString(workUnit)).append("\n");
    sb.append("    bonusCondition: ").append(toIndentedString(bonusCondition)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("    lengthUnit: ").append(toIndentedString(lengthUnit)).append("\n");
    sb.append("    permanentDetails: ").append(toIndentedString(permanentDetails)).append("\n");
    sb.append("    contractorDetails: ").append(toIndentedString(contractorDetails)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    approval: ").append(toIndentedString(approval)).append("\n");
    sb.append("    contractStatus: ").append(toIndentedString(contractStatus)).append("\n");
    sb.append("    negotiationStatus: ").append(toIndentedString(negotiationStatus)).append("\n");
    sb.append("    creationUser: ").append(toIndentedString(creationUser)).append("\n");
    sb.append("    updateUser: ").append(toIndentedString(updateUser)).append("\n");
    sb.append("    lovs: ").append(toIndentedString(lovs)).append("\n");
    sb.append("    freeFormFields: ").append(toIndentedString(freeFormFields)).append("\n");
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    timesheetConfig: ").append(toIndentedString(timesheetConfig)).append("\n");
    sb.append("    approvalProcess: ").append(toIndentedString(approvalProcess)).append("\n");
    sb.append("    midPeriodsConfigs: ").append(toIndentedString(midPeriodsConfigs)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
