/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.IndeedApplyEndpointsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.SponsoredJobContextDto;

import java.util.ArrayList;
import java.util.List;
/**
 * IndeedConfigurationDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class IndeedConfigurationDto {
  @JsonProperty("organic")
  private Boolean organic = false;

  @JsonProperty("sponsored")
  private Boolean sponsored = false;

  @JsonProperty("sponsoredJobContexts")
  private List<SponsoredJobContextDto> sponsoredJobContexts = null;

  @JsonProperty("indeedApply")
  private Boolean indeedApply = false;

  @JsonProperty("indeedApplyEndpoints")
  private IndeedApplyEndpointsDto indeedApplyEndpoints = null;

  public IndeedConfigurationDto organic(Boolean organic) {
    this.organic = organic;
    return this;
  }

   /**
   * Get organic
   * @return organic
  **/
  public Boolean isOrganic() {
    return organic;
  }

  public void setOrganic(Boolean organic) {
    this.organic = organic;
  }

  public IndeedConfigurationDto sponsored(Boolean sponsored) {
    this.sponsored = sponsored;
    return this;
  }

   /**
   * Get sponsored
   * @return sponsored
  **/
  public Boolean isSponsored() {
    return sponsored;
  }

  public void setSponsored(Boolean sponsored) {
    this.sponsored = sponsored;
  }

  public IndeedConfigurationDto sponsoredJobContexts(List<SponsoredJobContextDto> sponsoredJobContexts) {
    this.sponsoredJobContexts = sponsoredJobContexts;
    return this;
  }

  public IndeedConfigurationDto addSponsoredJobContextsItem(SponsoredJobContextDto sponsoredJobContextsItem) {
    if (this.sponsoredJobContexts == null) {
      this.sponsoredJobContexts = new ArrayList<>();
    }
    this.sponsoredJobContexts.add(sponsoredJobContextsItem);
    return this;
  }

   /**
   * Get sponsoredJobContexts
   * @return sponsoredJobContexts
  **/
  public List<SponsoredJobContextDto> getSponsoredJobContexts() {
    return sponsoredJobContexts;
  }

  public void setSponsoredJobContexts(List<SponsoredJobContextDto> sponsoredJobContexts) {
    this.sponsoredJobContexts = sponsoredJobContexts;
  }

  public IndeedConfigurationDto indeedApply(Boolean indeedApply) {
    this.indeedApply = indeedApply;
    return this;
  }

   /**
   * Get indeedApply
   * @return indeedApply
  **/
  public Boolean isIndeedApply() {
    return indeedApply;
  }

  public void setIndeedApply(Boolean indeedApply) {
    this.indeedApply = indeedApply;
  }

  public IndeedConfigurationDto indeedApplyEndpoints(IndeedApplyEndpointsDto indeedApplyEndpoints) {
    this.indeedApplyEndpoints = indeedApplyEndpoints;
    return this;
  }

   /**
   * Get indeedApplyEndpoints
   * @return indeedApplyEndpoints
  **/
  public IndeedApplyEndpointsDto getIndeedApplyEndpoints() {
    return indeedApplyEndpoints;
  }

  public void setIndeedApplyEndpoints(IndeedApplyEndpointsDto indeedApplyEndpoints) {
    this.indeedApplyEndpoints = indeedApplyEndpoints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndeedConfigurationDto indeedConfigurationDto = (IndeedConfigurationDto) o;
    return Objects.equals(this.organic, indeedConfigurationDto.organic) &&
        Objects.equals(this.sponsored, indeedConfigurationDto.sponsored) &&
        Objects.equals(this.sponsoredJobContexts, indeedConfigurationDto.sponsoredJobContexts) &&
        Objects.equals(this.indeedApply, indeedConfigurationDto.indeedApply) &&
        Objects.equals(this.indeedApplyEndpoints, indeedConfigurationDto.indeedApplyEndpoints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(organic, sponsored, sponsoredJobContexts, indeedApply, indeedApplyEndpoints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndeedConfigurationDto {\n");
    
    sb.append("    organic: ").append(toIndentedString(organic)).append("\n");
    sb.append("    sponsored: ").append(toIndentedString(sponsored)).append("\n");
    sb.append("    sponsoredJobContexts: ").append(toIndentedString(sponsoredJobContexts)).append("\n");
    sb.append("    indeedApply: ").append(toIndentedString(indeedApply)).append("\n");
    sb.append("    indeedApplyEndpoints: ").append(toIndentedString(indeedApplyEndpoints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
