/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.IdDto;

import java.util.ArrayList;
import java.util.List;
/**
 * InterviewLocationBasicDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class InterviewLocationBasicDto {
  @JsonProperty("title")
  private String title = null;

  @JsonProperty("address1")
  private String address1 = null;

  @JsonProperty("address2")
  private String address2 = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("zipcode")
  private String zipcode = null;

  @JsonProperty("region")
  private String region = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("room")
  private String room = null;

  @JsonProperty("timezone")
  private String timezone = null;

  @JsonProperty("local")
  private Boolean local = false;

  @JsonProperty("standard")
  private Boolean standard = false;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("departments")
  private List<IdDto> departments = null;

  public InterviewLocationBasicDto title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public InterviewLocationBasicDto address1(String address1) {
    this.address1 = address1;
    return this;
  }

   /**
   * Get address1
   * @return address1
  **/
  public String getAddress1() {
    return address1;
  }

  public void setAddress1(String address1) {
    this.address1 = address1;
  }

  public InterviewLocationBasicDto address2(String address2) {
    this.address2 = address2;
    return this;
  }

   /**
   * Get address2
   * @return address2
  **/
  public String getAddress2() {
    return address2;
  }

  public void setAddress2(String address2) {
    this.address2 = address2;
  }

  public InterviewLocationBasicDto city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public InterviewLocationBasicDto zipcode(String zipcode) {
    this.zipcode = zipcode;
    return this;
  }

   /**
   * Get zipcode
   * @return zipcode
  **/
  public String getZipcode() {
    return zipcode;
  }

  public void setZipcode(String zipcode) {
    this.zipcode = zipcode;
  }

  public InterviewLocationBasicDto region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public InterviewLocationBasicDto country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public InterviewLocationBasicDto room(String room) {
    this.room = room;
    return this;
  }

   /**
   * Get room
   * @return room
  **/
  public String getRoom() {
    return room;
  }

  public void setRoom(String room) {
    this.room = room;
  }

  public InterviewLocationBasicDto timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public InterviewLocationBasicDto local(Boolean local) {
    this.local = local;
    return this;
  }

   /**
   * Get local
   * @return local
  **/
  public Boolean isLocal() {
    return local;
  }

  public void setLocal(Boolean local) {
    this.local = local;
  }

  public InterviewLocationBasicDto standard(Boolean standard) {
    this.standard = standard;
    return this;
  }

   /**
   * Get standard
   * @return standard
  **/
  public Boolean isStandard() {
    return standard;
  }

  public void setStandard(Boolean standard) {
    this.standard = standard;
  }

  public InterviewLocationBasicDto email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InterviewLocationBasicDto departments(List<IdDto> departments) {
    this.departments = departments;
    return this;
  }

  public InterviewLocationBasicDto addDepartmentsItem(IdDto departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments
  **/
  public List<IdDto> getDepartments() {
    return departments;
  }

  public void setDepartments(List<IdDto> departments) {
    this.departments = departments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InterviewLocationBasicDto interviewLocationBasicDto = (InterviewLocationBasicDto) o;
    return Objects.equals(this.title, interviewLocationBasicDto.title) &&
        Objects.equals(this.address1, interviewLocationBasicDto.address1) &&
        Objects.equals(this.address2, interviewLocationBasicDto.address2) &&
        Objects.equals(this.city, interviewLocationBasicDto.city) &&
        Objects.equals(this.zipcode, interviewLocationBasicDto.zipcode) &&
        Objects.equals(this.region, interviewLocationBasicDto.region) &&
        Objects.equals(this.country, interviewLocationBasicDto.country) &&
        Objects.equals(this.room, interviewLocationBasicDto.room) &&
        Objects.equals(this.timezone, interviewLocationBasicDto.timezone) &&
        Objects.equals(this.local, interviewLocationBasicDto.local) &&
        Objects.equals(this.standard, interviewLocationBasicDto.standard) &&
        Objects.equals(this.email, interviewLocationBasicDto.email) &&
        Objects.equals(this.departments, interviewLocationBasicDto.departments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, address1, address2, city, zipcode, region, country, room, timezone, local, standard, email, departments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InterviewLocationBasicDto {\n");
    
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    local: ").append(toIndentedString(local)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
