/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.Channel;

import java.util.ArrayList;
import java.util.List;
/**
 * JobboardDTO
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class JobboardDTO {
  @JsonProperty("postingAction")
  private String postingAction = null;

  @JsonProperty("postingStatus")
  private String postingStatus = null;

  @JsonProperty("startDate")
  private Long startDate = null;

  @JsonProperty("endDate")
  private Long endDate = null;

  @JsonProperty("errorCode")
  private String errorCode = null;

  @JsonProperty("channels")
  private List<Channel> channels = null;

  /**
   * Gets or Sets postingActionAsEnum
   */
  public enum PostingActionAsEnumEnum {
    INSERT("INSERT"),
    UPDATE("UPDATE"),
    CHANNEL_DELETE("CHANNEL_DELETE"),
    DELETE("DELETE"),
    NAVIGATE("NAVIGATE"),
    RESEND_WITHOUT_CHANGES("RESEND_WITHOUT_CHANGES");

    private String value;

    PostingActionAsEnumEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PostingActionAsEnumEnum fromValue(String input) {
      for (PostingActionAsEnumEnum b : PostingActionAsEnumEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("postingActionAsEnum")
  private PostingActionAsEnumEnum postingActionAsEnum = null;

  /**
   * Gets or Sets postingStatusAsEnum
   */
  public enum PostingStatusAsEnumEnum {
    INITIAL("INITIAL"),
    PENDING("PENDING"),
    MULTIPOST_PENDING("MULTIPOST_PENDING"),
    ACTIVE("ACTIVE"),
    DEFERRED("DEFERRED"),
    QUEUED_FOR_FUTURE_POSTING("QUEUED_FOR_FUTURE_POSTING"),
    INACTIVE("INACTIVE"),
    DELETED("DELETED"),
    EXPIRED("EXPIRED"),
    FAILED("FAILED"),
    ERROR("ERROR"),
    SUCCESS("SUCCESS"),
    CANCELLED("CANCELLED");

    private String value;

    PostingStatusAsEnumEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PostingStatusAsEnumEnum fromValue(String input) {
      for (PostingStatusAsEnumEnum b : PostingStatusAsEnumEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("postingStatusAsEnum")
  private PostingStatusAsEnumEnum postingStatusAsEnum = null;

  @JsonProperty("statusDescription")
  private String statusDescription = null;

  public JobboardDTO postingAction(String postingAction) {
    this.postingAction = postingAction;
    return this;
  }

   /**
   * Get postingAction
   * @return postingAction
  **/
  public String getPostingAction() {
    return postingAction;
  }

  public void setPostingAction(String postingAction) {
    this.postingAction = postingAction;
  }

  public JobboardDTO postingStatus(String postingStatus) {
    this.postingStatus = postingStatus;
    return this;
  }

   /**
   * Get postingStatus
   * @return postingStatus
  **/
  public String getPostingStatus() {
    return postingStatus;
  }

  public void setPostingStatus(String postingStatus) {
    this.postingStatus = postingStatus;
  }

  public JobboardDTO startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public JobboardDTO endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public JobboardDTO errorCode(String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

   /**
   * Get errorCode
   * @return errorCode
  **/
  public String getErrorCode() {
    return errorCode;
  }

  public void setErrorCode(String errorCode) {
    this.errorCode = errorCode;
  }

  public JobboardDTO channels(List<Channel> channels) {
    this.channels = channels;
    return this;
  }

  public JobboardDTO addChannelsItem(Channel channelsItem) {
    if (this.channels == null) {
      this.channels = new ArrayList<>();
    }
    this.channels.add(channelsItem);
    return this;
  }

   /**
   * Get channels
   * @return channels
  **/
  public List<Channel> getChannels() {
    return channels;
  }

  public void setChannels(List<Channel> channels) {
    this.channels = channels;
  }

  public JobboardDTO postingActionAsEnum(PostingActionAsEnumEnum postingActionAsEnum) {
    this.postingActionAsEnum = postingActionAsEnum;
    return this;
  }

   /**
   * Get postingActionAsEnum
   * @return postingActionAsEnum
  **/
  public PostingActionAsEnumEnum getPostingActionAsEnum() {
    return postingActionAsEnum;
  }

  public void setPostingActionAsEnum(PostingActionAsEnumEnum postingActionAsEnum) {
    this.postingActionAsEnum = postingActionAsEnum;
  }

  public JobboardDTO postingStatusAsEnum(PostingStatusAsEnumEnum postingStatusAsEnum) {
    this.postingStatusAsEnum = postingStatusAsEnum;
    return this;
  }

   /**
   * Get postingStatusAsEnum
   * @return postingStatusAsEnum
  **/
  public PostingStatusAsEnumEnum getPostingStatusAsEnum() {
    return postingStatusAsEnum;
  }

  public void setPostingStatusAsEnum(PostingStatusAsEnumEnum postingStatusAsEnum) {
    this.postingStatusAsEnum = postingStatusAsEnum;
  }

  public JobboardDTO statusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
    return this;
  }

   /**
   * Get statusDescription
   * @return statusDescription
  **/
  public String getStatusDescription() {
    return statusDescription;
  }

  public void setStatusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobboardDTO jobboardDTO = (JobboardDTO) o;
    return Objects.equals(this.postingAction, jobboardDTO.postingAction) &&
        Objects.equals(this.postingStatus, jobboardDTO.postingStatus) &&
        Objects.equals(this.startDate, jobboardDTO.startDate) &&
        Objects.equals(this.endDate, jobboardDTO.endDate) &&
        Objects.equals(this.errorCode, jobboardDTO.errorCode) &&
        Objects.equals(this.channels, jobboardDTO.channels) &&
        Objects.equals(this.postingActionAsEnum, jobboardDTO.postingActionAsEnum) &&
        Objects.equals(this.postingStatusAsEnum, jobboardDTO.postingStatusAsEnum) &&
        Objects.equals(this.statusDescription, jobboardDTO.statusDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postingAction, postingStatus, startDate, endDate, errorCode, channels, postingActionAsEnum, postingStatusAsEnum, statusDescription);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobboardDTO {\n");
    
    sb.append("    postingAction: ").append(toIndentedString(postingAction)).append("\n");
    sb.append("    postingStatus: ").append(toIndentedString(postingStatus)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    channels: ").append(toIndentedString(channels)).append("\n");
    sb.append("    postingActionAsEnum: ").append(toIndentedString(postingActionAsEnum)).append("\n");
    sb.append("    postingStatusAsEnum: ").append(toIndentedString(postingStatusAsEnum)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
