/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * LinkToJobsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class LinkToJobsDto {
  @JsonProperty("requisitionIds")
  private List<Long> requisitionIds = null;

  @JsonProperty("copyAllDocuments")
  private Boolean copyAllDocuments = false;

  @JsonProperty("documentsIds")
  private List<Long> documentsIds = null;

  public LinkToJobsDto requisitionIds(List<Long> requisitionIds) {
    this.requisitionIds = requisitionIds;
    return this;
  }

  public LinkToJobsDto addRequisitionIdsItem(Long requisitionIdsItem) {
    if (this.requisitionIds == null) {
      this.requisitionIds = new ArrayList<>();
    }
    this.requisitionIds.add(requisitionIdsItem);
    return this;
  }

   /**
   * Get requisitionIds
   * @return requisitionIds
  **/
  public List<Long> getRequisitionIds() {
    return requisitionIds;
  }

  public void setRequisitionIds(List<Long> requisitionIds) {
    this.requisitionIds = requisitionIds;
  }

  public LinkToJobsDto copyAllDocuments(Boolean copyAllDocuments) {
    this.copyAllDocuments = copyAllDocuments;
    return this;
  }

   /**
   * Get copyAllDocuments
   * @return copyAllDocuments
  **/
  public Boolean isCopyAllDocuments() {
    return copyAllDocuments;
  }

  public void setCopyAllDocuments(Boolean copyAllDocuments) {
    this.copyAllDocuments = copyAllDocuments;
  }

  public LinkToJobsDto documentsIds(List<Long> documentsIds) {
    this.documentsIds = documentsIds;
    return this;
  }

  public LinkToJobsDto addDocumentsIdsItem(Long documentsIdsItem) {
    if (this.documentsIds == null) {
      this.documentsIds = new ArrayList<>();
    }
    this.documentsIds.add(documentsIdsItem);
    return this;
  }

   /**
   * Get documentsIds
   * @return documentsIds
  **/
  public List<Long> getDocumentsIds() {
    return documentsIds;
  }

  public void setDocumentsIds(List<Long> documentsIds) {
    this.documentsIds = documentsIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinkToJobsDto linkToJobsDto = (LinkToJobsDto) o;
    return Objects.equals(this.requisitionIds, linkToJobsDto.requisitionIds) &&
        Objects.equals(this.copyAllDocuments, linkToJobsDto.copyAllDocuments) &&
        Objects.equals(this.documentsIds, linkToJobsDto.documentsIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requisitionIds, copyAllDocuments, documentsIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinkToJobsDto {\n");
    
    sb.append("    requisitionIds: ").append(toIndentedString(requisitionIds)).append("\n");
    sb.append("    copyAllDocuments: ").append(toIndentedString(copyAllDocuments)).append("\n");
    sb.append("    documentsIds: ").append(toIndentedString(documentsIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
