/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LovValueDto;

import java.util.ArrayList;
import java.util.List;
/**
 * ListOfValuesDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class ListOfValuesDto {
  @JsonProperty("values")
  private List<LovValueDto> values = null;

  @JsonProperty("lovName")
  private String lovName = null;

  public ListOfValuesDto values(List<LovValueDto> values) {
    this.values = values;
    return this;
  }

  public ListOfValuesDto addValuesItem(LovValueDto valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  public List<LovValueDto> getValues() {
    return values;
  }

  public void setValues(List<LovValueDto> values) {
    this.values = values;
  }

  public ListOfValuesDto lovName(String lovName) {
    this.lovName = lovName;
    return this;
  }

   /**
   * Get lovName
   * @return lovName
  **/
  public String getLovName() {
    return lovName;
  }

  public void setLovName(String lovName) {
    this.lovName = lovName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListOfValuesDto listOfValuesDto = (ListOfValuesDto) o;
    return Objects.equals(this.values, listOfValuesDto.values) &&
        Objects.equals(this.lovName, listOfValuesDto.lovName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(values, lovName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListOfValuesDto {\n");
    
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    lovName: ").append(toIndentedString(lovName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
