/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LocationActionsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TranslationsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserDto;

/**
 * LocationFullDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class LocationFullDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("countryCodeAlpha2")
  private String countryCodeAlpha2 = null;

  @JsonProperty("countryCodeAlpha3")
  private String countryCodeAlpha3 = null;

  @JsonProperty("region")
  private String region = null;

  @JsonProperty("regionName")
  private String regionName = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("street")
  private String street = null;

  @JsonProperty("zipCode")
  private String zipCode = null;

  @JsonProperty("latitude")
  private Double latitude = null;

  @JsonProperty("longitude")
  private Double longitude = null;

  @JsonProperty("remote")
  private Boolean remote = false;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("countryTranslations")
  private TranslationsDto countryTranslations = null;

  @JsonProperty("regionTranslations")
  private TranslationsDto regionTranslations = null;

  @JsonProperty("creationDate")
  private Long creationDate = null;

  @JsonProperty("creationUser")
  private UserDto creationUser = null;

  @JsonProperty("updateDate")
  private Long updateDate = null;

  @JsonProperty("updateUser")
  private UserDto updateUser = null;

  @JsonProperty("department")
  private DepartmentDto department = null;

  @JsonProperty("actions")
  private LocationActionsDto actions = null;

  public LocationFullDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LocationFullDto country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public LocationFullDto countryCodeAlpha2(String countryCodeAlpha2) {
    this.countryCodeAlpha2 = countryCodeAlpha2;
    return this;
  }

   /**
   * Get countryCodeAlpha2
   * @return countryCodeAlpha2
  **/
  public String getCountryCodeAlpha2() {
    return countryCodeAlpha2;
  }

  public void setCountryCodeAlpha2(String countryCodeAlpha2) {
    this.countryCodeAlpha2 = countryCodeAlpha2;
  }

  public LocationFullDto countryCodeAlpha3(String countryCodeAlpha3) {
    this.countryCodeAlpha3 = countryCodeAlpha3;
    return this;
  }

   /**
   * Get countryCodeAlpha3
   * @return countryCodeAlpha3
  **/
  public String getCountryCodeAlpha3() {
    return countryCodeAlpha3;
  }

  public void setCountryCodeAlpha3(String countryCodeAlpha3) {
    this.countryCodeAlpha3 = countryCodeAlpha3;
  }

  public LocationFullDto region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public LocationFullDto regionName(String regionName) {
    this.regionName = regionName;
    return this;
  }

   /**
   * Get regionName
   * @return regionName
  **/
  public String getRegionName() {
    return regionName;
  }

  public void setRegionName(String regionName) {
    this.regionName = regionName;
  }

  public LocationFullDto city(String city) {
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public LocationFullDto street(String street) {
    this.street = street;
    return this;
  }

   /**
   * Get street
   * @return street
  **/
  public String getStreet() {
    return street;
  }

  public void setStreet(String street) {
    this.street = street;
  }

  public LocationFullDto zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

   /**
   * Get zipCode
   * @return zipCode
  **/
  public String getZipCode() {
    return zipCode;
  }

  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public LocationFullDto latitude(Double latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  public Double getLatitude() {
    return latitude;
  }

  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }

  public LocationFullDto longitude(Double longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  public Double getLongitude() {
    return longitude;
  }

  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }

  public LocationFullDto remote(Boolean remote) {
    this.remote = remote;
    return this;
  }

   /**
   * Get remote
   * @return remote
  **/
  public Boolean isRemote() {
    return remote;
  }

  public void setRemote(Boolean remote) {
    this.remote = remote;
  }

  public LocationFullDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public LocationFullDto countryTranslations(TranslationsDto countryTranslations) {
    this.countryTranslations = countryTranslations;
    return this;
  }

   /**
   * Get countryTranslations
   * @return countryTranslations
  **/
  public TranslationsDto getCountryTranslations() {
    return countryTranslations;
  }

  public void setCountryTranslations(TranslationsDto countryTranslations) {
    this.countryTranslations = countryTranslations;
  }

  public LocationFullDto regionTranslations(TranslationsDto regionTranslations) {
    this.regionTranslations = regionTranslations;
    return this;
  }

   /**
   * Get regionTranslations
   * @return regionTranslations
  **/
  public TranslationsDto getRegionTranslations() {
    return regionTranslations;
  }

  public void setRegionTranslations(TranslationsDto regionTranslations) {
    this.regionTranslations = regionTranslations;
  }

  public LocationFullDto creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }

  public LocationFullDto creationUser(UserDto creationUser) {
    this.creationUser = creationUser;
    return this;
  }

   /**
   * Get creationUser
   * @return creationUser
  **/
  public UserDto getCreationUser() {
    return creationUser;
  }

  public void setCreationUser(UserDto creationUser) {
    this.creationUser = creationUser;
  }

  public LocationFullDto updateDate(Long updateDate) {
    this.updateDate = updateDate;
    return this;
  }

   /**
   * Get updateDate
   * @return updateDate
  **/
  public Long getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Long updateDate) {
    this.updateDate = updateDate;
  }

  public LocationFullDto updateUser(UserDto updateUser) {
    this.updateUser = updateUser;
    return this;
  }

   /**
   * Get updateUser
   * @return updateUser
  **/
  public UserDto getUpdateUser() {
    return updateUser;
  }

  public void setUpdateUser(UserDto updateUser) {
    this.updateUser = updateUser;
  }

  public LocationFullDto department(DepartmentDto department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  public DepartmentDto getDepartment() {
    return department;
  }

  public void setDepartment(DepartmentDto department) {
    this.department = department;
  }

  public LocationFullDto actions(LocationActionsDto actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  public LocationActionsDto getActions() {
    return actions;
  }

  public void setActions(LocationActionsDto actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationFullDto locationFullDto = (LocationFullDto) o;
    return Objects.equals(this.name, locationFullDto.name) &&
        Objects.equals(this.country, locationFullDto.country) &&
        Objects.equals(this.countryCodeAlpha2, locationFullDto.countryCodeAlpha2) &&
        Objects.equals(this.countryCodeAlpha3, locationFullDto.countryCodeAlpha3) &&
        Objects.equals(this.region, locationFullDto.region) &&
        Objects.equals(this.regionName, locationFullDto.regionName) &&
        Objects.equals(this.city, locationFullDto.city) &&
        Objects.equals(this.street, locationFullDto.street) &&
        Objects.equals(this.zipCode, locationFullDto.zipCode) &&
        Objects.equals(this.latitude, locationFullDto.latitude) &&
        Objects.equals(this.longitude, locationFullDto.longitude) &&
        Objects.equals(this.remote, locationFullDto.remote) &&
        Objects.equals(this.id, locationFullDto.id) &&
        Objects.equals(this.countryTranslations, locationFullDto.countryTranslations) &&
        Objects.equals(this.regionTranslations, locationFullDto.regionTranslations) &&
        Objects.equals(this.creationDate, locationFullDto.creationDate) &&
        Objects.equals(this.creationUser, locationFullDto.creationUser) &&
        Objects.equals(this.updateDate, locationFullDto.updateDate) &&
        Objects.equals(this.updateUser, locationFullDto.updateUser) &&
        Objects.equals(this.department, locationFullDto.department) &&
        Objects.equals(this.actions, locationFullDto.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, country, countryCodeAlpha2, countryCodeAlpha3, region, regionName, city, street, zipCode, latitude, longitude, remote, id, countryTranslations, regionTranslations, creationDate, creationUser, updateDate, updateUser, department, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationFullDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryCodeAlpha2: ").append(toIndentedString(countryCodeAlpha2)).append("\n");
    sb.append("    countryCodeAlpha3: ").append(toIndentedString(countryCodeAlpha3)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    regionName: ").append(toIndentedString(regionName)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    street: ").append(toIndentedString(street)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    remote: ").append(toIndentedString(remote)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    countryTranslations: ").append(toIndentedString(countryTranslations)).append("\n");
    sb.append("    regionTranslations: ").append(toIndentedString(regionTranslations)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    creationUser: ").append(toIndentedString(creationUser)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    updateUser: ").append(toIndentedString(updateUser)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
