/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LocationFullDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LocationGlobalActionsDto;

import java.util.ArrayList;
import java.util.List;
/**
 * LocationGraphQlContent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class LocationGraphQlContent {
  @JsonProperty("locations")
  private List<LocationFullDto> locations = null;

  @JsonProperty("actions")
  private LocationGlobalActionsDto actions = null;

  public LocationGraphQlContent locations(List<LocationFullDto> locations) {
    this.locations = locations;
    return this;
  }

  public LocationGraphQlContent addLocationsItem(LocationFullDto locationsItem) {
    if (this.locations == null) {
      this.locations = new ArrayList<>();
    }
    this.locations.add(locationsItem);
    return this;
  }

   /**
   * Get locations
   * @return locations
  **/
  public List<LocationFullDto> getLocations() {
    return locations;
  }

  public void setLocations(List<LocationFullDto> locations) {
    this.locations = locations;
  }

  public LocationGraphQlContent actions(LocationGlobalActionsDto actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  public LocationGlobalActionsDto getActions() {
    return actions;
  }

  public void setActions(LocationGlobalActionsDto actions) {
    this.actions = actions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationGraphQlContent locationGraphQlContent = (LocationGraphQlContent) o;
    return Objects.equals(this.locations, locationGraphQlContent.locations) &&
        Objects.equals(this.actions, locationGraphQlContent.actions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locations, actions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationGraphQlContent {\n");
    
    sb.append("    locations: ").append(toIndentedString(locations)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
