/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TranslationsDto;

/**
 * LovDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class LovDto {
  @JsonProperty("nameLovId")
  private Long nameLovId = null;

  @JsonProperty("valueLovId")
  private Long valueLovId = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("nameTranslations")
  private TranslationsDto nameTranslations = null;

  @JsonProperty("valueTranslations")
  private TranslationsDto valueTranslations = null;

  public LovDto nameLovId(Long nameLovId) {
    this.nameLovId = nameLovId;
    return this;
  }

   /**
   * Get nameLovId
   * @return nameLovId
  **/
  public Long getNameLovId() {
    return nameLovId;
  }

  public void setNameLovId(Long nameLovId) {
    this.nameLovId = nameLovId;
  }

  public LovDto valueLovId(Long valueLovId) {
    this.valueLovId = valueLovId;
    return this;
  }

   /**
   * Get valueLovId
   * @return valueLovId
  **/
  public Long getValueLovId() {
    return valueLovId;
  }

  public void setValueLovId(Long valueLovId) {
    this.valueLovId = valueLovId;
  }

  public LovDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LovDto value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public LovDto nameTranslations(TranslationsDto nameTranslations) {
    this.nameTranslations = nameTranslations;
    return this;
  }

   /**
   * Get nameTranslations
   * @return nameTranslations
  **/
  public TranslationsDto getNameTranslations() {
    return nameTranslations;
  }

  public void setNameTranslations(TranslationsDto nameTranslations) {
    this.nameTranslations = nameTranslations;
  }

  public LovDto valueTranslations(TranslationsDto valueTranslations) {
    this.valueTranslations = valueTranslations;
    return this;
  }

   /**
   * Get valueTranslations
   * @return valueTranslations
  **/
  public TranslationsDto getValueTranslations() {
    return valueTranslations;
  }

  public void setValueTranslations(TranslationsDto valueTranslations) {
    this.valueTranslations = valueTranslations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LovDto lovDto = (LovDto) o;
    return Objects.equals(this.nameLovId, lovDto.nameLovId) &&
        Objects.equals(this.valueLovId, lovDto.valueLovId) &&
        Objects.equals(this.name, lovDto.name) &&
        Objects.equals(this.value, lovDto.value) &&
        Objects.equals(this.nameTranslations, lovDto.nameTranslations) &&
        Objects.equals(this.valueTranslations, lovDto.valueTranslations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameLovId, valueLovId, name, value, nameTranslations, valueTranslations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LovDto {\n");
    
    sb.append("    nameLovId: ").append(toIndentedString(nameLovId)).append("\n");
    sb.append("    valueLovId: ").append(toIndentedString(valueLovId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    nameTranslations: ").append(toIndentedString(nameTranslations)).append("\n");
    sb.append("    valueTranslations: ").append(toIndentedString(valueTranslations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
