/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.ConfigurableLovDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.FreeFormFieldTriggerDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.StandardFieldDto;

import java.util.ArrayList;
import java.util.List;
/**
 * OfferTermsDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class OfferTermsDto {
  @JsonProperty("standardFields")
  private List<StandardFieldDto> standardFields = null;

  @JsonProperty("configurableLovs")
  private List<ConfigurableLovDto> configurableLovs = null;

  @JsonProperty("freeFormFields")
  private List<FreeFormFieldTriggerDto> freeFormFields = null;

  public OfferTermsDto standardFields(List<StandardFieldDto> standardFields) {
    this.standardFields = standardFields;
    return this;
  }

  public OfferTermsDto addStandardFieldsItem(StandardFieldDto standardFieldsItem) {
    if (this.standardFields == null) {
      this.standardFields = new ArrayList<>();
    }
    this.standardFields.add(standardFieldsItem);
    return this;
  }

   /**
   * Get standardFields
   * @return standardFields
  **/
  public List<StandardFieldDto> getStandardFields() {
    return standardFields;
  }

  public void setStandardFields(List<StandardFieldDto> standardFields) {
    this.standardFields = standardFields;
  }

  public OfferTermsDto configurableLovs(List<ConfigurableLovDto> configurableLovs) {
    this.configurableLovs = configurableLovs;
    return this;
  }

  public OfferTermsDto addConfigurableLovsItem(ConfigurableLovDto configurableLovsItem) {
    if (this.configurableLovs == null) {
      this.configurableLovs = new ArrayList<>();
    }
    this.configurableLovs.add(configurableLovsItem);
    return this;
  }

   /**
   * Get configurableLovs
   * @return configurableLovs
  **/
  public List<ConfigurableLovDto> getConfigurableLovs() {
    return configurableLovs;
  }

  public void setConfigurableLovs(List<ConfigurableLovDto> configurableLovs) {
    this.configurableLovs = configurableLovs;
  }

  public OfferTermsDto freeFormFields(List<FreeFormFieldTriggerDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
    return this;
  }

  public OfferTermsDto addFreeFormFieldsItem(FreeFormFieldTriggerDto freeFormFieldsItem) {
    if (this.freeFormFields == null) {
      this.freeFormFields = new ArrayList<>();
    }
    this.freeFormFields.add(freeFormFieldsItem);
    return this;
  }

   /**
   * Get freeFormFields
   * @return freeFormFields
  **/
  public List<FreeFormFieldTriggerDto> getFreeFormFields() {
    return freeFormFields;
  }

  public void setFreeFormFields(List<FreeFormFieldTriggerDto> freeFormFields) {
    this.freeFormFields = freeFormFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferTermsDto offerTermsDto = (OfferTermsDto) o;
    return Objects.equals(this.standardFields, offerTermsDto.standardFields) &&
        Objects.equals(this.configurableLovs, offerTermsDto.configurableLovs) &&
        Objects.equals(this.freeFormFields, offerTermsDto.freeFormFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(standardFields, configurableLovs, freeFormFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferTermsDto {\n");
    
    sb.append("    standardFields: ").append(toIndentedString(standardFields)).append("\n");
    sb.append("    configurableLovs: ").append(toIndentedString(configurableLovs)).append("\n");
    sb.append("    freeFormFields: ").append(toIndentedString(freeFormFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
