/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PasswordFoRuleDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class PasswordFoRuleDto {
  @JsonProperty("secured")
  private Boolean secured = false;

  @JsonProperty("blockLoginAfterAttempts")
  private Long blockLoginAfterAttempts = null;

  @JsonProperty("blockLoginDays")
  private Long blockLoginDays = null;

  @JsonProperty("passwordExpire")
  private Long passwordExpire = null;

  @JsonProperty("passwordMinimumLength")
  private Long passwordMinimumLength = null;

  @JsonProperty("passwordMixedCase")
  private Boolean passwordMixedCase = false;

  @JsonProperty("passwordNumbers")
  private Boolean passwordNumbers = false;

  @JsonProperty("passwordSpecialCharacters")
  private Boolean passwordSpecialCharacters = false;

  @JsonProperty("passwordDifferentLast")
  private Long passwordDifferentLast = null;

  @JsonProperty("passwordDifferentThanPersonalAttributes")
  private Boolean passwordDifferentThanPersonalAttributes = false;

  @JsonProperty("displayRules")
  private Boolean displayRules = false;

  public PasswordFoRuleDto secured(Boolean secured) {
    this.secured = secured;
    return this;
  }

   /**
   * Get secured
   * @return secured
  **/
  public Boolean isSecured() {
    return secured;
  }

  public void setSecured(Boolean secured) {
    this.secured = secured;
  }

  public PasswordFoRuleDto blockLoginAfterAttempts(Long blockLoginAfterAttempts) {
    this.blockLoginAfterAttempts = blockLoginAfterAttempts;
    return this;
  }

   /**
   * Get blockLoginAfterAttempts
   * @return blockLoginAfterAttempts
  **/
  public Long getBlockLoginAfterAttempts() {
    return blockLoginAfterAttempts;
  }

  public void setBlockLoginAfterAttempts(Long blockLoginAfterAttempts) {
    this.blockLoginAfterAttempts = blockLoginAfterAttempts;
  }

  public PasswordFoRuleDto blockLoginDays(Long blockLoginDays) {
    this.blockLoginDays = blockLoginDays;
    return this;
  }

   /**
   * Get blockLoginDays
   * @return blockLoginDays
  **/
  public Long getBlockLoginDays() {
    return blockLoginDays;
  }

  public void setBlockLoginDays(Long blockLoginDays) {
    this.blockLoginDays = blockLoginDays;
  }

  public PasswordFoRuleDto passwordExpire(Long passwordExpire) {
    this.passwordExpire = passwordExpire;
    return this;
  }

   /**
   * Get passwordExpire
   * @return passwordExpire
  **/
  public Long getPasswordExpire() {
    return passwordExpire;
  }

  public void setPasswordExpire(Long passwordExpire) {
    this.passwordExpire = passwordExpire;
  }

  public PasswordFoRuleDto passwordMinimumLength(Long passwordMinimumLength) {
    this.passwordMinimumLength = passwordMinimumLength;
    return this;
  }

   /**
   * Get passwordMinimumLength
   * @return passwordMinimumLength
  **/
  public Long getPasswordMinimumLength() {
    return passwordMinimumLength;
  }

  public void setPasswordMinimumLength(Long passwordMinimumLength) {
    this.passwordMinimumLength = passwordMinimumLength;
  }

  public PasswordFoRuleDto passwordMixedCase(Boolean passwordMixedCase) {
    this.passwordMixedCase = passwordMixedCase;
    return this;
  }

   /**
   * Get passwordMixedCase
   * @return passwordMixedCase
  **/
  public Boolean isPasswordMixedCase() {
    return passwordMixedCase;
  }

  public void setPasswordMixedCase(Boolean passwordMixedCase) {
    this.passwordMixedCase = passwordMixedCase;
  }

  public PasswordFoRuleDto passwordNumbers(Boolean passwordNumbers) {
    this.passwordNumbers = passwordNumbers;
    return this;
  }

   /**
   * Get passwordNumbers
   * @return passwordNumbers
  **/
  public Boolean isPasswordNumbers() {
    return passwordNumbers;
  }

  public void setPasswordNumbers(Boolean passwordNumbers) {
    this.passwordNumbers = passwordNumbers;
  }

  public PasswordFoRuleDto passwordSpecialCharacters(Boolean passwordSpecialCharacters) {
    this.passwordSpecialCharacters = passwordSpecialCharacters;
    return this;
  }

   /**
   * Get passwordSpecialCharacters
   * @return passwordSpecialCharacters
  **/
  public Boolean isPasswordSpecialCharacters() {
    return passwordSpecialCharacters;
  }

  public void setPasswordSpecialCharacters(Boolean passwordSpecialCharacters) {
    this.passwordSpecialCharacters = passwordSpecialCharacters;
  }

  public PasswordFoRuleDto passwordDifferentLast(Long passwordDifferentLast) {
    this.passwordDifferentLast = passwordDifferentLast;
    return this;
  }

   /**
   * Get passwordDifferentLast
   * @return passwordDifferentLast
  **/
  public Long getPasswordDifferentLast() {
    return passwordDifferentLast;
  }

  public void setPasswordDifferentLast(Long passwordDifferentLast) {
    this.passwordDifferentLast = passwordDifferentLast;
  }

  public PasswordFoRuleDto passwordDifferentThanPersonalAttributes(Boolean passwordDifferentThanPersonalAttributes) {
    this.passwordDifferentThanPersonalAttributes = passwordDifferentThanPersonalAttributes;
    return this;
  }

   /**
   * Get passwordDifferentThanPersonalAttributes
   * @return passwordDifferentThanPersonalAttributes
  **/
  public Boolean isPasswordDifferentThanPersonalAttributes() {
    return passwordDifferentThanPersonalAttributes;
  }

  public void setPasswordDifferentThanPersonalAttributes(Boolean passwordDifferentThanPersonalAttributes) {
    this.passwordDifferentThanPersonalAttributes = passwordDifferentThanPersonalAttributes;
  }

  public PasswordFoRuleDto displayRules(Boolean displayRules) {
    this.displayRules = displayRules;
    return this;
  }

   /**
   * Get displayRules
   * @return displayRules
  **/
  public Boolean isDisplayRules() {
    return displayRules;
  }

  public void setDisplayRules(Boolean displayRules) {
    this.displayRules = displayRules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordFoRuleDto passwordFoRuleDto = (PasswordFoRuleDto) o;
    return Objects.equals(this.secured, passwordFoRuleDto.secured) &&
        Objects.equals(this.blockLoginAfterAttempts, passwordFoRuleDto.blockLoginAfterAttempts) &&
        Objects.equals(this.blockLoginDays, passwordFoRuleDto.blockLoginDays) &&
        Objects.equals(this.passwordExpire, passwordFoRuleDto.passwordExpire) &&
        Objects.equals(this.passwordMinimumLength, passwordFoRuleDto.passwordMinimumLength) &&
        Objects.equals(this.passwordMixedCase, passwordFoRuleDto.passwordMixedCase) &&
        Objects.equals(this.passwordNumbers, passwordFoRuleDto.passwordNumbers) &&
        Objects.equals(this.passwordSpecialCharacters, passwordFoRuleDto.passwordSpecialCharacters) &&
        Objects.equals(this.passwordDifferentLast, passwordFoRuleDto.passwordDifferentLast) &&
        Objects.equals(this.passwordDifferentThanPersonalAttributes, passwordFoRuleDto.passwordDifferentThanPersonalAttributes) &&
        Objects.equals(this.displayRules, passwordFoRuleDto.displayRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secured, blockLoginAfterAttempts, blockLoginDays, passwordExpire, passwordMinimumLength, passwordMixedCase, passwordNumbers, passwordSpecialCharacters, passwordDifferentLast, passwordDifferentThanPersonalAttributes, displayRules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordFoRuleDto {\n");
    
    sb.append("    secured: ").append(toIndentedString(secured)).append("\n");
    sb.append("    blockLoginAfterAttempts: ").append(toIndentedString(blockLoginAfterAttempts)).append("\n");
    sb.append("    blockLoginDays: ").append(toIndentedString(blockLoginDays)).append("\n");
    sb.append("    passwordExpire: ").append(toIndentedString(passwordExpire)).append("\n");
    sb.append("    passwordMinimumLength: ").append(toIndentedString(passwordMinimumLength)).append("\n");
    sb.append("    passwordMixedCase: ").append(toIndentedString(passwordMixedCase)).append("\n");
    sb.append("    passwordNumbers: ").append(toIndentedString(passwordNumbers)).append("\n");
    sb.append("    passwordSpecialCharacters: ").append(toIndentedString(passwordSpecialCharacters)).append("\n");
    sb.append("    passwordDifferentLast: ").append(toIndentedString(passwordDifferentLast)).append("\n");
    sb.append("    passwordDifferentThanPersonalAttributes: ").append(toIndentedString(passwordDifferentThanPersonalAttributes)).append("\n");
    sb.append("    displayRules: ").append(toIndentedString(displayRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
