/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.FormulaDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TranslationsDto;

import java.util.ArrayList;
import java.util.List;
/**
 * RateFormulaSetDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class RateFormulaSetDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("translations")
  private TranslationsDto translations = null;

  @JsonProperty("formulas")
  private List<FormulaDto> formulas = null;

  /**
   * Gets or Sets assignment
   */
  public enum AssignmentEnum {
    DEPARTMENT("Department"),
    CORPORATE("Corporate");

    private String value;

    AssignmentEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AssignmentEnum fromValue(String input) {
      for (AssignmentEnum b : AssignmentEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("assignment")
  private AssignmentEnum assignment = null;

  @JsonProperty("departments")
  private List<DepartmentDto> departments = null;

  @JsonProperty("active")
  private Boolean active = false;

  /**
   * Gets or Sets contractType
   */
  public enum ContractTypeEnum {
    DIRECT("Direct"),
    THIRDPARTY("ThirdParty");

    private String value;

    ContractTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ContractTypeEnum fromValue(String input) {
      for (ContractTypeEnum b : ContractTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("contractType")
  private ContractTypeEnum contractType = null;

  public RateFormulaSetDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public RateFormulaSetDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RateFormulaSetDto translations(TranslationsDto translations) {
    this.translations = translations;
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  public TranslationsDto getTranslations() {
    return translations;
  }

  public void setTranslations(TranslationsDto translations) {
    this.translations = translations;
  }

  public RateFormulaSetDto formulas(List<FormulaDto> formulas) {
    this.formulas = formulas;
    return this;
  }

  public RateFormulaSetDto addFormulasItem(FormulaDto formulasItem) {
    if (this.formulas == null) {
      this.formulas = new ArrayList<>();
    }
    this.formulas.add(formulasItem);
    return this;
  }

   /**
   * Get formulas
   * @return formulas
  **/
  public List<FormulaDto> getFormulas() {
    return formulas;
  }

  public void setFormulas(List<FormulaDto> formulas) {
    this.formulas = formulas;
  }

  public RateFormulaSetDto assignment(AssignmentEnum assignment) {
    this.assignment = assignment;
    return this;
  }

   /**
   * Get assignment
   * @return assignment
  **/
  public AssignmentEnum getAssignment() {
    return assignment;
  }

  public void setAssignment(AssignmentEnum assignment) {
    this.assignment = assignment;
  }

  public RateFormulaSetDto departments(List<DepartmentDto> departments) {
    this.departments = departments;
    return this;
  }

  public RateFormulaSetDto addDepartmentsItem(DepartmentDto departmentsItem) {
    if (this.departments == null) {
      this.departments = new ArrayList<>();
    }
    this.departments.add(departmentsItem);
    return this;
  }

   /**
   * Get departments
   * @return departments
  **/
  public List<DepartmentDto> getDepartments() {
    return departments;
  }

  public void setDepartments(List<DepartmentDto> departments) {
    this.departments = departments;
  }

  public RateFormulaSetDto active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  public Boolean isActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public RateFormulaSetDto contractType(ContractTypeEnum contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * Get contractType
   * @return contractType
  **/
  public ContractTypeEnum getContractType() {
    return contractType;
  }

  public void setContractType(ContractTypeEnum contractType) {
    this.contractType = contractType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RateFormulaSetDto rateFormulaSetDto = (RateFormulaSetDto) o;
    return Objects.equals(this.id, rateFormulaSetDto.id) &&
        Objects.equals(this.name, rateFormulaSetDto.name) &&
        Objects.equals(this.translations, rateFormulaSetDto.translations) &&
        Objects.equals(this.formulas, rateFormulaSetDto.formulas) &&
        Objects.equals(this.assignment, rateFormulaSetDto.assignment) &&
        Objects.equals(this.departments, rateFormulaSetDto.departments) &&
        Objects.equals(this.active, rateFormulaSetDto.active) &&
        Objects.equals(this.contractType, rateFormulaSetDto.contractType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, translations, formulas, assignment, departments, active, contractType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RateFormulaSetDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("    formulas: ").append(toIndentedString(formulas)).append("\n");
    sb.append("    assignment: ").append(toIndentedString(assignment)).append("\n");
    sb.append("    departments: ").append(toIndentedString(departments)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
