/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.CategoryNameDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.CustomLovGroup;

import java.util.ArrayList;
import java.util.List;
/**
 * SearchCriteriaDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class SearchCriteriaDto {
  @JsonProperty("generalApplication")
  private Boolean generalApplication = false;

  @JsonProperty("postedSince")
  private Integer postedSince = null;

  @JsonProperty("jobNumber")
  private String jobNumber = null;

  @JsonProperty("adLanguages")
  private List<String> adLanguages = null;

  @JsonProperty("countries")
  private List<Long> countries = null;

  @JsonProperty("regions")
  private List<Long> regions = null;

  @JsonProperty("contractTypes")
  private List<Long> contractTypes = null;

  @JsonProperty("scheduleTypes")
  private List<Long> scheduleTypes = null;

  @JsonProperty("customLovs")
  private List<CustomLovGroup> customLovs = null;

  @JsonProperty("keywords")
  private String keywords = null;

  @JsonProperty("categoryLists")
  private List<CategoryNameDto> categoryLists = null;

  @JsonProperty("organizationIds")
  private List<Long> organizationIds = null;

  @JsonProperty("countriesToBeFilltered")
  private List<String> countriesToBeFilltered = null;

  @JsonProperty("showImages")
  private Boolean showImages = false;

  public SearchCriteriaDto generalApplication(Boolean generalApplication) {
    this.generalApplication = generalApplication;
    return this;
  }

   /**
   * Get generalApplication
   * @return generalApplication
  **/
  public Boolean isGeneralApplication() {
    return generalApplication;
  }

  public void setGeneralApplication(Boolean generalApplication) {
    this.generalApplication = generalApplication;
  }

  public SearchCriteriaDto postedSince(Integer postedSince) {
    this.postedSince = postedSince;
    return this;
  }

   /**
   * Get postedSince
   * @return postedSince
  **/
  public Integer getPostedSince() {
    return postedSince;
  }

  public void setPostedSince(Integer postedSince) {
    this.postedSince = postedSince;
  }

  public SearchCriteriaDto jobNumber(String jobNumber) {
    this.jobNumber = jobNumber;
    return this;
  }

   /**
   * Get jobNumber
   * @return jobNumber
  **/
  public String getJobNumber() {
    return jobNumber;
  }

  public void setJobNumber(String jobNumber) {
    this.jobNumber = jobNumber;
  }

  public SearchCriteriaDto adLanguages(List<String> adLanguages) {
    this.adLanguages = adLanguages;
    return this;
  }

  public SearchCriteriaDto addAdLanguagesItem(String adLanguagesItem) {
    if (this.adLanguages == null) {
      this.adLanguages = new ArrayList<>();
    }
    this.adLanguages.add(adLanguagesItem);
    return this;
  }

   /**
   * Get adLanguages
   * @return adLanguages
  **/
  public List<String> getAdLanguages() {
    return adLanguages;
  }

  public void setAdLanguages(List<String> adLanguages) {
    this.adLanguages = adLanguages;
  }

  public SearchCriteriaDto countries(List<Long> countries) {
    this.countries = countries;
    return this;
  }

  public SearchCriteriaDto addCountriesItem(Long countriesItem) {
    if (this.countries == null) {
      this.countries = new ArrayList<>();
    }
    this.countries.add(countriesItem);
    return this;
  }

   /**
   * Get countries
   * @return countries
  **/
  public List<Long> getCountries() {
    return countries;
  }

  public void setCountries(List<Long> countries) {
    this.countries = countries;
  }

  public SearchCriteriaDto regions(List<Long> regions) {
    this.regions = regions;
    return this;
  }

  public SearchCriteriaDto addRegionsItem(Long regionsItem) {
    if (this.regions == null) {
      this.regions = new ArrayList<>();
    }
    this.regions.add(regionsItem);
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  public List<Long> getRegions() {
    return regions;
  }

  public void setRegions(List<Long> regions) {
    this.regions = regions;
  }

  public SearchCriteriaDto contractTypes(List<Long> contractTypes) {
    this.contractTypes = contractTypes;
    return this;
  }

  public SearchCriteriaDto addContractTypesItem(Long contractTypesItem) {
    if (this.contractTypes == null) {
      this.contractTypes = new ArrayList<>();
    }
    this.contractTypes.add(contractTypesItem);
    return this;
  }

   /**
   * Get contractTypes
   * @return contractTypes
  **/
  public List<Long> getContractTypes() {
    return contractTypes;
  }

  public void setContractTypes(List<Long> contractTypes) {
    this.contractTypes = contractTypes;
  }

  public SearchCriteriaDto scheduleTypes(List<Long> scheduleTypes) {
    this.scheduleTypes = scheduleTypes;
    return this;
  }

  public SearchCriteriaDto addScheduleTypesItem(Long scheduleTypesItem) {
    if (this.scheduleTypes == null) {
      this.scheduleTypes = new ArrayList<>();
    }
    this.scheduleTypes.add(scheduleTypesItem);
    return this;
  }

   /**
   * Get scheduleTypes
   * @return scheduleTypes
  **/
  public List<Long> getScheduleTypes() {
    return scheduleTypes;
  }

  public void setScheduleTypes(List<Long> scheduleTypes) {
    this.scheduleTypes = scheduleTypes;
  }

  public SearchCriteriaDto customLovs(List<CustomLovGroup> customLovs) {
    this.customLovs = customLovs;
    return this;
  }

  public SearchCriteriaDto addCustomLovsItem(CustomLovGroup customLovsItem) {
    if (this.customLovs == null) {
      this.customLovs = new ArrayList<>();
    }
    this.customLovs.add(customLovsItem);
    return this;
  }

   /**
   * Get customLovs
   * @return customLovs
  **/
  public List<CustomLovGroup> getCustomLovs() {
    return customLovs;
  }

  public void setCustomLovs(List<CustomLovGroup> customLovs) {
    this.customLovs = customLovs;
  }

  public SearchCriteriaDto keywords(String keywords) {
    this.keywords = keywords;
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  public String getKeywords() {
    return keywords;
  }

  public void setKeywords(String keywords) {
    this.keywords = keywords;
  }

  public SearchCriteriaDto categoryLists(List<CategoryNameDto> categoryLists) {
    this.categoryLists = categoryLists;
    return this;
  }

  public SearchCriteriaDto addCategoryListsItem(CategoryNameDto categoryListsItem) {
    if (this.categoryLists == null) {
      this.categoryLists = new ArrayList<>();
    }
    this.categoryLists.add(categoryListsItem);
    return this;
  }

   /**
   * Get categoryLists
   * @return categoryLists
  **/
  public List<CategoryNameDto> getCategoryLists() {
    return categoryLists;
  }

  public void setCategoryLists(List<CategoryNameDto> categoryLists) {
    this.categoryLists = categoryLists;
  }

  public SearchCriteriaDto organizationIds(List<Long> organizationIds) {
    this.organizationIds = organizationIds;
    return this;
  }

  public SearchCriteriaDto addOrganizationIdsItem(Long organizationIdsItem) {
    if (this.organizationIds == null) {
      this.organizationIds = new ArrayList<>();
    }
    this.organizationIds.add(organizationIdsItem);
    return this;
  }

   /**
   * Get organizationIds
   * @return organizationIds
  **/
  public List<Long> getOrganizationIds() {
    return organizationIds;
  }

  public void setOrganizationIds(List<Long> organizationIds) {
    this.organizationIds = organizationIds;
  }

  public SearchCriteriaDto countriesToBeFilltered(List<String> countriesToBeFilltered) {
    this.countriesToBeFilltered = countriesToBeFilltered;
    return this;
  }

  public SearchCriteriaDto addCountriesToBeFillteredItem(String countriesToBeFillteredItem) {
    if (this.countriesToBeFilltered == null) {
      this.countriesToBeFilltered = new ArrayList<>();
    }
    this.countriesToBeFilltered.add(countriesToBeFillteredItem);
    return this;
  }

   /**
   * Get countriesToBeFilltered
   * @return countriesToBeFilltered
  **/
  public List<String> getCountriesToBeFilltered() {
    return countriesToBeFilltered;
  }

  public void setCountriesToBeFilltered(List<String> countriesToBeFilltered) {
    this.countriesToBeFilltered = countriesToBeFilltered;
  }

  public SearchCriteriaDto showImages(Boolean showImages) {
    this.showImages = showImages;
    return this;
  }

   /**
   * Get showImages
   * @return showImages
  **/
  public Boolean isShowImages() {
    return showImages;
  }

  public void setShowImages(Boolean showImages) {
    this.showImages = showImages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCriteriaDto searchCriteriaDto = (SearchCriteriaDto) o;
    return Objects.equals(this.generalApplication, searchCriteriaDto.generalApplication) &&
        Objects.equals(this.postedSince, searchCriteriaDto.postedSince) &&
        Objects.equals(this.jobNumber, searchCriteriaDto.jobNumber) &&
        Objects.equals(this.adLanguages, searchCriteriaDto.adLanguages) &&
        Objects.equals(this.countries, searchCriteriaDto.countries) &&
        Objects.equals(this.regions, searchCriteriaDto.regions) &&
        Objects.equals(this.contractTypes, searchCriteriaDto.contractTypes) &&
        Objects.equals(this.scheduleTypes, searchCriteriaDto.scheduleTypes) &&
        Objects.equals(this.customLovs, searchCriteriaDto.customLovs) &&
        Objects.equals(this.keywords, searchCriteriaDto.keywords) &&
        Objects.equals(this.categoryLists, searchCriteriaDto.categoryLists) &&
        Objects.equals(this.organizationIds, searchCriteriaDto.organizationIds) &&
        Objects.equals(this.countriesToBeFilltered, searchCriteriaDto.countriesToBeFilltered) &&
        Objects.equals(this.showImages, searchCriteriaDto.showImages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generalApplication, postedSince, jobNumber, adLanguages, countries, regions, contractTypes, scheduleTypes, customLovs, keywords, categoryLists, organizationIds, countriesToBeFilltered, showImages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCriteriaDto {\n");
    
    sb.append("    generalApplication: ").append(toIndentedString(generalApplication)).append("\n");
    sb.append("    postedSince: ").append(toIndentedString(postedSince)).append("\n");
    sb.append("    jobNumber: ").append(toIndentedString(jobNumber)).append("\n");
    sb.append("    adLanguages: ").append(toIndentedString(adLanguages)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    contractTypes: ").append(toIndentedString(contractTypes)).append("\n");
    sb.append("    scheduleTypes: ").append(toIndentedString(scheduleTypes)).append("\n");
    sb.append("    customLovs: ").append(toIndentedString(customLovs)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    categoryLists: ").append(toIndentedString(categoryLists)).append("\n");
    sb.append("    organizationIds: ").append(toIndentedString(organizationIds)).append("\n");
    sb.append("    countriesToBeFilltered: ").append(toIndentedString(countriesToBeFilltered)).append("\n");
    sb.append("    showImages: ").append(toIndentedString(showImages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
