/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.AccountDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.SelectionProcessModelDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.SelectionTaskFullDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.TlkQueueDto;

import java.util.ArrayList;
import java.util.List;
/**
 * SelectionProcessModelDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class SelectionProcessModelDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("mandatory")
  private Boolean mandatory = false;

  @JsonProperty("get_strictEnforcement")
  private Boolean getStrictEnforcement = false;

  @JsonProperty("get_current")
  private Boolean getCurrent = false;

  @JsonProperty("get_markedPrivate")
  private Boolean getMarkedPrivate = false;

  @JsonProperty("get_archived")
  private Boolean getArchived = false;

  @JsonProperty("get_validated")
  private Boolean getValidated = false;

  @JsonProperty("version")
  private Integer version = null;

  @JsonProperty("queue")
  private TlkQueueDto queue = null;

  @JsonProperty("department")
  private DepartmentDto department = null;

  @JsonProperty("account")
  private AccountDto account = null;

  @JsonProperty("shortListCandidate")
  private Boolean shortListCandidate = false;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("comment")
  private String comment = null;

  @JsonProperty("parent")
  private SelectionProcessModelDto parent = null;

  @JsonProperty("tasks")
  private List<SelectionTaskFullDto> tasks = null;

  public SelectionProcessModelDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SelectionProcessModelDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SelectionProcessModelDto mandatory(Boolean mandatory) {
    this.mandatory = mandatory;
    return this;
  }

   /**
   * Get mandatory
   * @return mandatory
  **/
  public Boolean isMandatory() {
    return mandatory;
  }

  public void setMandatory(Boolean mandatory) {
    this.mandatory = mandatory;
  }

  public SelectionProcessModelDto getStrictEnforcement(Boolean getStrictEnforcement) {
    this.getStrictEnforcement = getStrictEnforcement;
    return this;
  }

   /**
   * Get getStrictEnforcement
   * @return getStrictEnforcement
  **/
  public Boolean isGetStrictEnforcement() {
    return getStrictEnforcement;
  }

  public void setGetStrictEnforcement(Boolean getStrictEnforcement) {
    this.getStrictEnforcement = getStrictEnforcement;
  }

  public SelectionProcessModelDto getCurrent(Boolean getCurrent) {
    this.getCurrent = getCurrent;
    return this;
  }

   /**
   * Get getCurrent
   * @return getCurrent
  **/
  public Boolean isGetCurrent() {
    return getCurrent;
  }

  public void setGetCurrent(Boolean getCurrent) {
    this.getCurrent = getCurrent;
  }

  public SelectionProcessModelDto getMarkedPrivate(Boolean getMarkedPrivate) {
    this.getMarkedPrivate = getMarkedPrivate;
    return this;
  }

   /**
   * Get getMarkedPrivate
   * @return getMarkedPrivate
  **/
  public Boolean isGetMarkedPrivate() {
    return getMarkedPrivate;
  }

  public void setGetMarkedPrivate(Boolean getMarkedPrivate) {
    this.getMarkedPrivate = getMarkedPrivate;
  }

  public SelectionProcessModelDto getArchived(Boolean getArchived) {
    this.getArchived = getArchived;
    return this;
  }

   /**
   * Get getArchived
   * @return getArchived
  **/
  public Boolean isGetArchived() {
    return getArchived;
  }

  public void setGetArchived(Boolean getArchived) {
    this.getArchived = getArchived;
  }

  public SelectionProcessModelDto getValidated(Boolean getValidated) {
    this.getValidated = getValidated;
    return this;
  }

   /**
   * Get getValidated
   * @return getValidated
  **/
  public Boolean isGetValidated() {
    return getValidated;
  }

  public void setGetValidated(Boolean getValidated) {
    this.getValidated = getValidated;
  }

  public SelectionProcessModelDto version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public SelectionProcessModelDto queue(TlkQueueDto queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  public TlkQueueDto getQueue() {
    return queue;
  }

  public void setQueue(TlkQueueDto queue) {
    this.queue = queue;
  }

  public SelectionProcessModelDto department(DepartmentDto department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  public DepartmentDto getDepartment() {
    return department;
  }

  public void setDepartment(DepartmentDto department) {
    this.department = department;
  }

  public SelectionProcessModelDto account(AccountDto account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  public AccountDto getAccount() {
    return account;
  }

  public void setAccount(AccountDto account) {
    this.account = account;
  }

  public SelectionProcessModelDto shortListCandidate(Boolean shortListCandidate) {
    this.shortListCandidate = shortListCandidate;
    return this;
  }

   /**
   * Get shortListCandidate
   * @return shortListCandidate
  **/
  public Boolean isShortListCandidate() {
    return shortListCandidate;
  }

  public void setShortListCandidate(Boolean shortListCandidate) {
    this.shortListCandidate = shortListCandidate;
  }

  public SelectionProcessModelDto description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SelectionProcessModelDto comment(String comment) {
    this.comment = comment;
    return this;
  }

   /**
   * Get comment
   * @return comment
  **/
  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public SelectionProcessModelDto parent(SelectionProcessModelDto parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  public SelectionProcessModelDto getParent() {
    return parent;
  }

  public void setParent(SelectionProcessModelDto parent) {
    this.parent = parent;
  }

  public SelectionProcessModelDto tasks(List<SelectionTaskFullDto> tasks) {
    this.tasks = tasks;
    return this;
  }

  public SelectionProcessModelDto addTasksItem(SelectionTaskFullDto tasksItem) {
    if (this.tasks == null) {
      this.tasks = new ArrayList<>();
    }
    this.tasks.add(tasksItem);
    return this;
  }

   /**
   * Get tasks
   * @return tasks
  **/
  public List<SelectionTaskFullDto> getTasks() {
    return tasks;
  }

  public void setTasks(List<SelectionTaskFullDto> tasks) {
    this.tasks = tasks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectionProcessModelDto selectionProcessModelDto = (SelectionProcessModelDto) o;
    return Objects.equals(this.id, selectionProcessModelDto.id) &&
        Objects.equals(this.name, selectionProcessModelDto.name) &&
        Objects.equals(this.mandatory, selectionProcessModelDto.mandatory) &&
        Objects.equals(this.getStrictEnforcement, selectionProcessModelDto.getStrictEnforcement) &&
        Objects.equals(this.getCurrent, selectionProcessModelDto.getCurrent) &&
        Objects.equals(this.getMarkedPrivate, selectionProcessModelDto.getMarkedPrivate) &&
        Objects.equals(this.getArchived, selectionProcessModelDto.getArchived) &&
        Objects.equals(this.getValidated, selectionProcessModelDto.getValidated) &&
        Objects.equals(this.version, selectionProcessModelDto.version) &&
        Objects.equals(this.queue, selectionProcessModelDto.queue) &&
        Objects.equals(this.department, selectionProcessModelDto.department) &&
        Objects.equals(this.account, selectionProcessModelDto.account) &&
        Objects.equals(this.shortListCandidate, selectionProcessModelDto.shortListCandidate) &&
        Objects.equals(this.description, selectionProcessModelDto.description) &&
        Objects.equals(this.comment, selectionProcessModelDto.comment) &&
        Objects.equals(this.parent, selectionProcessModelDto.parent) &&
        Objects.equals(this.tasks, selectionProcessModelDto.tasks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, mandatory, getStrictEnforcement, getCurrent, getMarkedPrivate, getArchived, getValidated, version, queue, department, account, shortListCandidate, description, comment, parent, tasks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectionProcessModelDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mandatory: ").append(toIndentedString(mandatory)).append("\n");
    sb.append("    getStrictEnforcement: ").append(toIndentedString(getStrictEnforcement)).append("\n");
    sb.append("    getCurrent: ").append(toIndentedString(getCurrent)).append("\n");
    sb.append("    getMarkedPrivate: ").append(toIndentedString(getMarkedPrivate)).append("\n");
    sb.append("    getArchived: ").append(toIndentedString(getArchived)).append("\n");
    sb.append("    getValidated: ").append(toIndentedString(getValidated)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    shortListCandidate: ").append(toIndentedString(shortListCandidate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    tasks: ").append(toIndentedString(tasks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
