/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SelectionStepStatusUpdateDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class SelectionStepStatusUpdateDto {
  /**
   * New status
   */
  public enum StepStatusEnum {
    AUTO_CLOSED("Auto-closed"),
    CANCEL("Cancel"),
    CLOSED("Closed"),
    CONFIRM("Confirm"),
    COMPLETED("Completed"),
    DECLINE("Decline"),
    INTERVIEWTOSCHEDULE("InterviewToSchedule"),
    INVITED("Invited"),
    ONHOLD("OnHold"),
    PENDING("Pending"),
    SUBMITABLE("SubmitAble"),
    SUBMITTED("Submitted"),
    PROCESSING("Processing");

    private String value;

    StepStatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StepStatusEnum fromValue(String input) {
      for (StepStatusEnum b : StepStatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("stepStatus")
  private StepStatusEnum stepStatus = null;

  public SelectionStepStatusUpdateDto stepStatus(StepStatusEnum stepStatus) {
    this.stepStatus = stepStatus;
    return this;
  }

   /**
   * New status
   * @return stepStatus
  **/
  public StepStatusEnum getStepStatus() {
    return stepStatus;
  }

  public void setStepStatus(StepStatusEnum stepStatus) {
    this.stepStatus = stepStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelectionStepStatusUpdateDto selectionStepStatusUpdateDto = (SelectionStepStatusUpdateDto) o;
    return Objects.equals(this.stepStatus, selectionStepStatusUpdateDto.stepStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stepStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelectionStepStatusUpdateDto {\n");
    
    sb.append("    stepStatus: ").append(toIndentedString(stepStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
