/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.LocationDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.SlotResponseDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserDto;

import java.util.ArrayList;
import java.util.List;
/**
 * SelfBookingSlotDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class SelfBookingSlotDto {
  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("startDate")
  private Long startDate = null;

  @JsonProperty("endDate")
  private Long endDate = null;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    FREE("FREE"),
    BUSY("BUSY"),
    CANCELLED("CANCELLED"),
    DECLINED("DECLINED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("creationUser")
  private UserDto creationUser = null;

  @JsonProperty("meetingCorrelationId")
  private String meetingCorrelationId = null;

  @JsonProperty("location")
  private LocationDto location = null;

  @JsonProperty("externalMeetingId")
  private String externalMeetingId = null;

  @JsonProperty("slotResponses")
  private List<SlotResponseDto> slotResponses = null;

  public SelfBookingSlotDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public SelfBookingSlotDto startDate(Long startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate
  **/
  public Long getStartDate() {
    return startDate;
  }

  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  public SelfBookingSlotDto endDate(Long endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate
  **/
  public Long getEndDate() {
    return endDate;
  }

  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  public SelfBookingSlotDto status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SelfBookingSlotDto creationUser(UserDto creationUser) {
    this.creationUser = creationUser;
    return this;
  }

   /**
   * Get creationUser
   * @return creationUser
  **/
  public UserDto getCreationUser() {
    return creationUser;
  }

  public void setCreationUser(UserDto creationUser) {
    this.creationUser = creationUser;
  }

  public SelfBookingSlotDto meetingCorrelationId(String meetingCorrelationId) {
    this.meetingCorrelationId = meetingCorrelationId;
    return this;
  }

   /**
   * Get meetingCorrelationId
   * @return meetingCorrelationId
  **/
  public String getMeetingCorrelationId() {
    return meetingCorrelationId;
  }

  public void setMeetingCorrelationId(String meetingCorrelationId) {
    this.meetingCorrelationId = meetingCorrelationId;
  }

  public SelfBookingSlotDto location(LocationDto location) {
    this.location = location;
    return this;
  }

   /**
   * Get location
   * @return location
  **/
  public LocationDto getLocation() {
    return location;
  }

  public void setLocation(LocationDto location) {
    this.location = location;
  }

  public SelfBookingSlotDto externalMeetingId(String externalMeetingId) {
    this.externalMeetingId = externalMeetingId;
    return this;
  }

   /**
   * Get externalMeetingId
   * @return externalMeetingId
  **/
  public String getExternalMeetingId() {
    return externalMeetingId;
  }

  public void setExternalMeetingId(String externalMeetingId) {
    this.externalMeetingId = externalMeetingId;
  }

  public SelfBookingSlotDto slotResponses(List<SlotResponseDto> slotResponses) {
    this.slotResponses = slotResponses;
    return this;
  }

  public SelfBookingSlotDto addSlotResponsesItem(SlotResponseDto slotResponsesItem) {
    if (this.slotResponses == null) {
      this.slotResponses = new ArrayList<>();
    }
    this.slotResponses.add(slotResponsesItem);
    return this;
  }

   /**
   * Get slotResponses
   * @return slotResponses
  **/
  public List<SlotResponseDto> getSlotResponses() {
    return slotResponses;
  }

  public void setSlotResponses(List<SlotResponseDto> slotResponses) {
    this.slotResponses = slotResponses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfBookingSlotDto selfBookingSlotDto = (SelfBookingSlotDto) o;
    return Objects.equals(this.id, selfBookingSlotDto.id) &&
        Objects.equals(this.startDate, selfBookingSlotDto.startDate) &&
        Objects.equals(this.endDate, selfBookingSlotDto.endDate) &&
        Objects.equals(this.status, selfBookingSlotDto.status) &&
        Objects.equals(this.creationUser, selfBookingSlotDto.creationUser) &&
        Objects.equals(this.meetingCorrelationId, selfBookingSlotDto.meetingCorrelationId) &&
        Objects.equals(this.location, selfBookingSlotDto.location) &&
        Objects.equals(this.externalMeetingId, selfBookingSlotDto.externalMeetingId) &&
        Objects.equals(this.slotResponses, selfBookingSlotDto.slotResponses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, startDate, endDate, status, creationUser, meetingCorrelationId, location, externalMeetingId, slotResponses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfBookingSlotDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    creationUser: ").append(toIndentedString(creationUser)).append("\n");
    sb.append("    meetingCorrelationId: ").append(toIndentedString(meetingCorrelationId)).append("\n");
    sb.append("    location: ").append(toIndentedString(location)).append("\n");
    sb.append("    externalMeetingId: ").append(toIndentedString(externalMeetingId)).append("\n");
    sb.append("    slotResponses: ").append(toIndentedString(slotResponses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
