/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DepartmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserDto;

/**
 * TagTypeDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class TagTypeDto {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("labelKey")
  private String labelKey = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("department")
  private DepartmentDto department = null;

  @JsonProperty("creationUser")
  private UserDto creationUser = null;

  public TagTypeDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TagTypeDto labelKey(String labelKey) {
    this.labelKey = labelKey;
    return this;
  }

   /**
   * Get labelKey
   * @return labelKey
  **/
  public String getLabelKey() {
    return labelKey;
  }

  public void setLabelKey(String labelKey) {
    this.labelKey = labelKey;
  }

  public TagTypeDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public TagTypeDto department(DepartmentDto department) {
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  public DepartmentDto getDepartment() {
    return department;
  }

  public void setDepartment(DepartmentDto department) {
    this.department = department;
  }

  public TagTypeDto creationUser(UserDto creationUser) {
    this.creationUser = creationUser;
    return this;
  }

   /**
   * Get creationUser
   * @return creationUser
  **/
  public UserDto getCreationUser() {
    return creationUser;
  }

  public void setCreationUser(UserDto creationUser) {
    this.creationUser = creationUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagTypeDto tagTypeDto = (TagTypeDto) o;
    return Objects.equals(this.name, tagTypeDto.name) &&
        Objects.equals(this.labelKey, tagTypeDto.labelKey) &&
        Objects.equals(this.id, tagTypeDto.id) &&
        Objects.equals(this.department, tagTypeDto.department) &&
        Objects.equals(this.creationUser, tagTypeDto.creationUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, labelKey, id, department, creationUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagTypeDto {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    labelKey: ").append(toIndentedString(labelKey)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    creationUser: ").append(toIndentedString(creationUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
