/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.IdDto;

/**
 * TeamMemberBasicDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class TeamMemberBasicDto {
  @JsonProperty("order")
  private Integer order = null;

  @JsonProperty("lovValue")
  private String lovValue = null;

  @JsonProperty("user")
  private IdDto user = null;

  @JsonProperty("userId")
  private Long userId = null;

  public TeamMemberBasicDto order(Integer order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public TeamMemberBasicDto lovValue(String lovValue) {
    this.lovValue = lovValue;
    return this;
  }

   /**
   * Get lovValue
   * @return lovValue
  **/
  public String getLovValue() {
    return lovValue;
  }

  public void setLovValue(String lovValue) {
    this.lovValue = lovValue;
  }

  public TeamMemberBasicDto user(IdDto user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  public IdDto getUser() {
    return user;
  }

  public void setUser(IdDto user) {
    this.user = user;
  }

  public TeamMemberBasicDto userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TeamMemberBasicDto teamMemberBasicDto = (TeamMemberBasicDto) o;
    return Objects.equals(this.order, teamMemberBasicDto.order) &&
        Objects.equals(this.lovValue, teamMemberBasicDto.lovValue) &&
        Objects.equals(this.user, teamMemberBasicDto.user) &&
        Objects.equals(this.userId, teamMemberBasicDto.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, lovValue, user, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TeamMemberBasicDto {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    lovValue: ").append(toIndentedString(lovValue)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
