/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UpdateApplicationScoreDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class UpdateApplicationScoreDto {
  @JsonProperty("score")
  private Double score = null;

  @JsonProperty("system")
  private String system = null;

  @JsonProperty("info")
  private String info = null;

  @JsonProperty("applicationId")
  private Long applicationId = null;

  @JsonProperty("populateScoreToChildApplications")
  private Boolean populateScoreToChildApplications = false;

  public UpdateApplicationScoreDto score(Double score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  public Double getScore() {
    return score;
  }

  public void setScore(Double score) {
    this.score = score;
  }

  public UpdateApplicationScoreDto system(String system) {
    this.system = system;
    return this;
  }

   /**
   * Get system
   * @return system
  **/
  public String getSystem() {
    return system;
  }

  public void setSystem(String system) {
    this.system = system;
  }

  public UpdateApplicationScoreDto info(String info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  public String getInfo() {
    return info;
  }

  public void setInfo(String info) {
    this.info = info;
  }

  public UpdateApplicationScoreDto applicationId(Long applicationId) {
    this.applicationId = applicationId;
    return this;
  }

   /**
   * Get applicationId
   * @return applicationId
  **/
  public Long getApplicationId() {
    return applicationId;
  }

  public void setApplicationId(Long applicationId) {
    this.applicationId = applicationId;
  }

  public UpdateApplicationScoreDto populateScoreToChildApplications(Boolean populateScoreToChildApplications) {
    this.populateScoreToChildApplications = populateScoreToChildApplications;
    return this;
  }

   /**
   * Get populateScoreToChildApplications
   * @return populateScoreToChildApplications
  **/
  public Boolean isPopulateScoreToChildApplications() {
    return populateScoreToChildApplications;
  }

  public void setPopulateScoreToChildApplications(Boolean populateScoreToChildApplications) {
    this.populateScoreToChildApplications = populateScoreToChildApplications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplicationScoreDto updateApplicationScoreDto = (UpdateApplicationScoreDto) o;
    return Objects.equals(this.score, updateApplicationScoreDto.score) &&
        Objects.equals(this.system, updateApplicationScoreDto.system) &&
        Objects.equals(this.info, updateApplicationScoreDto.info) &&
        Objects.equals(this.applicationId, updateApplicationScoreDto.applicationId) &&
        Objects.equals(this.populateScoreToChildApplications, updateApplicationScoreDto.populateScoreToChildApplications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(score, system, info, applicationId, populateScoreToChildApplications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplicationScoreDto {\n");
    
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    applicationId: ").append(toIndentedString(applicationId)).append("\n");
    sb.append("    populateScoreToChildApplications: ").append(toIndentedString(populateScoreToChildApplications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
