/*
 * Talentlink REST API Documentation
 * This is a live documentation of Talentlink RESTful services.  You will find detailed descriptions on how to use the TalentLink Exchange API to build your integrations in Developers Guide.  To use this documentation and call first go to green <span class=\"bold-span\">\"Authorize\"</span> button and provide your credentials. Once you do this you will be able to call the API directly from this page. However, if you only wish to check the syntax or list the filters then credentials are not mandatory.  To write a query, go to any method, expand it and press <span class=\"bold-span\">\"Try it out\"</span> button. It will display the method details window where in case of GET methods you will be able to write the query and check the filters.  You will also notice some of the methods have more specific details in their descriptions.  <span class=\"bold-span\">QuickTip:</span> when writing the GraphQL query you can use CTRL + SPACE to see suggestions of the available schemas/tags.
 *
 * OpenAPI spec version: 23.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.lumessetalentlink.shared.apiproxy.tlk.rest.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.DocumentSecurityDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.EventNotificationConfigurationDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.MailGatewayConfigurationDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.PersonalJobTemplateFullDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.RoleAssignmentDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.RoleDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserActionsDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserDataDto;
import com.lumessetalentlink.shared.apiproxy.tlk.rest.client.UserPreferencesDto;

import java.util.ArrayList;
import java.util.List;
/**
 * UserFullDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-13T12:07:01.346534600+01:00[Europe/Prague]")
public class UserFullDto {
  @JsonProperty("login")
  private String login = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("language")
  private String language = null;

  @JsonProperty("mss")
  private Boolean mss = false;

  @JsonProperty("disabledLoginPage")
  private Boolean disabledLoginPage = false;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("updateDate")
  private Long updateDate = null;

  @JsonProperty("creationDate")
  private Long creationDate = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("mustChangePassword")
  private Boolean mustChangePassword = false;

  @JsonProperty("roleAssignments")
  private List<RoleAssignmentDto> roleAssignments = null;

  @JsonProperty("mailGatewayConfiguration")
  private MailGatewayConfigurationDto mailGatewayConfiguration = null;

  @JsonProperty("eventNotificationConfiguration")
  private EventNotificationConfigurationDto eventNotificationConfiguration = null;

  @JsonProperty("userPreferences")
  private UserPreferencesDto userPreferences = null;

  @JsonProperty("userData")
  private UserDataDto userData = null;

  @JsonProperty("roleInRequisition")
  private RoleDto roleInRequisition = null;

  @JsonProperty("roleToReceiveCandidate")
  private RoleDto roleToReceiveCandidate = null;

  @JsonProperty("documentSecurity")
  private List<DocumentSecurityDto> documentSecurity = null;

  @JsonProperty("emailContact")
  private Boolean emailContact = false;

  @JsonProperty("actions")
  private UserActionsDto actions = null;

  @JsonProperty("personalJobTemplates")
  private List<PersonalJobTemplateFullDto> personalJobTemplates = null;

  @JsonProperty("publicKeyConfigured")
  private Boolean publicKeyConfigured = false;

  public UserFullDto login(String login) {
    this.login = login;
    return this;
  }

   /**
   * Get login
   * @return login
  **/
  public String getLogin() {
    return login;
  }

  public void setLogin(String login) {
    this.login = login;
  }

  public UserFullDto firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public UserFullDto lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public UserFullDto email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserFullDto language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public UserFullDto mss(Boolean mss) {
    this.mss = mss;
    return this;
  }

   /**
   * Get mss
   * @return mss
  **/
  public Boolean isMss() {
    return mss;
  }

  public void setMss(Boolean mss) {
    this.mss = mss;
  }

  public UserFullDto disabledLoginPage(Boolean disabledLoginPage) {
    this.disabledLoginPage = disabledLoginPage;
    return this;
  }

   /**
   * Get disabledLoginPage
   * @return disabledLoginPage
  **/
  public Boolean isDisabledLoginPage() {
    return disabledLoginPage;
  }

  public void setDisabledLoginPage(Boolean disabledLoginPage) {
    this.disabledLoginPage = disabledLoginPage;
  }

  public UserFullDto id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserFullDto updateDate(Long updateDate) {
    this.updateDate = updateDate;
    return this;
  }

   /**
   * Get updateDate
   * @return updateDate
  **/
  public Long getUpdateDate() {
    return updateDate;
  }

  public void setUpdateDate(Long updateDate) {
    this.updateDate = updateDate;
  }

  public UserFullDto creationDate(Long creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  public Long getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(Long creationDate) {
    this.creationDate = creationDate;
  }

  public UserFullDto status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public UserFullDto mustChangePassword(Boolean mustChangePassword) {
    this.mustChangePassword = mustChangePassword;
    return this;
  }

   /**
   * Get mustChangePassword
   * @return mustChangePassword
  **/
  public Boolean isMustChangePassword() {
    return mustChangePassword;
  }

  public void setMustChangePassword(Boolean mustChangePassword) {
    this.mustChangePassword = mustChangePassword;
  }

  public UserFullDto roleAssignments(List<RoleAssignmentDto> roleAssignments) {
    this.roleAssignments = roleAssignments;
    return this;
  }

  public UserFullDto addRoleAssignmentsItem(RoleAssignmentDto roleAssignmentsItem) {
    if (this.roleAssignments == null) {
      this.roleAssignments = new ArrayList<>();
    }
    this.roleAssignments.add(roleAssignmentsItem);
    return this;
  }

   /**
   * Get roleAssignments
   * @return roleAssignments
  **/
  public List<RoleAssignmentDto> getRoleAssignments() {
    return roleAssignments;
  }

  public void setRoleAssignments(List<RoleAssignmentDto> roleAssignments) {
    this.roleAssignments = roleAssignments;
  }

  public UserFullDto mailGatewayConfiguration(MailGatewayConfigurationDto mailGatewayConfiguration) {
    this.mailGatewayConfiguration = mailGatewayConfiguration;
    return this;
  }

   /**
   * Get mailGatewayConfiguration
   * @return mailGatewayConfiguration
  **/
  public MailGatewayConfigurationDto getMailGatewayConfiguration() {
    return mailGatewayConfiguration;
  }

  public void setMailGatewayConfiguration(MailGatewayConfigurationDto mailGatewayConfiguration) {
    this.mailGatewayConfiguration = mailGatewayConfiguration;
  }

  public UserFullDto eventNotificationConfiguration(EventNotificationConfigurationDto eventNotificationConfiguration) {
    this.eventNotificationConfiguration = eventNotificationConfiguration;
    return this;
  }

   /**
   * Get eventNotificationConfiguration
   * @return eventNotificationConfiguration
  **/
  public EventNotificationConfigurationDto getEventNotificationConfiguration() {
    return eventNotificationConfiguration;
  }

  public void setEventNotificationConfiguration(EventNotificationConfigurationDto eventNotificationConfiguration) {
    this.eventNotificationConfiguration = eventNotificationConfiguration;
  }

  public UserFullDto userPreferences(UserPreferencesDto userPreferences) {
    this.userPreferences = userPreferences;
    return this;
  }

   /**
   * Get userPreferences
   * @return userPreferences
  **/
  public UserPreferencesDto getUserPreferences() {
    return userPreferences;
  }

  public void setUserPreferences(UserPreferencesDto userPreferences) {
    this.userPreferences = userPreferences;
  }

  public UserFullDto userData(UserDataDto userData) {
    this.userData = userData;
    return this;
  }

   /**
   * Get userData
   * @return userData
  **/
  public UserDataDto getUserData() {
    return userData;
  }

  public void setUserData(UserDataDto userData) {
    this.userData = userData;
  }

  public UserFullDto roleInRequisition(RoleDto roleInRequisition) {
    this.roleInRequisition = roleInRequisition;
    return this;
  }

   /**
   * Get roleInRequisition
   * @return roleInRequisition
  **/
  public RoleDto getRoleInRequisition() {
    return roleInRequisition;
  }

  public void setRoleInRequisition(RoleDto roleInRequisition) {
    this.roleInRequisition = roleInRequisition;
  }

  public UserFullDto roleToReceiveCandidate(RoleDto roleToReceiveCandidate) {
    this.roleToReceiveCandidate = roleToReceiveCandidate;
    return this;
  }

   /**
   * Get roleToReceiveCandidate
   * @return roleToReceiveCandidate
  **/
  public RoleDto getRoleToReceiveCandidate() {
    return roleToReceiveCandidate;
  }

  public void setRoleToReceiveCandidate(RoleDto roleToReceiveCandidate) {
    this.roleToReceiveCandidate = roleToReceiveCandidate;
  }

  public UserFullDto documentSecurity(List<DocumentSecurityDto> documentSecurity) {
    this.documentSecurity = documentSecurity;
    return this;
  }

  public UserFullDto addDocumentSecurityItem(DocumentSecurityDto documentSecurityItem) {
    if (this.documentSecurity == null) {
      this.documentSecurity = new ArrayList<>();
    }
    this.documentSecurity.add(documentSecurityItem);
    return this;
  }

   /**
   * Get documentSecurity
   * @return documentSecurity
  **/
  public List<DocumentSecurityDto> getDocumentSecurity() {
    return documentSecurity;
  }

  public void setDocumentSecurity(List<DocumentSecurityDto> documentSecurity) {
    this.documentSecurity = documentSecurity;
  }

  public UserFullDto emailContact(Boolean emailContact) {
    this.emailContact = emailContact;
    return this;
  }

   /**
   * Get emailContact
   * @return emailContact
  **/
  public Boolean isEmailContact() {
    return emailContact;
  }

  public void setEmailContact(Boolean emailContact) {
    this.emailContact = emailContact;
  }

  public UserFullDto actions(UserActionsDto actions) {
    this.actions = actions;
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  public UserActionsDto getActions() {
    return actions;
  }

  public void setActions(UserActionsDto actions) {
    this.actions = actions;
  }

  public UserFullDto personalJobTemplates(List<PersonalJobTemplateFullDto> personalJobTemplates) {
    this.personalJobTemplates = personalJobTemplates;
    return this;
  }

  public UserFullDto addPersonalJobTemplatesItem(PersonalJobTemplateFullDto personalJobTemplatesItem) {
    if (this.personalJobTemplates == null) {
      this.personalJobTemplates = new ArrayList<>();
    }
    this.personalJobTemplates.add(personalJobTemplatesItem);
    return this;
  }

   /**
   * Get personalJobTemplates
   * @return personalJobTemplates
  **/
  public List<PersonalJobTemplateFullDto> getPersonalJobTemplates() {
    return personalJobTemplates;
  }

  public void setPersonalJobTemplates(List<PersonalJobTemplateFullDto> personalJobTemplates) {
    this.personalJobTemplates = personalJobTemplates;
  }

  public UserFullDto publicKeyConfigured(Boolean publicKeyConfigured) {
    this.publicKeyConfigured = publicKeyConfigured;
    return this;
  }

   /**
   * Get publicKeyConfigured
   * @return publicKeyConfigured
  **/
  public Boolean isPublicKeyConfigured() {
    return publicKeyConfigured;
  }

  public void setPublicKeyConfigured(Boolean publicKeyConfigured) {
    this.publicKeyConfigured = publicKeyConfigured;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserFullDto userFullDto = (UserFullDto) o;
    return Objects.equals(this.login, userFullDto.login) &&
        Objects.equals(this.firstName, userFullDto.firstName) &&
        Objects.equals(this.lastName, userFullDto.lastName) &&
        Objects.equals(this.email, userFullDto.email) &&
        Objects.equals(this.language, userFullDto.language) &&
        Objects.equals(this.mss, userFullDto.mss) &&
        Objects.equals(this.disabledLoginPage, userFullDto.disabledLoginPage) &&
        Objects.equals(this.id, userFullDto.id) &&
        Objects.equals(this.updateDate, userFullDto.updateDate) &&
        Objects.equals(this.creationDate, userFullDto.creationDate) &&
        Objects.equals(this.status, userFullDto.status) &&
        Objects.equals(this.mustChangePassword, userFullDto.mustChangePassword) &&
        Objects.equals(this.roleAssignments, userFullDto.roleAssignments) &&
        Objects.equals(this.mailGatewayConfiguration, userFullDto.mailGatewayConfiguration) &&
        Objects.equals(this.eventNotificationConfiguration, userFullDto.eventNotificationConfiguration) &&
        Objects.equals(this.userPreferences, userFullDto.userPreferences) &&
        Objects.equals(this.userData, userFullDto.userData) &&
        Objects.equals(this.roleInRequisition, userFullDto.roleInRequisition) &&
        Objects.equals(this.roleToReceiveCandidate, userFullDto.roleToReceiveCandidate) &&
        Objects.equals(this.documentSecurity, userFullDto.documentSecurity) &&
        Objects.equals(this.emailContact, userFullDto.emailContact) &&
        Objects.equals(this.actions, userFullDto.actions) &&
        Objects.equals(this.personalJobTemplates, userFullDto.personalJobTemplates) &&
        Objects.equals(this.publicKeyConfigured, userFullDto.publicKeyConfigured);
  }

  @Override
  public int hashCode() {
    return Objects.hash(login, firstName, lastName, email, language, mss, disabledLoginPage, id, updateDate, creationDate, status, mustChangePassword, roleAssignments, mailGatewayConfiguration, eventNotificationConfiguration, userPreferences, userData, roleInRequisition, roleToReceiveCandidate, documentSecurity, emailContact, actions, personalJobTemplates, publicKeyConfigured);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserFullDto {\n");
    
    sb.append("    login: ").append(toIndentedString(login)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    mss: ").append(toIndentedString(mss)).append("\n");
    sb.append("    disabledLoginPage: ").append(toIndentedString(disabledLoginPage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updateDate: ").append(toIndentedString(updateDate)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    mustChangePassword: ").append(toIndentedString(mustChangePassword)).append("\n");
    sb.append("    roleAssignments: ").append(toIndentedString(roleAssignments)).append("\n");
    sb.append("    mailGatewayConfiguration: ").append(toIndentedString(mailGatewayConfiguration)).append("\n");
    sb.append("    eventNotificationConfiguration: ").append(toIndentedString(eventNotificationConfiguration)).append("\n");
    sb.append("    userPreferences: ").append(toIndentedString(userPreferences)).append("\n");
    sb.append("    userData: ").append(toIndentedString(userData)).append("\n");
    sb.append("    roleInRequisition: ").append(toIndentedString(roleInRequisition)).append("\n");
    sb.append("    roleToReceiveCandidate: ").append(toIndentedString(roleToReceiveCandidate)).append("\n");
    sb.append("    documentSecurity: ").append(toIndentedString(documentSecurity)).append("\n");
    sb.append("    emailContact: ").append(toIndentedString(emailContact)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    personalJobTemplates: ").append(toIndentedString(personalJobTemplates)).append("\n");
    sb.append("    publicKeyConfigured: ").append(toIndentedString(publicKeyConfigured)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
